// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/dao/dao.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'

export const protobufPackage = 'metaearth.dao'

/** GenesisState defines the sudo module's genesis state. */
export interface DaoAddresses {
  globalDao: string
  meidDao: string
  devOperator: string
  airdropAddress: string
}

function createBaseDaoAddresses(): DaoAddresses {
  return { globalDao: '', meidDao: '', devOperator: '', airdropAddress: '' }
}

export const DaoAddresses: MessageFns<DaoAddresses> = {
  encode(message: DaoAddresses, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.globalDao !== '') {
      writer.uint32(10).string(message.globalDao)
    }
    if (message.meidDao !== '') {
      writer.uint32(18).string(message.meidDao)
    }
    if (message.devOperator !== '') {
      writer.uint32(26).string(message.devOperator)
    }
    if (message.airdropAddress !== '') {
      writer.uint32(34).string(message.airdropAddress)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoAddresses {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseDaoAddresses()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.globalDao = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.meidDao = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.devOperator = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.airdropAddress = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): DaoAddresses {
    return {
      globalDao: isSet(object.globalDao)
        ? globalThis.String(object.globalDao)
        : isSet(object.global_dao)
          ? globalThis.String(object.global_dao)
          : '',
      meidDao: isSet(object.meidDao)
        ? globalThis.String(object.meidDao)
        : isSet(object.meid_dao)
          ? globalThis.String(object.meid_dao)
          : '',
      devOperator: isSet(object.devOperator)
        ? globalThis.String(object.devOperator)
        : isSet(object.dev_operator)
          ? globalThis.String(object.dev_operator)
          : '',
      airdropAddress: isSet(object.airdropAddress)
        ? globalThis.String(object.airdropAddress)
        : isSet(object.airdrop_address)
          ? globalThis.String(object.airdrop_address)
          : '',
    }
  },

  toJSON(message: DaoAddresses): unknown {
    const obj: any = {}
    if (message.globalDao !== '') {
      obj.globalDao = message.globalDao
    }
    if (message.meidDao !== '') {
      obj.meidDao = message.meidDao
    }
    if (message.devOperator !== '') {
      obj.devOperator = message.devOperator
    }
    if (message.airdropAddress !== '') {
      obj.airdropAddress = message.airdropAddress
    }
    return obj
  },

  create<I extends Exact<DeepPartial<DaoAddresses>, I>>(base?: I): DaoAddresses {
    return DaoAddresses.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<DaoAddresses>, I>>(object: I): DaoAddresses {
    const message = createBaseDaoAddresses()
    message.globalDao = object.globalDao ?? ''
    message.meidDao = object.meidDao ?? ''
    message.devOperator = object.devOperator ?? ''
    message.airdropAddress = object.airdropAddress ?? ''
    return message
  },
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
