// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/wgov/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import { TallyResult } from '../../cosmos/gov/v1/gov'

export const protobufPackage = 'metaearth.wgov'

export interface QueryMeTallyResultRequest {
  proposalId: number
}

export interface QueryMeTallyResultResponse {
  tally: TallyResult | undefined
}

function createBaseQueryMeTallyResultRequest(): QueryMeTallyResultRequest {
  return { proposalId: 0 }
}

export const QueryMeTallyResultRequest: MessageFns<QueryMeTallyResultRequest> = {
  encode(
    message: QueryMeTallyResultRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.proposalId !== 0) {
      writer.uint32(8).uint64(message.proposalId)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryMeTallyResultRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryMeTallyResultRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.proposalId = longToNumber(reader.uint64())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryMeTallyResultRequest {
    return {
      proposalId: isSet(object.proposalId)
        ? globalThis.Number(object.proposalId)
        : isSet(object.proposal_id)
          ? globalThis.Number(object.proposal_id)
          : 0,
    }
  },

  toJSON(message: QueryMeTallyResultRequest): unknown {
    const obj: any = {}
    if (message.proposalId !== 0) {
      obj.proposalId = Math.round(message.proposalId)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryMeTallyResultRequest>, I>>(
    base?: I,
  ): QueryMeTallyResultRequest {
    return QueryMeTallyResultRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryMeTallyResultRequest>, I>>(
    object: I,
  ): QueryMeTallyResultRequest {
    const message = createBaseQueryMeTallyResultRequest()
    message.proposalId = object.proposalId ?? 0
    return message
  },
}

function createBaseQueryMeTallyResultResponse(): QueryMeTallyResultResponse {
  return { tally: undefined }
}

export const QueryMeTallyResultResponse: MessageFns<QueryMeTallyResultResponse> = {
  encode(
    message: QueryMeTallyResultResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.tally !== undefined) {
      TallyResult.encode(message.tally, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryMeTallyResultResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryMeTallyResultResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.tally = TallyResult.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryMeTallyResultResponse {
    return { tally: isSet(object.tally) ? TallyResult.fromJSON(object.tally) : undefined }
  },

  toJSON(message: QueryMeTallyResultResponse): unknown {
    const obj: any = {}
    if (message.tally !== undefined) {
      obj.tally = TallyResult.toJSON(message.tally)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryMeTallyResultResponse>, I>>(
    base?: I,
  ): QueryMeTallyResultResponse {
    return QueryMeTallyResultResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryMeTallyResultResponse>, I>>(
    object: I,
  ): QueryMeTallyResultResponse {
    const message = createBaseQueryMeTallyResultResponse()
    message.tally =
      object.tally !== undefined && object.tally !== null
        ? TallyResult.fromPartial(object.tally)
        : undefined
    return message
  },
}

export interface Query {
  MeTallyResult(request: QueryMeTallyResultRequest): Promise<QueryMeTallyResultResponse>
}

export const QueryServiceName = 'metaearth.wgov.Query'
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc
  private readonly service: string
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName
    this.rpc = rpc
    this.MeTallyResult = this.MeTallyResult.bind(this)
  }
  MeTallyResult(request: QueryMeTallyResultRequest): Promise<QueryMeTallyResultResponse> {
    const data = QueryMeTallyResultRequest.encode(request).finish()
    const promise = this.rpc.request(this.service, 'MeTallyResult', data)
    return promise.then((data) => QueryMeTallyResultResponse.decode(new BinaryReader(data)))
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString())
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER')
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER')
  }
  return num
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
