// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/gravity/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import { Coin } from '../../../cosmos/base/v1beta1/coin'
import { BridgeValidator, Params } from './types'

export const protobufPackage = 'metaearth.gravity.v1'

export interface MsgBondedRelayer {
  chainName: string
  relayerAddress: string
  externalAddress: string
  delegateAmount: Coin | undefined
}

export interface MsgBondedRelayerResponse {}

export interface MsgAddDelegate {
  chainName: string
  relayerAddress: string
  amount: Coin | undefined
}

export interface MsgAddDelegateResponse {}

export interface MsgUnbondedRelayer {
  chainName: string
  relayerAddress: string
}

export interface MsgUnbondedRelayerResponse {}

/**
 * MsgRelayerSetConfirm
 * this is the message sent by the validators when they wish to submit their
 * signatures over the validator set at a given block height. A validator must
 * first call MsgSetEthAddress to set their Ethereum address to be used for
 * signing. Then someone (anyone) must make a RelayerSetRequest, the request is
 * essentially a messaging mechanism to determine which block all validators
 * should submit signatures over. Finally validators sign the validator set,
 * powers, and Ethereum addresses of the entire validator set at the height of a
 * RelayerSetRequest and submit that signature with this message.
 *
 * If a sufficient number of validators (66% of voting power) (A) have set
 * Ethereum addresses and (B) submit RelayerSetConfirm messages with their
 * signatures it is then possible for anyone to view these signatures in the
 * chain store and submit them to Ethereum to update the validator set
 * -------------
 */
export interface MsgRelayerSetConfirm {
  nonce: number
  relayerAddress: string
  externalAddress: string
  signature: string
  chainName: string
}

export interface MsgRelayerSetConfirmResponse {}

/** This informs the Cosmos module that a relayer set has been updated. */
export interface MsgRelayerSetUpdateClaim {
  eventNonce: number
  blockHeight: number
  relayerSetNonce: number
  members: BridgeValidator[]
  relayerAddress: string
  chainName: string
}

export interface MsgRelayerSetUpdateClaimResponse {}

/**
 * MsgSendToMeClaim
 * When more than 66% of the active validator set has
 * claimed to have seen the deposit enter the bsc blockchain coins are
 * issued to the Payment address in question
 * -------------
 */
export interface MsgSendToMeClaim {
  eventNonce: number
  blockHeight: number
  tokenContract: string
  amount: string
  sender: string
  receiver: string
  relayerAddress: string
  chainName: string
}

export interface MsgSendToMeClaimResponse {}

/**
 * MsgSendToExternal
 * This is the message that a user calls when they want to bridge an asset
 * it will later be removed when it is included in a batch and successfully
 * submitted tokens are removed from the users balance immediately
 * -------------
 * AMOUNT:
 * the coin to send across the bridge, note the restriction that this is a
 * single coin not a set of coins that is normal in other Payment messages
 * FEE:
 * the fee paid for the bridge, distinct from the fee paid to the chain to
 * actually send this message in the first place. So a successful send has
 * two layers of fees for the user
 */
export interface MsgSendToExternal {
  sender: string
  dest: string
  amount: Coin | undefined
  bridgeFee: Coin | undefined
  chainName: string
}

export interface MsgSendToExternalResponse {
  outgoingTxId: number
}

/**
 * This call allows the sender (and only the sender)
 * to cancel a given MsgSendToExternal and recieve a refund
 * of the tokens
 */
export interface MsgCancelSendToExternal {
  transactionId: number
  sender: string
  chainName: string
}

export interface MsgCancelSendToExternalResponse {}

/**
 * MsgRequestBatch
 * this is a message anyone can send that requests a batch of transactions to
 * send across the bridge be created for whatever block height this message is
 * included in. This acts as a coordination point, the handler for this message
 * looks at the AddToOutgoingPool tx's in the store and generates a batch, also
 * available in the store tied to this message. The validators then grab this
 * batch, sign it, submit the signatures with a MsgConfirmBatch before a relayer
 * can finally submit the batch
 * -------------
 * feeReceive:
 */
export interface MsgRequestBatch {
  sender: string
  denom: string
  minimumFee: string
  feeReceive: string
  chainName: string
  baseFee: string
}

export interface MsgRequestBatchResponse {
  batchNonce: number
}

/**
 * MsgConfirmBatch
 * When validators observe a MsgRequestBatch they form a batch by ordering
 * transactions currently in the txqueue in order of highest to lowest fee,
 * cutting off when the batch either reaches a hardcoded maximum size (to be
 * decided, probably around 100) or when transactions stop being profitable
 * (determine this without nondeterminism) This message includes the batch
 * as well as an Bsc signature over this batch by the validator
 * -------------
 */
export interface MsgConfirmBatch {
  nonce: number
  tokenContract: string
  relayerAddress: string
  externalAddress: string
  signature: string
  chainName: string
}

export interface MsgConfirmBatchResponse {}

/**
 * SendToExternalClaim claims that a batch of withdrawal
 * operations on the bridge contract was executed.
 */
export interface MsgSendToExternalClaim {
  eventNonce: number
  blockHeight: number
  batchNonce: number
  tokenContract: string
  relayerAddress: string
  chainName: string
}

export interface MsgSendToExternalClaimResponse {}

export interface MsgBridgeTokenClaim {
  eventNonce: number
  blockHeight: number
  tokenContract: string
  name: string
  symbol: string
  decimals: number
  relayerAddress: string
  chainName: string
}

export interface MsgBridgeTokenClaimResponse {}

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  chainName: string
  /** authority is the address of the governance account. */
  authority: string
  /**
   * params defines the x/gravity parameters to update.
   *
   * NOTE: All parameters must be supplied.
   */
  params: Params | undefined
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {}

export interface MsgIncreaseBridgeFee {
  chainName: string
  transactionId: number
  sender: string
  addBridgeFee: Coin | undefined
}

export interface MsgIncreaseBridgeFeeResponse {}

export interface MsgProposalRelayers {
  chainName: string
  /** authority is the address of the governance account. */
  authority: string
  relayers: string[]
}

export interface MsgProposalRelayersResponse {}

function createBaseMsgBondedRelayer(): MsgBondedRelayer {
  return { chainName: '', relayerAddress: '', externalAddress: '', delegateAmount: undefined }
}

export const MsgBondedRelayer: MessageFns<MsgBondedRelayer> = {
  encode(message: MsgBondedRelayer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainName !== '') {
      writer.uint32(10).string(message.chainName)
    }
    if (message.relayerAddress !== '') {
      writer.uint32(18).string(message.relayerAddress)
    }
    if (message.externalAddress !== '') {
      writer.uint32(26).string(message.externalAddress)
    }
    if (message.delegateAmount !== undefined) {
      Coin.encode(message.delegateAmount, writer.uint32(34).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBondedRelayer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgBondedRelayer()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.chainName = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.relayerAddress = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.externalAddress = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.delegateAmount = Coin.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgBondedRelayer {
    return {
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
      relayerAddress: isSet(object.relayerAddress)
        ? globalThis.String(object.relayerAddress)
        : isSet(object.relayer_address)
          ? globalThis.String(object.relayer_address)
          : '',
      externalAddress: isSet(object.externalAddress)
        ? globalThis.String(object.externalAddress)
        : isSet(object.external_address)
          ? globalThis.String(object.external_address)
          : '',
      delegateAmount: isSet(object.delegateAmount)
        ? Coin.fromJSON(object.delegateAmount)
        : isSet(object.delegate_amount)
          ? Coin.fromJSON(object.delegate_amount)
          : undefined,
    }
  },

  toJSON(message: MsgBondedRelayer): unknown {
    const obj: any = {}
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    if (message.relayerAddress !== '') {
      obj.relayerAddress = message.relayerAddress
    }
    if (message.externalAddress !== '') {
      obj.externalAddress = message.externalAddress
    }
    if (message.delegateAmount !== undefined) {
      obj.delegateAmount = Coin.toJSON(message.delegateAmount)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgBondedRelayer>, I>>(base?: I): MsgBondedRelayer {
    return MsgBondedRelayer.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgBondedRelayer>, I>>(object: I): MsgBondedRelayer {
    const message = createBaseMsgBondedRelayer()
    message.chainName = object.chainName ?? ''
    message.relayerAddress = object.relayerAddress ?? ''
    message.externalAddress = object.externalAddress ?? ''
    message.delegateAmount =
      object.delegateAmount !== undefined && object.delegateAmount !== null
        ? Coin.fromPartial(object.delegateAmount)
        : undefined
    return message
  },
}

function createBaseMsgBondedRelayerResponse(): MsgBondedRelayerResponse {
  return {}
}

export const MsgBondedRelayerResponse: MessageFns<MsgBondedRelayerResponse> = {
  encode(_: MsgBondedRelayerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBondedRelayerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgBondedRelayerResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgBondedRelayerResponse {
    return {}
  },

  toJSON(_: MsgBondedRelayerResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgBondedRelayerResponse>, I>>(
    base?: I,
  ): MsgBondedRelayerResponse {
    return MsgBondedRelayerResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgBondedRelayerResponse>, I>>(
    _: I,
  ): MsgBondedRelayerResponse {
    const message = createBaseMsgBondedRelayerResponse()
    return message
  },
}

function createBaseMsgAddDelegate(): MsgAddDelegate {
  return { chainName: '', relayerAddress: '', amount: undefined }
}

export const MsgAddDelegate: MessageFns<MsgAddDelegate> = {
  encode(message: MsgAddDelegate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainName !== '') {
      writer.uint32(10).string(message.chainName)
    }
    if (message.relayerAddress !== '') {
      writer.uint32(18).string(message.relayerAddress)
    }
    if (message.amount !== undefined) {
      Coin.encode(message.amount, writer.uint32(26).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAddDelegate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgAddDelegate()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.chainName = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.relayerAddress = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.amount = Coin.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgAddDelegate {
    return {
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
      relayerAddress: isSet(object.relayerAddress)
        ? globalThis.String(object.relayerAddress)
        : isSet(object.relayer_address)
          ? globalThis.String(object.relayer_address)
          : '',
      amount: isSet(object.amount) ? Coin.fromJSON(object.amount) : undefined,
    }
  },

  toJSON(message: MsgAddDelegate): unknown {
    const obj: any = {}
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    if (message.relayerAddress !== '') {
      obj.relayerAddress = message.relayerAddress
    }
    if (message.amount !== undefined) {
      obj.amount = Coin.toJSON(message.amount)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgAddDelegate>, I>>(base?: I): MsgAddDelegate {
    return MsgAddDelegate.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddDelegate>, I>>(object: I): MsgAddDelegate {
    const message = createBaseMsgAddDelegate()
    message.chainName = object.chainName ?? ''
    message.relayerAddress = object.relayerAddress ?? ''
    message.amount =
      object.amount !== undefined && object.amount !== null
        ? Coin.fromPartial(object.amount)
        : undefined
    return message
  },
}

function createBaseMsgAddDelegateResponse(): MsgAddDelegateResponse {
  return {}
}

export const MsgAddDelegateResponse: MessageFns<MsgAddDelegateResponse> = {
  encode(_: MsgAddDelegateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAddDelegateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgAddDelegateResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgAddDelegateResponse {
    return {}
  },

  toJSON(_: MsgAddDelegateResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgAddDelegateResponse>, I>>(
    base?: I,
  ): MsgAddDelegateResponse {
    return MsgAddDelegateResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddDelegateResponse>, I>>(
    _: I,
  ): MsgAddDelegateResponse {
    const message = createBaseMsgAddDelegateResponse()
    return message
  },
}

function createBaseMsgUnbondedRelayer(): MsgUnbondedRelayer {
  return { chainName: '', relayerAddress: '' }
}

export const MsgUnbondedRelayer: MessageFns<MsgUnbondedRelayer> = {
  encode(message: MsgUnbondedRelayer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainName !== '') {
      writer.uint32(10).string(message.chainName)
    }
    if (message.relayerAddress !== '') {
      writer.uint32(18).string(message.relayerAddress)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUnbondedRelayer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgUnbondedRelayer()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.chainName = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.relayerAddress = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgUnbondedRelayer {
    return {
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
      relayerAddress: isSet(object.relayerAddress)
        ? globalThis.String(object.relayerAddress)
        : isSet(object.relayer_address)
          ? globalThis.String(object.relayer_address)
          : '',
    }
  },

  toJSON(message: MsgUnbondedRelayer): unknown {
    const obj: any = {}
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    if (message.relayerAddress !== '') {
      obj.relayerAddress = message.relayerAddress
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgUnbondedRelayer>, I>>(base?: I): MsgUnbondedRelayer {
    return MsgUnbondedRelayer.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgUnbondedRelayer>, I>>(object: I): MsgUnbondedRelayer {
    const message = createBaseMsgUnbondedRelayer()
    message.chainName = object.chainName ?? ''
    message.relayerAddress = object.relayerAddress ?? ''
    return message
  },
}

function createBaseMsgUnbondedRelayerResponse(): MsgUnbondedRelayerResponse {
  return {}
}

export const MsgUnbondedRelayerResponse: MessageFns<MsgUnbondedRelayerResponse> = {
  encode(_: MsgUnbondedRelayerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUnbondedRelayerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgUnbondedRelayerResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgUnbondedRelayerResponse {
    return {}
  },

  toJSON(_: MsgUnbondedRelayerResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgUnbondedRelayerResponse>, I>>(
    base?: I,
  ): MsgUnbondedRelayerResponse {
    return MsgUnbondedRelayerResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgUnbondedRelayerResponse>, I>>(
    _: I,
  ): MsgUnbondedRelayerResponse {
    const message = createBaseMsgUnbondedRelayerResponse()
    return message
  },
}

function createBaseMsgRelayerSetConfirm(): MsgRelayerSetConfirm {
  return { nonce: 0, relayerAddress: '', externalAddress: '', signature: '', chainName: '' }
}

export const MsgRelayerSetConfirm: MessageFns<MsgRelayerSetConfirm> = {
  encode(message: MsgRelayerSetConfirm, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nonce !== 0) {
      writer.uint32(8).uint64(message.nonce)
    }
    if (message.relayerAddress !== '') {
      writer.uint32(18).string(message.relayerAddress)
    }
    if (message.externalAddress !== '') {
      writer.uint32(26).string(message.externalAddress)
    }
    if (message.signature !== '') {
      writer.uint32(34).string(message.signature)
    }
    if (message.chainName !== '') {
      writer.uint32(42).string(message.chainName)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRelayerSetConfirm {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgRelayerSetConfirm()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.nonce = longToNumber(reader.uint64())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.relayerAddress = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.externalAddress = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.signature = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.chainName = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgRelayerSetConfirm {
    return {
      nonce: isSet(object.nonce) ? globalThis.Number(object.nonce) : 0,
      relayerAddress: isSet(object.relayerAddress)
        ? globalThis.String(object.relayerAddress)
        : isSet(object.relayer_address)
          ? globalThis.String(object.relayer_address)
          : '',
      externalAddress: isSet(object.externalAddress)
        ? globalThis.String(object.externalAddress)
        : isSet(object.external_address)
          ? globalThis.String(object.external_address)
          : '',
      signature: isSet(object.signature) ? globalThis.String(object.signature) : '',
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
    }
  },

  toJSON(message: MsgRelayerSetConfirm): unknown {
    const obj: any = {}
    if (message.nonce !== 0) {
      obj.nonce = Math.round(message.nonce)
    }
    if (message.relayerAddress !== '') {
      obj.relayerAddress = message.relayerAddress
    }
    if (message.externalAddress !== '') {
      obj.externalAddress = message.externalAddress
    }
    if (message.signature !== '') {
      obj.signature = message.signature
    }
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgRelayerSetConfirm>, I>>(base?: I): MsgRelayerSetConfirm {
    return MsgRelayerSetConfirm.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgRelayerSetConfirm>, I>>(
    object: I,
  ): MsgRelayerSetConfirm {
    const message = createBaseMsgRelayerSetConfirm()
    message.nonce = object.nonce ?? 0
    message.relayerAddress = object.relayerAddress ?? ''
    message.externalAddress = object.externalAddress ?? ''
    message.signature = object.signature ?? ''
    message.chainName = object.chainName ?? ''
    return message
  },
}

function createBaseMsgRelayerSetConfirmResponse(): MsgRelayerSetConfirmResponse {
  return {}
}

export const MsgRelayerSetConfirmResponse: MessageFns<MsgRelayerSetConfirmResponse> = {
  encode(_: MsgRelayerSetConfirmResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRelayerSetConfirmResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgRelayerSetConfirmResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgRelayerSetConfirmResponse {
    return {}
  },

  toJSON(_: MsgRelayerSetConfirmResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgRelayerSetConfirmResponse>, I>>(
    base?: I,
  ): MsgRelayerSetConfirmResponse {
    return MsgRelayerSetConfirmResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgRelayerSetConfirmResponse>, I>>(
    _: I,
  ): MsgRelayerSetConfirmResponse {
    const message = createBaseMsgRelayerSetConfirmResponse()
    return message
  },
}

function createBaseMsgRelayerSetUpdateClaim(): MsgRelayerSetUpdateClaim {
  return {
    eventNonce: 0,
    blockHeight: 0,
    relayerSetNonce: 0,
    members: [],
    relayerAddress: '',
    chainName: '',
  }
}

export const MsgRelayerSetUpdateClaim: MessageFns<MsgRelayerSetUpdateClaim> = {
  encode(
    message: MsgRelayerSetUpdateClaim,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.eventNonce !== 0) {
      writer.uint32(8).uint64(message.eventNonce)
    }
    if (message.blockHeight !== 0) {
      writer.uint32(16).uint64(message.blockHeight)
    }
    if (message.relayerSetNonce !== 0) {
      writer.uint32(24).uint64(message.relayerSetNonce)
    }
    for (const v of message.members) {
      BridgeValidator.encode(v!, writer.uint32(34).fork()).join()
    }
    if (message.relayerAddress !== '') {
      writer.uint32(50).string(message.relayerAddress)
    }
    if (message.chainName !== '') {
      writer.uint32(58).string(message.chainName)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRelayerSetUpdateClaim {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgRelayerSetUpdateClaim()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.eventNonce = longToNumber(reader.uint64())
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.blockHeight = longToNumber(reader.uint64())
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.relayerSetNonce = longToNumber(reader.uint64())
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.members.push(BridgeValidator.decode(reader, reader.uint32()))
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.relayerAddress = reader.string()
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.chainName = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgRelayerSetUpdateClaim {
    return {
      eventNonce: isSet(object.eventNonce)
        ? globalThis.Number(object.eventNonce)
        : isSet(object.event_nonce)
          ? globalThis.Number(object.event_nonce)
          : 0,
      blockHeight: isSet(object.blockHeight)
        ? globalThis.Number(object.blockHeight)
        : isSet(object.block_height)
          ? globalThis.Number(object.block_height)
          : 0,
      relayerSetNonce: isSet(object.relayerSetNonce)
        ? globalThis.Number(object.relayerSetNonce)
        : isSet(object.relayer_set_nonce)
          ? globalThis.Number(object.relayer_set_nonce)
          : 0,
      members: globalThis.Array.isArray(object?.members)
        ? object.members.map((e: any) => BridgeValidator.fromJSON(e))
        : [],
      relayerAddress: isSet(object.relayerAddress)
        ? globalThis.String(object.relayerAddress)
        : isSet(object.relayer_address)
          ? globalThis.String(object.relayer_address)
          : '',
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
    }
  },

  toJSON(message: MsgRelayerSetUpdateClaim): unknown {
    const obj: any = {}
    if (message.eventNonce !== 0) {
      obj.eventNonce = Math.round(message.eventNonce)
    }
    if (message.blockHeight !== 0) {
      obj.blockHeight = Math.round(message.blockHeight)
    }
    if (message.relayerSetNonce !== 0) {
      obj.relayerSetNonce = Math.round(message.relayerSetNonce)
    }
    if (message.members?.length) {
      obj.members = message.members.map((e) => BridgeValidator.toJSON(e))
    }
    if (message.relayerAddress !== '') {
      obj.relayerAddress = message.relayerAddress
    }
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgRelayerSetUpdateClaim>, I>>(
    base?: I,
  ): MsgRelayerSetUpdateClaim {
    return MsgRelayerSetUpdateClaim.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgRelayerSetUpdateClaim>, I>>(
    object: I,
  ): MsgRelayerSetUpdateClaim {
    const message = createBaseMsgRelayerSetUpdateClaim()
    message.eventNonce = object.eventNonce ?? 0
    message.blockHeight = object.blockHeight ?? 0
    message.relayerSetNonce = object.relayerSetNonce ?? 0
    message.members = object.members?.map((e) => BridgeValidator.fromPartial(e)) || []
    message.relayerAddress = object.relayerAddress ?? ''
    message.chainName = object.chainName ?? ''
    return message
  },
}

function createBaseMsgRelayerSetUpdateClaimResponse(): MsgRelayerSetUpdateClaimResponse {
  return {}
}

export const MsgRelayerSetUpdateClaimResponse: MessageFns<MsgRelayerSetUpdateClaimResponse> = {
  encode(
    _: MsgRelayerSetUpdateClaimResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRelayerSetUpdateClaimResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgRelayerSetUpdateClaimResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgRelayerSetUpdateClaimResponse {
    return {}
  },

  toJSON(_: MsgRelayerSetUpdateClaimResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgRelayerSetUpdateClaimResponse>, I>>(
    base?: I,
  ): MsgRelayerSetUpdateClaimResponse {
    return MsgRelayerSetUpdateClaimResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgRelayerSetUpdateClaimResponse>, I>>(
    _: I,
  ): MsgRelayerSetUpdateClaimResponse {
    const message = createBaseMsgRelayerSetUpdateClaimResponse()
    return message
  },
}

function createBaseMsgSendToMeClaim(): MsgSendToMeClaim {
  return {
    eventNonce: 0,
    blockHeight: 0,
    tokenContract: '',
    amount: '',
    sender: '',
    receiver: '',
    relayerAddress: '',
    chainName: '',
  }
}

export const MsgSendToMeClaim: MessageFns<MsgSendToMeClaim> = {
  encode(message: MsgSendToMeClaim, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventNonce !== 0) {
      writer.uint32(8).uint64(message.eventNonce)
    }
    if (message.blockHeight !== 0) {
      writer.uint32(16).uint64(message.blockHeight)
    }
    if (message.tokenContract !== '') {
      writer.uint32(26).string(message.tokenContract)
    }
    if (message.amount !== '') {
      writer.uint32(34).string(message.amount)
    }
    if (message.sender !== '') {
      writer.uint32(42).string(message.sender)
    }
    if (message.receiver !== '') {
      writer.uint32(50).string(message.receiver)
    }
    if (message.relayerAddress !== '') {
      writer.uint32(58).string(message.relayerAddress)
    }
    if (message.chainName !== '') {
      writer.uint32(66).string(message.chainName)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSendToMeClaim {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgSendToMeClaim()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.eventNonce = longToNumber(reader.uint64())
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.blockHeight = longToNumber(reader.uint64())
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.tokenContract = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.amount = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.sender = reader.string()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.receiver = reader.string()
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.relayerAddress = reader.string()
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.chainName = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgSendToMeClaim {
    return {
      eventNonce: isSet(object.eventNonce)
        ? globalThis.Number(object.eventNonce)
        : isSet(object.event_nonce)
          ? globalThis.Number(object.event_nonce)
          : 0,
      blockHeight: isSet(object.blockHeight)
        ? globalThis.Number(object.blockHeight)
        : isSet(object.block_height)
          ? globalThis.Number(object.block_height)
          : 0,
      tokenContract: isSet(object.tokenContract)
        ? globalThis.String(object.tokenContract)
        : isSet(object.token_contract)
          ? globalThis.String(object.token_contract)
          : '',
      amount: isSet(object.amount) ? globalThis.String(object.amount) : '',
      sender: isSet(object.sender) ? globalThis.String(object.sender) : '',
      receiver: isSet(object.receiver) ? globalThis.String(object.receiver) : '',
      relayerAddress: isSet(object.relayerAddress)
        ? globalThis.String(object.relayerAddress)
        : isSet(object.relayer_address)
          ? globalThis.String(object.relayer_address)
          : '',
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
    }
  },

  toJSON(message: MsgSendToMeClaim): unknown {
    const obj: any = {}
    if (message.eventNonce !== 0) {
      obj.eventNonce = Math.round(message.eventNonce)
    }
    if (message.blockHeight !== 0) {
      obj.blockHeight = Math.round(message.blockHeight)
    }
    if (message.tokenContract !== '') {
      obj.tokenContract = message.tokenContract
    }
    if (message.amount !== '') {
      obj.amount = message.amount
    }
    if (message.sender !== '') {
      obj.sender = message.sender
    }
    if (message.receiver !== '') {
      obj.receiver = message.receiver
    }
    if (message.relayerAddress !== '') {
      obj.relayerAddress = message.relayerAddress
    }
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgSendToMeClaim>, I>>(base?: I): MsgSendToMeClaim {
    return MsgSendToMeClaim.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgSendToMeClaim>, I>>(object: I): MsgSendToMeClaim {
    const message = createBaseMsgSendToMeClaim()
    message.eventNonce = object.eventNonce ?? 0
    message.blockHeight = object.blockHeight ?? 0
    message.tokenContract = object.tokenContract ?? ''
    message.amount = object.amount ?? ''
    message.sender = object.sender ?? ''
    message.receiver = object.receiver ?? ''
    message.relayerAddress = object.relayerAddress ?? ''
    message.chainName = object.chainName ?? ''
    return message
  },
}

function createBaseMsgSendToMeClaimResponse(): MsgSendToMeClaimResponse {
  return {}
}

export const MsgSendToMeClaimResponse: MessageFns<MsgSendToMeClaimResponse> = {
  encode(_: MsgSendToMeClaimResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSendToMeClaimResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgSendToMeClaimResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgSendToMeClaimResponse {
    return {}
  },

  toJSON(_: MsgSendToMeClaimResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgSendToMeClaimResponse>, I>>(
    base?: I,
  ): MsgSendToMeClaimResponse {
    return MsgSendToMeClaimResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgSendToMeClaimResponse>, I>>(
    _: I,
  ): MsgSendToMeClaimResponse {
    const message = createBaseMsgSendToMeClaimResponse()
    return message
  },
}

function createBaseMsgSendToExternal(): MsgSendToExternal {
  return { sender: '', dest: '', amount: undefined, bridgeFee: undefined, chainName: '' }
}

export const MsgSendToExternal: MessageFns<MsgSendToExternal> = {
  encode(message: MsgSendToExternal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sender !== '') {
      writer.uint32(10).string(message.sender)
    }
    if (message.dest !== '') {
      writer.uint32(18).string(message.dest)
    }
    if (message.amount !== undefined) {
      Coin.encode(message.amount, writer.uint32(26).fork()).join()
    }
    if (message.bridgeFee !== undefined) {
      Coin.encode(message.bridgeFee, writer.uint32(34).fork()).join()
    }
    if (message.chainName !== '') {
      writer.uint32(42).string(message.chainName)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSendToExternal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgSendToExternal()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.sender = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.dest = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.amount = Coin.decode(reader, reader.uint32())
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.bridgeFee = Coin.decode(reader, reader.uint32())
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.chainName = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgSendToExternal {
    return {
      sender: isSet(object.sender) ? globalThis.String(object.sender) : '',
      dest: isSet(object.dest) ? globalThis.String(object.dest) : '',
      amount: isSet(object.amount) ? Coin.fromJSON(object.amount) : undefined,
      bridgeFee: isSet(object.bridgeFee)
        ? Coin.fromJSON(object.bridgeFee)
        : isSet(object.bridge_fee)
          ? Coin.fromJSON(object.bridge_fee)
          : undefined,
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
    }
  },

  toJSON(message: MsgSendToExternal): unknown {
    const obj: any = {}
    if (message.sender !== '') {
      obj.sender = message.sender
    }
    if (message.dest !== '') {
      obj.dest = message.dest
    }
    if (message.amount !== undefined) {
      obj.amount = Coin.toJSON(message.amount)
    }
    if (message.bridgeFee !== undefined) {
      obj.bridgeFee = Coin.toJSON(message.bridgeFee)
    }
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgSendToExternal>, I>>(base?: I): MsgSendToExternal {
    return MsgSendToExternal.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgSendToExternal>, I>>(object: I): MsgSendToExternal {
    const message = createBaseMsgSendToExternal()
    message.sender = object.sender ?? ''
    message.dest = object.dest ?? ''
    message.amount =
      object.amount !== undefined && object.amount !== null
        ? Coin.fromPartial(object.amount)
        : undefined
    message.bridgeFee =
      object.bridgeFee !== undefined && object.bridgeFee !== null
        ? Coin.fromPartial(object.bridgeFee)
        : undefined
    message.chainName = object.chainName ?? ''
    return message
  },
}

function createBaseMsgSendToExternalResponse(): MsgSendToExternalResponse {
  return { outgoingTxId: 0 }
}

export const MsgSendToExternalResponse: MessageFns<MsgSendToExternalResponse> = {
  encode(
    message: MsgSendToExternalResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.outgoingTxId !== 0) {
      writer.uint32(8).uint64(message.outgoingTxId)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSendToExternalResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgSendToExternalResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.outgoingTxId = longToNumber(reader.uint64())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgSendToExternalResponse {
    return {
      outgoingTxId: isSet(object.outgoingTxId)
        ? globalThis.Number(object.outgoingTxId)
        : isSet(object.outgoing_tx_id)
          ? globalThis.Number(object.outgoing_tx_id)
          : 0,
    }
  },

  toJSON(message: MsgSendToExternalResponse): unknown {
    const obj: any = {}
    if (message.outgoingTxId !== 0) {
      obj.outgoingTxId = Math.round(message.outgoingTxId)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgSendToExternalResponse>, I>>(
    base?: I,
  ): MsgSendToExternalResponse {
    return MsgSendToExternalResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgSendToExternalResponse>, I>>(
    object: I,
  ): MsgSendToExternalResponse {
    const message = createBaseMsgSendToExternalResponse()
    message.outgoingTxId = object.outgoingTxId ?? 0
    return message
  },
}

function createBaseMsgCancelSendToExternal(): MsgCancelSendToExternal {
  return { transactionId: 0, sender: '', chainName: '' }
}

export const MsgCancelSendToExternal: MessageFns<MsgCancelSendToExternal> = {
  encode(
    message: MsgCancelSendToExternal,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.transactionId !== 0) {
      writer.uint32(8).uint64(message.transactionId)
    }
    if (message.sender !== '') {
      writer.uint32(18).string(message.sender)
    }
    if (message.chainName !== '') {
      writer.uint32(26).string(message.chainName)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCancelSendToExternal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgCancelSendToExternal()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.transactionId = longToNumber(reader.uint64())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.sender = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.chainName = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgCancelSendToExternal {
    return {
      transactionId: isSet(object.transactionId)
        ? globalThis.Number(object.transactionId)
        : isSet(object.transaction_id)
          ? globalThis.Number(object.transaction_id)
          : 0,
      sender: isSet(object.sender) ? globalThis.String(object.sender) : '',
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
    }
  },

  toJSON(message: MsgCancelSendToExternal): unknown {
    const obj: any = {}
    if (message.transactionId !== 0) {
      obj.transactionId = Math.round(message.transactionId)
    }
    if (message.sender !== '') {
      obj.sender = message.sender
    }
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgCancelSendToExternal>, I>>(
    base?: I,
  ): MsgCancelSendToExternal {
    return MsgCancelSendToExternal.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgCancelSendToExternal>, I>>(
    object: I,
  ): MsgCancelSendToExternal {
    const message = createBaseMsgCancelSendToExternal()
    message.transactionId = object.transactionId ?? 0
    message.sender = object.sender ?? ''
    message.chainName = object.chainName ?? ''
    return message
  },
}

function createBaseMsgCancelSendToExternalResponse(): MsgCancelSendToExternalResponse {
  return {}
}

export const MsgCancelSendToExternalResponse: MessageFns<MsgCancelSendToExternalResponse> = {
  encode(
    _: MsgCancelSendToExternalResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCancelSendToExternalResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgCancelSendToExternalResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgCancelSendToExternalResponse {
    return {}
  },

  toJSON(_: MsgCancelSendToExternalResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgCancelSendToExternalResponse>, I>>(
    base?: I,
  ): MsgCancelSendToExternalResponse {
    return MsgCancelSendToExternalResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgCancelSendToExternalResponse>, I>>(
    _: I,
  ): MsgCancelSendToExternalResponse {
    const message = createBaseMsgCancelSendToExternalResponse()
    return message
  },
}

function createBaseMsgRequestBatch(): MsgRequestBatch {
  return { sender: '', denom: '', minimumFee: '', feeReceive: '', chainName: '', baseFee: '' }
}

export const MsgRequestBatch: MessageFns<MsgRequestBatch> = {
  encode(message: MsgRequestBatch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sender !== '') {
      writer.uint32(10).string(message.sender)
    }
    if (message.denom !== '') {
      writer.uint32(18).string(message.denom)
    }
    if (message.minimumFee !== '') {
      writer.uint32(26).string(message.minimumFee)
    }
    if (message.feeReceive !== '') {
      writer.uint32(34).string(message.feeReceive)
    }
    if (message.chainName !== '') {
      writer.uint32(42).string(message.chainName)
    }
    if (message.baseFee !== '') {
      writer.uint32(50).string(message.baseFee)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRequestBatch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgRequestBatch()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.sender = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.denom = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.minimumFee = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.feeReceive = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.chainName = reader.string()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.baseFee = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgRequestBatch {
    return {
      sender: isSet(object.sender) ? globalThis.String(object.sender) : '',
      denom: isSet(object.denom) ? globalThis.String(object.denom) : '',
      minimumFee: isSet(object.minimumFee)
        ? globalThis.String(object.minimumFee)
        : isSet(object.minimum_fee)
          ? globalThis.String(object.minimum_fee)
          : '',
      feeReceive: isSet(object.feeReceive)
        ? globalThis.String(object.feeReceive)
        : isSet(object.fee_receive)
          ? globalThis.String(object.fee_receive)
          : '',
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
      baseFee: isSet(object.baseFee)
        ? globalThis.String(object.baseFee)
        : isSet(object.base_fee)
          ? globalThis.String(object.base_fee)
          : '',
    }
  },

  toJSON(message: MsgRequestBatch): unknown {
    const obj: any = {}
    if (message.sender !== '') {
      obj.sender = message.sender
    }
    if (message.denom !== '') {
      obj.denom = message.denom
    }
    if (message.minimumFee !== '') {
      obj.minimumFee = message.minimumFee
    }
    if (message.feeReceive !== '') {
      obj.feeReceive = message.feeReceive
    }
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    if (message.baseFee !== '') {
      obj.baseFee = message.baseFee
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgRequestBatch>, I>>(base?: I): MsgRequestBatch {
    return MsgRequestBatch.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgRequestBatch>, I>>(object: I): MsgRequestBatch {
    const message = createBaseMsgRequestBatch()
    message.sender = object.sender ?? ''
    message.denom = object.denom ?? ''
    message.minimumFee = object.minimumFee ?? ''
    message.feeReceive = object.feeReceive ?? ''
    message.chainName = object.chainName ?? ''
    message.baseFee = object.baseFee ?? ''
    return message
  },
}

function createBaseMsgRequestBatchResponse(): MsgRequestBatchResponse {
  return { batchNonce: 0 }
}

export const MsgRequestBatchResponse: MessageFns<MsgRequestBatchResponse> = {
  encode(
    message: MsgRequestBatchResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.batchNonce !== 0) {
      writer.uint32(8).uint64(message.batchNonce)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRequestBatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgRequestBatchResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.batchNonce = longToNumber(reader.uint64())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgRequestBatchResponse {
    return {
      batchNonce: isSet(object.batchNonce)
        ? globalThis.Number(object.batchNonce)
        : isSet(object.batch_nonce)
          ? globalThis.Number(object.batch_nonce)
          : 0,
    }
  },

  toJSON(message: MsgRequestBatchResponse): unknown {
    const obj: any = {}
    if (message.batchNonce !== 0) {
      obj.batchNonce = Math.round(message.batchNonce)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgRequestBatchResponse>, I>>(
    base?: I,
  ): MsgRequestBatchResponse {
    return MsgRequestBatchResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgRequestBatchResponse>, I>>(
    object: I,
  ): MsgRequestBatchResponse {
    const message = createBaseMsgRequestBatchResponse()
    message.batchNonce = object.batchNonce ?? 0
    return message
  },
}

function createBaseMsgConfirmBatch(): MsgConfirmBatch {
  return {
    nonce: 0,
    tokenContract: '',
    relayerAddress: '',
    externalAddress: '',
    signature: '',
    chainName: '',
  }
}

export const MsgConfirmBatch: MessageFns<MsgConfirmBatch> = {
  encode(message: MsgConfirmBatch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nonce !== 0) {
      writer.uint32(8).uint64(message.nonce)
    }
    if (message.tokenContract !== '') {
      writer.uint32(18).string(message.tokenContract)
    }
    if (message.relayerAddress !== '') {
      writer.uint32(26).string(message.relayerAddress)
    }
    if (message.externalAddress !== '') {
      writer.uint32(34).string(message.externalAddress)
    }
    if (message.signature !== '') {
      writer.uint32(42).string(message.signature)
    }
    if (message.chainName !== '') {
      writer.uint32(50).string(message.chainName)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgConfirmBatch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgConfirmBatch()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.nonce = longToNumber(reader.uint64())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.tokenContract = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.relayerAddress = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.externalAddress = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.signature = reader.string()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.chainName = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgConfirmBatch {
    return {
      nonce: isSet(object.nonce) ? globalThis.Number(object.nonce) : 0,
      tokenContract: isSet(object.tokenContract)
        ? globalThis.String(object.tokenContract)
        : isSet(object.token_contract)
          ? globalThis.String(object.token_contract)
          : '',
      relayerAddress: isSet(object.relayerAddress)
        ? globalThis.String(object.relayerAddress)
        : isSet(object.relayer_address)
          ? globalThis.String(object.relayer_address)
          : '',
      externalAddress: isSet(object.externalAddress)
        ? globalThis.String(object.externalAddress)
        : isSet(object.external_address)
          ? globalThis.String(object.external_address)
          : '',
      signature: isSet(object.signature) ? globalThis.String(object.signature) : '',
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
    }
  },

  toJSON(message: MsgConfirmBatch): unknown {
    const obj: any = {}
    if (message.nonce !== 0) {
      obj.nonce = Math.round(message.nonce)
    }
    if (message.tokenContract !== '') {
      obj.tokenContract = message.tokenContract
    }
    if (message.relayerAddress !== '') {
      obj.relayerAddress = message.relayerAddress
    }
    if (message.externalAddress !== '') {
      obj.externalAddress = message.externalAddress
    }
    if (message.signature !== '') {
      obj.signature = message.signature
    }
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgConfirmBatch>, I>>(base?: I): MsgConfirmBatch {
    return MsgConfirmBatch.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgConfirmBatch>, I>>(object: I): MsgConfirmBatch {
    const message = createBaseMsgConfirmBatch()
    message.nonce = object.nonce ?? 0
    message.tokenContract = object.tokenContract ?? ''
    message.relayerAddress = object.relayerAddress ?? ''
    message.externalAddress = object.externalAddress ?? ''
    message.signature = object.signature ?? ''
    message.chainName = object.chainName ?? ''
    return message
  },
}

function createBaseMsgConfirmBatchResponse(): MsgConfirmBatchResponse {
  return {}
}

export const MsgConfirmBatchResponse: MessageFns<MsgConfirmBatchResponse> = {
  encode(_: MsgConfirmBatchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgConfirmBatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgConfirmBatchResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgConfirmBatchResponse {
    return {}
  },

  toJSON(_: MsgConfirmBatchResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgConfirmBatchResponse>, I>>(
    base?: I,
  ): MsgConfirmBatchResponse {
    return MsgConfirmBatchResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgConfirmBatchResponse>, I>>(
    _: I,
  ): MsgConfirmBatchResponse {
    const message = createBaseMsgConfirmBatchResponse()
    return message
  },
}

function createBaseMsgSendToExternalClaim(): MsgSendToExternalClaim {
  return {
    eventNonce: 0,
    blockHeight: 0,
    batchNonce: 0,
    tokenContract: '',
    relayerAddress: '',
    chainName: '',
  }
}

export const MsgSendToExternalClaim: MessageFns<MsgSendToExternalClaim> = {
  encode(message: MsgSendToExternalClaim, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventNonce !== 0) {
      writer.uint32(8).uint64(message.eventNonce)
    }
    if (message.blockHeight !== 0) {
      writer.uint32(16).uint64(message.blockHeight)
    }
    if (message.batchNonce !== 0) {
      writer.uint32(24).uint64(message.batchNonce)
    }
    if (message.tokenContract !== '') {
      writer.uint32(34).string(message.tokenContract)
    }
    if (message.relayerAddress !== '') {
      writer.uint32(42).string(message.relayerAddress)
    }
    if (message.chainName !== '') {
      writer.uint32(50).string(message.chainName)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSendToExternalClaim {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgSendToExternalClaim()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.eventNonce = longToNumber(reader.uint64())
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.blockHeight = longToNumber(reader.uint64())
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.batchNonce = longToNumber(reader.uint64())
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.tokenContract = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.relayerAddress = reader.string()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.chainName = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgSendToExternalClaim {
    return {
      eventNonce: isSet(object.eventNonce)
        ? globalThis.Number(object.eventNonce)
        : isSet(object.event_nonce)
          ? globalThis.Number(object.event_nonce)
          : 0,
      blockHeight: isSet(object.blockHeight)
        ? globalThis.Number(object.blockHeight)
        : isSet(object.block_height)
          ? globalThis.Number(object.block_height)
          : 0,
      batchNonce: isSet(object.batchNonce)
        ? globalThis.Number(object.batchNonce)
        : isSet(object.batch_nonce)
          ? globalThis.Number(object.batch_nonce)
          : 0,
      tokenContract: isSet(object.tokenContract)
        ? globalThis.String(object.tokenContract)
        : isSet(object.token_contract)
          ? globalThis.String(object.token_contract)
          : '',
      relayerAddress: isSet(object.relayerAddress)
        ? globalThis.String(object.relayerAddress)
        : isSet(object.relayer_address)
          ? globalThis.String(object.relayer_address)
          : '',
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
    }
  },

  toJSON(message: MsgSendToExternalClaim): unknown {
    const obj: any = {}
    if (message.eventNonce !== 0) {
      obj.eventNonce = Math.round(message.eventNonce)
    }
    if (message.blockHeight !== 0) {
      obj.blockHeight = Math.round(message.blockHeight)
    }
    if (message.batchNonce !== 0) {
      obj.batchNonce = Math.round(message.batchNonce)
    }
    if (message.tokenContract !== '') {
      obj.tokenContract = message.tokenContract
    }
    if (message.relayerAddress !== '') {
      obj.relayerAddress = message.relayerAddress
    }
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgSendToExternalClaim>, I>>(
    base?: I,
  ): MsgSendToExternalClaim {
    return MsgSendToExternalClaim.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgSendToExternalClaim>, I>>(
    object: I,
  ): MsgSendToExternalClaim {
    const message = createBaseMsgSendToExternalClaim()
    message.eventNonce = object.eventNonce ?? 0
    message.blockHeight = object.blockHeight ?? 0
    message.batchNonce = object.batchNonce ?? 0
    message.tokenContract = object.tokenContract ?? ''
    message.relayerAddress = object.relayerAddress ?? ''
    message.chainName = object.chainName ?? ''
    return message
  },
}

function createBaseMsgSendToExternalClaimResponse(): MsgSendToExternalClaimResponse {
  return {}
}

export const MsgSendToExternalClaimResponse: MessageFns<MsgSendToExternalClaimResponse> = {
  encode(
    _: MsgSendToExternalClaimResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSendToExternalClaimResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgSendToExternalClaimResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgSendToExternalClaimResponse {
    return {}
  },

  toJSON(_: MsgSendToExternalClaimResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgSendToExternalClaimResponse>, I>>(
    base?: I,
  ): MsgSendToExternalClaimResponse {
    return MsgSendToExternalClaimResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgSendToExternalClaimResponse>, I>>(
    _: I,
  ): MsgSendToExternalClaimResponse {
    const message = createBaseMsgSendToExternalClaimResponse()
    return message
  },
}

function createBaseMsgBridgeTokenClaim(): MsgBridgeTokenClaim {
  return {
    eventNonce: 0,
    blockHeight: 0,
    tokenContract: '',
    name: '',
    symbol: '',
    decimals: 0,
    relayerAddress: '',
    chainName: '',
  }
}

export const MsgBridgeTokenClaim: MessageFns<MsgBridgeTokenClaim> = {
  encode(message: MsgBridgeTokenClaim, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventNonce !== 0) {
      writer.uint32(8).uint64(message.eventNonce)
    }
    if (message.blockHeight !== 0) {
      writer.uint32(16).uint64(message.blockHeight)
    }
    if (message.tokenContract !== '') {
      writer.uint32(26).string(message.tokenContract)
    }
    if (message.name !== '') {
      writer.uint32(34).string(message.name)
    }
    if (message.symbol !== '') {
      writer.uint32(42).string(message.symbol)
    }
    if (message.decimals !== 0) {
      writer.uint32(48).uint64(message.decimals)
    }
    if (message.relayerAddress !== '') {
      writer.uint32(58).string(message.relayerAddress)
    }
    if (message.chainName !== '') {
      writer.uint32(66).string(message.chainName)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBridgeTokenClaim {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgBridgeTokenClaim()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.eventNonce = longToNumber(reader.uint64())
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.blockHeight = longToNumber(reader.uint64())
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.tokenContract = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.name = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.symbol = reader.string()
          continue
        }
        case 6: {
          if (tag !== 48) {
            break
          }

          message.decimals = longToNumber(reader.uint64())
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.relayerAddress = reader.string()
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.chainName = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgBridgeTokenClaim {
    return {
      eventNonce: isSet(object.eventNonce)
        ? globalThis.Number(object.eventNonce)
        : isSet(object.event_nonce)
          ? globalThis.Number(object.event_nonce)
          : 0,
      blockHeight: isSet(object.blockHeight)
        ? globalThis.Number(object.blockHeight)
        : isSet(object.block_height)
          ? globalThis.Number(object.block_height)
          : 0,
      tokenContract: isSet(object.tokenContract)
        ? globalThis.String(object.tokenContract)
        : isSet(object.token_contract)
          ? globalThis.String(object.token_contract)
          : '',
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : '',
      decimals: isSet(object.decimals) ? globalThis.Number(object.decimals) : 0,
      relayerAddress: isSet(object.relayerAddress)
        ? globalThis.String(object.relayerAddress)
        : isSet(object.relayer_address)
          ? globalThis.String(object.relayer_address)
          : '',
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
    }
  },

  toJSON(message: MsgBridgeTokenClaim): unknown {
    const obj: any = {}
    if (message.eventNonce !== 0) {
      obj.eventNonce = Math.round(message.eventNonce)
    }
    if (message.blockHeight !== 0) {
      obj.blockHeight = Math.round(message.blockHeight)
    }
    if (message.tokenContract !== '') {
      obj.tokenContract = message.tokenContract
    }
    if (message.name !== '') {
      obj.name = message.name
    }
    if (message.symbol !== '') {
      obj.symbol = message.symbol
    }
    if (message.decimals !== 0) {
      obj.decimals = Math.round(message.decimals)
    }
    if (message.relayerAddress !== '') {
      obj.relayerAddress = message.relayerAddress
    }
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgBridgeTokenClaim>, I>>(base?: I): MsgBridgeTokenClaim {
    return MsgBridgeTokenClaim.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgBridgeTokenClaim>, I>>(
    object: I,
  ): MsgBridgeTokenClaim {
    const message = createBaseMsgBridgeTokenClaim()
    message.eventNonce = object.eventNonce ?? 0
    message.blockHeight = object.blockHeight ?? 0
    message.tokenContract = object.tokenContract ?? ''
    message.name = object.name ?? ''
    message.symbol = object.symbol ?? ''
    message.decimals = object.decimals ?? 0
    message.relayerAddress = object.relayerAddress ?? ''
    message.chainName = object.chainName ?? ''
    return message
  },
}

function createBaseMsgBridgeTokenClaimResponse(): MsgBridgeTokenClaimResponse {
  return {}
}

export const MsgBridgeTokenClaimResponse: MessageFns<MsgBridgeTokenClaimResponse> = {
  encode(_: MsgBridgeTokenClaimResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBridgeTokenClaimResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgBridgeTokenClaimResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgBridgeTokenClaimResponse {
    return {}
  },

  toJSON(_: MsgBridgeTokenClaimResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgBridgeTokenClaimResponse>, I>>(
    base?: I,
  ): MsgBridgeTokenClaimResponse {
    return MsgBridgeTokenClaimResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgBridgeTokenClaimResponse>, I>>(
    _: I,
  ): MsgBridgeTokenClaimResponse {
    const message = createBaseMsgBridgeTokenClaimResponse()
    return message
  },
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { chainName: '', authority: '', params: undefined }
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainName !== '') {
      writer.uint32(10).string(message.chainName)
    }
    if (message.authority !== '') {
      writer.uint32(18).string(message.authority)
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(26).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgUpdateParams()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.chainName = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.authority = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.params = Params.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
      authority: isSet(object.authority) ? globalThis.String(object.authority) : '',
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    }
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {}
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    if (message.authority !== '') {
      obj.authority = message.authority
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams()
    message.chainName = object.chainName ?? ''
    message.authority = object.authority ?? ''
    message.params =
      object.params !== undefined && object.params !== null
        ? Params.fromPartial(object.params)
        : undefined
    return message
  },
}

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {}
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgUpdateParamsResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {}
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(
    base?: I,
  ): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(
    _: I,
  ): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse()
    return message
  },
}

function createBaseMsgIncreaseBridgeFee(): MsgIncreaseBridgeFee {
  return { chainName: '', transactionId: 0, sender: '', addBridgeFee: undefined }
}

export const MsgIncreaseBridgeFee: MessageFns<MsgIncreaseBridgeFee> = {
  encode(message: MsgIncreaseBridgeFee, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainName !== '') {
      writer.uint32(10).string(message.chainName)
    }
    if (message.transactionId !== 0) {
      writer.uint32(16).uint64(message.transactionId)
    }
    if (message.sender !== '') {
      writer.uint32(26).string(message.sender)
    }
    if (message.addBridgeFee !== undefined) {
      Coin.encode(message.addBridgeFee, writer.uint32(34).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgIncreaseBridgeFee {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgIncreaseBridgeFee()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.chainName = reader.string()
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.transactionId = longToNumber(reader.uint64())
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.sender = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.addBridgeFee = Coin.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgIncreaseBridgeFee {
    return {
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
      transactionId: isSet(object.transactionId)
        ? globalThis.Number(object.transactionId)
        : isSet(object.transaction_id)
          ? globalThis.Number(object.transaction_id)
          : 0,
      sender: isSet(object.sender) ? globalThis.String(object.sender) : '',
      addBridgeFee: isSet(object.addBridgeFee)
        ? Coin.fromJSON(object.addBridgeFee)
        : isSet(object.add_bridge_fee)
          ? Coin.fromJSON(object.add_bridge_fee)
          : undefined,
    }
  },

  toJSON(message: MsgIncreaseBridgeFee): unknown {
    const obj: any = {}
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    if (message.transactionId !== 0) {
      obj.transactionId = Math.round(message.transactionId)
    }
    if (message.sender !== '') {
      obj.sender = message.sender
    }
    if (message.addBridgeFee !== undefined) {
      obj.addBridgeFee = Coin.toJSON(message.addBridgeFee)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgIncreaseBridgeFee>, I>>(base?: I): MsgIncreaseBridgeFee {
    return MsgIncreaseBridgeFee.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgIncreaseBridgeFee>, I>>(
    object: I,
  ): MsgIncreaseBridgeFee {
    const message = createBaseMsgIncreaseBridgeFee()
    message.chainName = object.chainName ?? ''
    message.transactionId = object.transactionId ?? 0
    message.sender = object.sender ?? ''
    message.addBridgeFee =
      object.addBridgeFee !== undefined && object.addBridgeFee !== null
        ? Coin.fromPartial(object.addBridgeFee)
        : undefined
    return message
  },
}

function createBaseMsgIncreaseBridgeFeeResponse(): MsgIncreaseBridgeFeeResponse {
  return {}
}

export const MsgIncreaseBridgeFeeResponse: MessageFns<MsgIncreaseBridgeFeeResponse> = {
  encode(_: MsgIncreaseBridgeFeeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgIncreaseBridgeFeeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgIncreaseBridgeFeeResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgIncreaseBridgeFeeResponse {
    return {}
  },

  toJSON(_: MsgIncreaseBridgeFeeResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgIncreaseBridgeFeeResponse>, I>>(
    base?: I,
  ): MsgIncreaseBridgeFeeResponse {
    return MsgIncreaseBridgeFeeResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgIncreaseBridgeFeeResponse>, I>>(
    _: I,
  ): MsgIncreaseBridgeFeeResponse {
    const message = createBaseMsgIncreaseBridgeFeeResponse()
    return message
  },
}

function createBaseMsgProposalRelayers(): MsgProposalRelayers {
  return { chainName: '', authority: '', relayers: [] }
}

export const MsgProposalRelayers: MessageFns<MsgProposalRelayers> = {
  encode(message: MsgProposalRelayers, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainName !== '') {
      writer.uint32(10).string(message.chainName)
    }
    if (message.authority !== '') {
      writer.uint32(18).string(message.authority)
    }
    for (const v of message.relayers) {
      writer.uint32(26).string(v!)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgProposalRelayers {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgProposalRelayers()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.chainName = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.authority = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.relayers.push(reader.string())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgProposalRelayers {
    return {
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
          ? globalThis.String(object.chain_name)
          : '',
      authority: isSet(object.authority) ? globalThis.String(object.authority) : '',
      relayers: globalThis.Array.isArray(object?.relayers)
        ? object.relayers.map((e: any) => globalThis.String(e))
        : [],
    }
  },

  toJSON(message: MsgProposalRelayers): unknown {
    const obj: any = {}
    if (message.chainName !== '') {
      obj.chainName = message.chainName
    }
    if (message.authority !== '') {
      obj.authority = message.authority
    }
    if (message.relayers?.length) {
      obj.relayers = message.relayers
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgProposalRelayers>, I>>(base?: I): MsgProposalRelayers {
    return MsgProposalRelayers.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgProposalRelayers>, I>>(
    object: I,
  ): MsgProposalRelayers {
    const message = createBaseMsgProposalRelayers()
    message.chainName = object.chainName ?? ''
    message.authority = object.authority ?? ''
    message.relayers = object.relayers?.map((e) => e) || []
    return message
  },
}

function createBaseMsgProposalRelayersResponse(): MsgProposalRelayersResponse {
  return {}
}

export const MsgProposalRelayersResponse: MessageFns<MsgProposalRelayersResponse> = {
  encode(_: MsgProposalRelayersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgProposalRelayersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgProposalRelayersResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgProposalRelayersResponse {
    return {}
  },

  toJSON(_: MsgProposalRelayersResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgProposalRelayersResponse>, I>>(
    base?: I,
  ): MsgProposalRelayersResponse {
    return MsgProposalRelayersResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgProposalRelayersResponse>, I>>(
    _: I,
  ): MsgProposalRelayersResponse {
    const message = createBaseMsgProposalRelayersResponse()
    return message
  },
}

/** Msg defines the state transitions possible within gravity */
export interface Msg {
  BondedRelayer(request: MsgBondedRelayer): Promise<MsgBondedRelayerResponse>
  AddDelegate(request: MsgAddDelegate): Promise<MsgAddDelegateResponse>
  UnbondedRelayer(request: MsgUnbondedRelayer): Promise<MsgUnbondedRelayerResponse>
  RelayerSetConfirm(request: MsgRelayerSetConfirm): Promise<MsgRelayerSetConfirmResponse>
  RelayerSetUpdateClaim(
    request: MsgRelayerSetUpdateClaim,
  ): Promise<MsgRelayerSetUpdateClaimResponse>
  SendToMeClaim(request: MsgSendToMeClaim): Promise<MsgSendToMeClaimResponse>
  BridgeTokenClaim(request: MsgBridgeTokenClaim): Promise<MsgBridgeTokenClaimResponse>
  SendToExternal(request: MsgSendToExternal): Promise<MsgSendToExternalResponse>
  CancelSendToExternal(request: MsgCancelSendToExternal): Promise<MsgCancelSendToExternalResponse>
  SendToExternalClaim(request: MsgSendToExternalClaim): Promise<MsgSendToExternalClaimResponse>
  RequestBatch(request: MsgRequestBatch): Promise<MsgRequestBatchResponse>
  ConfirmBatch(request: MsgConfirmBatch): Promise<MsgConfirmBatchResponse>
  /**
   * UpdateParams defines a governance operation for updating the x/gravity
   * module parameters. The authority is hard-coded to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>
  IncreaseBridgeFee(request: MsgIncreaseBridgeFee): Promise<MsgIncreaseBridgeFeeResponse>
  ProposalRelayers(request: MsgProposalRelayers): Promise<MsgProposalRelayersResponse>
}

export const MsgServiceName = 'metaearth.gravity.v1.Msg'
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc
  private readonly service: string
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName
    this.rpc = rpc
    this.BondedRelayer = this.BondedRelayer.bind(this)
    this.AddDelegate = this.AddDelegate.bind(this)
    this.UnbondedRelayer = this.UnbondedRelayer.bind(this)
    this.RelayerSetConfirm = this.RelayerSetConfirm.bind(this)
    this.RelayerSetUpdateClaim = this.RelayerSetUpdateClaim.bind(this)
    this.SendToMeClaim = this.SendToMeClaim.bind(this)
    this.BridgeTokenClaim = this.BridgeTokenClaim.bind(this)
    this.SendToExternal = this.SendToExternal.bind(this)
    this.CancelSendToExternal = this.CancelSendToExternal.bind(this)
    this.SendToExternalClaim = this.SendToExternalClaim.bind(this)
    this.RequestBatch = this.RequestBatch.bind(this)
    this.ConfirmBatch = this.ConfirmBatch.bind(this)
    this.UpdateParams = this.UpdateParams.bind(this)
    this.IncreaseBridgeFee = this.IncreaseBridgeFee.bind(this)
    this.ProposalRelayers = this.ProposalRelayers.bind(this)
  }
  BondedRelayer(request: MsgBondedRelayer): Promise<MsgBondedRelayerResponse> {
    const data = MsgBondedRelayer.encode(request).finish()
    const promise = this.rpc.request(this.service, 'BondedRelayer', data)
    return promise.then((data) => MsgBondedRelayerResponse.decode(new BinaryReader(data)))
  }

  AddDelegate(request: MsgAddDelegate): Promise<MsgAddDelegateResponse> {
    const data = MsgAddDelegate.encode(request).finish()
    const promise = this.rpc.request(this.service, 'AddDelegate', data)
    return promise.then((data) => MsgAddDelegateResponse.decode(new BinaryReader(data)))
  }

  UnbondedRelayer(request: MsgUnbondedRelayer): Promise<MsgUnbondedRelayerResponse> {
    const data = MsgUnbondedRelayer.encode(request).finish()
    const promise = this.rpc.request(this.service, 'UnbondedRelayer', data)
    return promise.then((data) => MsgUnbondedRelayerResponse.decode(new BinaryReader(data)))
  }

  RelayerSetConfirm(request: MsgRelayerSetConfirm): Promise<MsgRelayerSetConfirmResponse> {
    const data = MsgRelayerSetConfirm.encode(request).finish()
    const promise = this.rpc.request(this.service, 'RelayerSetConfirm', data)
    return promise.then((data) => MsgRelayerSetConfirmResponse.decode(new BinaryReader(data)))
  }

  RelayerSetUpdateClaim(
    request: MsgRelayerSetUpdateClaim,
  ): Promise<MsgRelayerSetUpdateClaimResponse> {
    const data = MsgRelayerSetUpdateClaim.encode(request).finish()
    const promise = this.rpc.request(this.service, 'RelayerSetUpdateClaim', data)
    return promise.then((data) => MsgRelayerSetUpdateClaimResponse.decode(new BinaryReader(data)))
  }

  SendToMeClaim(request: MsgSendToMeClaim): Promise<MsgSendToMeClaimResponse> {
    const data = MsgSendToMeClaim.encode(request).finish()
    const promise = this.rpc.request(this.service, 'SendToMeClaim', data)
    return promise.then((data) => MsgSendToMeClaimResponse.decode(new BinaryReader(data)))
  }

  BridgeTokenClaim(request: MsgBridgeTokenClaim): Promise<MsgBridgeTokenClaimResponse> {
    const data = MsgBridgeTokenClaim.encode(request).finish()
    const promise = this.rpc.request(this.service, 'BridgeTokenClaim', data)
    return promise.then((data) => MsgBridgeTokenClaimResponse.decode(new BinaryReader(data)))
  }

  SendToExternal(request: MsgSendToExternal): Promise<MsgSendToExternalResponse> {
    const data = MsgSendToExternal.encode(request).finish()
    const promise = this.rpc.request(this.service, 'SendToExternal', data)
    return promise.then((data) => MsgSendToExternalResponse.decode(new BinaryReader(data)))
  }

  CancelSendToExternal(request: MsgCancelSendToExternal): Promise<MsgCancelSendToExternalResponse> {
    const data = MsgCancelSendToExternal.encode(request).finish()
    const promise = this.rpc.request(this.service, 'CancelSendToExternal', data)
    return promise.then((data) => MsgCancelSendToExternalResponse.decode(new BinaryReader(data)))
  }

  SendToExternalClaim(request: MsgSendToExternalClaim): Promise<MsgSendToExternalClaimResponse> {
    const data = MsgSendToExternalClaim.encode(request).finish()
    const promise = this.rpc.request(this.service, 'SendToExternalClaim', data)
    return promise.then((data) => MsgSendToExternalClaimResponse.decode(new BinaryReader(data)))
  }

  RequestBatch(request: MsgRequestBatch): Promise<MsgRequestBatchResponse> {
    const data = MsgRequestBatch.encode(request).finish()
    const promise = this.rpc.request(this.service, 'RequestBatch', data)
    return promise.then((data) => MsgRequestBatchResponse.decode(new BinaryReader(data)))
  }

  ConfirmBatch(request: MsgConfirmBatch): Promise<MsgConfirmBatchResponse> {
    const data = MsgConfirmBatch.encode(request).finish()
    const promise = this.rpc.request(this.service, 'ConfirmBatch', data)
    return promise.then((data) => MsgConfirmBatchResponse.decode(new BinaryReader(data)))
  }

  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish()
    const promise = this.rpc.request(this.service, 'UpdateParams', data)
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)))
  }

  IncreaseBridgeFee(request: MsgIncreaseBridgeFee): Promise<MsgIncreaseBridgeFeeResponse> {
    const data = MsgIncreaseBridgeFee.encode(request).finish()
    const promise = this.rpc.request(this.service, 'IncreaseBridgeFee', data)
    return promise.then((data) => MsgIncreaseBridgeFeeResponse.decode(new BinaryReader(data)))
  }

  ProposalRelayers(request: MsgProposalRelayers): Promise<MsgProposalRelayersResponse> {
    const data = MsgProposalRelayers.encode(request).finish()
    const promise = this.rpc.request(this.service, 'ProposalRelayers', data)
    return promise.then((data) => MsgProposalRelayersResponse.decode(new BinaryReader(data)))
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString())
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER')
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER')
  }
  return num
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
