// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/eibc/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import {
  RollappPacket_Type,
  rollappPacket_TypeFromJSON,
  rollappPacket_TypeToJSON,
} from '../common/rollapp_packet'
import { Status, statusFromJSON, statusToJSON } from '../common/status'
import { DemandOrder } from './demand_order'
import { Params } from './params'

export const protobufPackage = 'metaearth.eibc'

export enum FulfillmentState {
  UNDEFINED = 0,
  FULFILLED = 1,
  UNFULFILLED = 2,
  UNRECOGNIZED = -1,
}

export function fulfillmentStateFromJSON(object: any): FulfillmentState {
  switch (object) {
    case 0:
    case 'UNDEFINED':
      return FulfillmentState.UNDEFINED
    case 1:
    case 'FULFILLED':
      return FulfillmentState.FULFILLED
    case 2:
    case 'UNFULFILLED':
      return FulfillmentState.UNFULFILLED
    case -1:
    case 'UNRECOGNIZED':
    default:
      return FulfillmentState.UNRECOGNIZED
  }
}

export function fulfillmentStateToJSON(object: FulfillmentState): string {
  switch (object) {
    case FulfillmentState.UNDEFINED:
      return 'UNDEFINED'
    case FulfillmentState.FULFILLED:
      return 'FULFILLED'
    case FulfillmentState.UNFULFILLED:
      return 'UNFULFILLED'
    case FulfillmentState.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined
}

/**
 * QueryGetDemandOrderRequest is the request type for the Query/GetDemandOrder
 * RPC method.
 */
export interface QueryGetDemandOrderRequest {
  /** id of the demand order to get */
  id: string
}

/**
 * QueryDemandOrdersByStatusRequest is the request type for the
 * Query/GetDemandOrdersByStatus RPC method.
 */
export interface QueryDemandOrdersByStatusRequest {
  /** status of the demand order */
  status: Status
  /** optional type */
  type: RollappPacket_Type
  /** optional rollapp_id */
  rollappId: string
  /** optional limit */
  limit: number
  /** optional fulfillment state */
  fulfillmentState: FulfillmentState
  /** optional fulfiller address */
  fulfiller: string
  /** optional denom */
  denom: string
  /** optional recipient address */
  recipient: string
}

/**
 * QueryGetDemandOrderResponse is the response type for the Query/GetDemandOrder
 * RPC method.
 */
export interface QueryGetDemandOrderResponse {
  /** demand order with the given id */
  demandOrder: DemandOrder | undefined
}

/**
 * QueryDemandOrdersByStatusResponse is the response type for the
 * Query/GetDemandOrdersByStatus RPC method.
 */
export interface QueryDemandOrdersByStatusResponse {
  /** A list of demand orders with the given status */
  demandOrders: DemandOrder[]
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {}
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryParamsRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): QueryParamsRequest {
    return {}
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest()
    return message
  },
}

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined }
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryParamsResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.params = Params.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined }
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {}
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(
    object: I,
  ): QueryParamsResponse {
    const message = createBaseQueryParamsResponse()
    message.params =
      object.params !== undefined && object.params !== null
        ? Params.fromPartial(object.params)
        : undefined
    return message
  },
}

function createBaseQueryGetDemandOrderRequest(): QueryGetDemandOrderRequest {
  return { id: '' }
}

export const QueryGetDemandOrderRequest: MessageFns<QueryGetDemandOrderRequest> = {
  encode(
    message: QueryGetDemandOrderRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetDemandOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryGetDemandOrderRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.id = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryGetDemandOrderRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : '' }
  },

  toJSON(message: QueryGetDemandOrderRequest): unknown {
    const obj: any = {}
    if (message.id !== '') {
      obj.id = message.id
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryGetDemandOrderRequest>, I>>(
    base?: I,
  ): QueryGetDemandOrderRequest {
    return QueryGetDemandOrderRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetDemandOrderRequest>, I>>(
    object: I,
  ): QueryGetDemandOrderRequest {
    const message = createBaseQueryGetDemandOrderRequest()
    message.id = object.id ?? ''
    return message
  },
}

function createBaseQueryDemandOrdersByStatusRequest(): QueryDemandOrdersByStatusRequest {
  return {
    status: 0,
    type: 0,
    rollappId: '',
    limit: 0,
    fulfillmentState: 0,
    fulfiller: '',
    denom: '',
    recipient: '',
  }
}

export const QueryDemandOrdersByStatusRequest: MessageFns<QueryDemandOrdersByStatusRequest> = {
  encode(
    message: QueryDemandOrdersByStatusRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status)
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type)
    }
    if (message.rollappId !== '') {
      writer.uint32(26).string(message.rollappId)
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit)
    }
    if (message.fulfillmentState !== 0) {
      writer.uint32(40).int32(message.fulfillmentState)
    }
    if (message.fulfiller !== '') {
      writer.uint32(50).string(message.fulfiller)
    }
    if (message.denom !== '') {
      writer.uint32(58).string(message.denom)
    }
    if (message.recipient !== '') {
      writer.uint32(66).string(message.recipient)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDemandOrdersByStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryDemandOrdersByStatusRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.status = reader.int32() as any
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.type = reader.int32() as any
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.rollappId = reader.string()
          continue
        }
        case 4: {
          if (tag !== 32) {
            break
          }

          message.limit = reader.int32()
          continue
        }
        case 5: {
          if (tag !== 40) {
            break
          }

          message.fulfillmentState = reader.int32() as any
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.fulfiller = reader.string()
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.denom = reader.string()
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.recipient = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryDemandOrdersByStatusRequest {
    return {
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      type: isSet(object.type) ? rollappPacket_TypeFromJSON(object.type) : 0,
      rollappId: isSet(object.rollappId)
        ? globalThis.String(object.rollappId)
        : isSet(object.rollapp_id)
          ? globalThis.String(object.rollapp_id)
          : '',
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      fulfillmentState: isSet(object.fulfillmentState)
        ? fulfillmentStateFromJSON(object.fulfillmentState)
        : isSet(object.fulfillment_state)
          ? fulfillmentStateFromJSON(object.fulfillment_state)
          : 0,
      fulfiller: isSet(object.fulfiller) ? globalThis.String(object.fulfiller) : '',
      denom: isSet(object.denom) ? globalThis.String(object.denom) : '',
      recipient: isSet(object.recipient) ? globalThis.String(object.recipient) : '',
    }
  },

  toJSON(message: QueryDemandOrdersByStatusRequest): unknown {
    const obj: any = {}
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status)
    }
    if (message.type !== 0) {
      obj.type = rollappPacket_TypeToJSON(message.type)
    }
    if (message.rollappId !== '') {
      obj.rollappId = message.rollappId
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit)
    }
    if (message.fulfillmentState !== 0) {
      obj.fulfillmentState = fulfillmentStateToJSON(message.fulfillmentState)
    }
    if (message.fulfiller !== '') {
      obj.fulfiller = message.fulfiller
    }
    if (message.denom !== '') {
      obj.denom = message.denom
    }
    if (message.recipient !== '') {
      obj.recipient = message.recipient
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryDemandOrdersByStatusRequest>, I>>(
    base?: I,
  ): QueryDemandOrdersByStatusRequest {
    return QueryDemandOrdersByStatusRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryDemandOrdersByStatusRequest>, I>>(
    object: I,
  ): QueryDemandOrdersByStatusRequest {
    const message = createBaseQueryDemandOrdersByStatusRequest()
    message.status = object.status ?? 0
    message.type = object.type ?? 0
    message.rollappId = object.rollappId ?? ''
    message.limit = object.limit ?? 0
    message.fulfillmentState = object.fulfillmentState ?? 0
    message.fulfiller = object.fulfiller ?? ''
    message.denom = object.denom ?? ''
    message.recipient = object.recipient ?? ''
    return message
  },
}

function createBaseQueryGetDemandOrderResponse(): QueryGetDemandOrderResponse {
  return { demandOrder: undefined }
}

export const QueryGetDemandOrderResponse: MessageFns<QueryGetDemandOrderResponse> = {
  encode(
    message: QueryGetDemandOrderResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.demandOrder !== undefined) {
      DemandOrder.encode(message.demandOrder, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetDemandOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryGetDemandOrderResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.demandOrder = DemandOrder.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryGetDemandOrderResponse {
    return {
      demandOrder: isSet(object.demandOrder)
        ? DemandOrder.fromJSON(object.demandOrder)
        : isSet(object.demand_order)
          ? DemandOrder.fromJSON(object.demand_order)
          : undefined,
    }
  },

  toJSON(message: QueryGetDemandOrderResponse): unknown {
    const obj: any = {}
    if (message.demandOrder !== undefined) {
      obj.demandOrder = DemandOrder.toJSON(message.demandOrder)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryGetDemandOrderResponse>, I>>(
    base?: I,
  ): QueryGetDemandOrderResponse {
    return QueryGetDemandOrderResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetDemandOrderResponse>, I>>(
    object: I,
  ): QueryGetDemandOrderResponse {
    const message = createBaseQueryGetDemandOrderResponse()
    message.demandOrder =
      object.demandOrder !== undefined && object.demandOrder !== null
        ? DemandOrder.fromPartial(object.demandOrder)
        : undefined
    return message
  },
}

function createBaseQueryDemandOrdersByStatusResponse(): QueryDemandOrdersByStatusResponse {
  return { demandOrders: [] }
}

export const QueryDemandOrdersByStatusResponse: MessageFns<QueryDemandOrdersByStatusResponse> = {
  encode(
    message: QueryDemandOrdersByStatusResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.demandOrders) {
      DemandOrder.encode(v!, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDemandOrdersByStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryDemandOrdersByStatusResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.demandOrders.push(DemandOrder.decode(reader, reader.uint32()))
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryDemandOrdersByStatusResponse {
    return {
      demandOrders: globalThis.Array.isArray(object?.demandOrders)
        ? object.demandOrders.map((e: any) => DemandOrder.fromJSON(e))
        : globalThis.Array.isArray(object?.demand_orders)
          ? object.demand_orders.map((e: any) => DemandOrder.fromJSON(e))
          : [],
    }
  },

  toJSON(message: QueryDemandOrdersByStatusResponse): unknown {
    const obj: any = {}
    if (message.demandOrders?.length) {
      obj.demandOrders = message.demandOrders.map((e) => DemandOrder.toJSON(e))
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryDemandOrdersByStatusResponse>, I>>(
    base?: I,
  ): QueryDemandOrdersByStatusResponse {
    return QueryDemandOrdersByStatusResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryDemandOrdersByStatusResponse>, I>>(
    object: I,
  ): QueryDemandOrdersByStatusResponse {
    const message = createBaseQueryDemandOrdersByStatusResponse()
    message.demandOrders = object.demandOrders?.map((e) => DemandOrder.fromPartial(e)) || []
    return message
  },
}

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>
  /** Queries a Demand Order by id. */
  DemandOrderById(request: QueryGetDemandOrderRequest): Promise<QueryGetDemandOrderResponse>
  /** Queries a list of demand orders by status. */
  DemandOrdersByStatus(
    request: QueryDemandOrdersByStatusRequest,
  ): Promise<QueryDemandOrdersByStatusResponse>
}

export const QueryServiceName = 'metaearth.eibc.Query'
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc
  private readonly service: string
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName
    this.rpc = rpc
    this.Params = this.Params.bind(this)
    this.DemandOrderById = this.DemandOrderById.bind(this)
    this.DemandOrdersByStatus = this.DemandOrdersByStatus.bind(this)
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish()
    const promise = this.rpc.request(this.service, 'Params', data)
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)))
  }

  DemandOrderById(request: QueryGetDemandOrderRequest): Promise<QueryGetDemandOrderResponse> {
    const data = QueryGetDemandOrderRequest.encode(request).finish()
    const promise = this.rpc.request(this.service, 'DemandOrderById', data)
    return promise.then((data) => QueryGetDemandOrderResponse.decode(new BinaryReader(data)))
  }

  DemandOrdersByStatus(
    request: QueryDemandOrdersByStatusRequest,
  ): Promise<QueryDemandOrdersByStatusResponse> {
    const data = QueryDemandOrdersByStatusRequest.encode(request).finish()
    const promise = this.rpc.request(this.service, 'DemandOrdersByStatus', data)
    return promise.then((data) => QueryDemandOrdersByStatusResponse.decode(new BinaryReader(data)))
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
