// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/wnft/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import { PageRequest, PageResponse } from '../../cosmos/base/query/v1beta1/pagination'

export const protobufPackage = 'metaearth.wnft'

/** QueryClassRequest is the request type for the Query/Class RPC method */
export interface QueryClassAddressRequest {
  /** class_id associated with the nft */
  classId: string
  address: string
  pagination: PageRequest | undefined
}

/** QueryClassesResponse is the response type for the Query/Classes RPC method */
export interface QueryClassAddressResponse {
  exists: boolean
  totalSupply: number
  nfts: string[]
  pagination: PageResponse | undefined
}

/** QueryNftFilterResponse is the request type for the Query/NftFilter RPC method */
export interface QueryNftFilterRequest {
  owner: string
  classId: string
  tokenId: string
  pagination: PageRequest | undefined
}

/**
 * QueryNftFilterResponse is the response type for the Query/NftFilter RPC
 * method
 */
export interface QueryNftFilterResponse {
  nfts: NftList[]
  pagination: PageResponse | undefined
}

export interface NftList {
  classId: string
  tokenId: string
  uri: string
  owner: string
}

function createBaseQueryClassAddressRequest(): QueryClassAddressRequest {
  return { classId: '', address: '', pagination: undefined }
}

export const QueryClassAddressRequest: MessageFns<QueryClassAddressRequest> = {
  encode(
    message: QueryClassAddressRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.classId !== '') {
      writer.uint32(10).string(message.classId)
    }
    if (message.address !== '') {
      writer.uint32(18).string(message.address)
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(26).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryClassAddressRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryClassAddressRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.classId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.address = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.pagination = PageRequest.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryClassAddressRequest {
    return {
      classId: isSet(object.classId)
        ? globalThis.String(object.classId)
        : isSet(object.class_id)
          ? globalThis.String(object.class_id)
          : '',
      address: isSet(object.address) ? globalThis.String(object.address) : '',
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryClassAddressRequest): unknown {
    const obj: any = {}
    if (message.classId !== '') {
      obj.classId = message.classId
    }
    if (message.address !== '') {
      obj.address = message.address
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryClassAddressRequest>, I>>(
    base?: I,
  ): QueryClassAddressRequest {
    return QueryClassAddressRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryClassAddressRequest>, I>>(
    object: I,
  ): QueryClassAddressRequest {
    const message = createBaseQueryClassAddressRequest()
    message.classId = object.classId ?? ''
    message.address = object.address ?? ''
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageRequest.fromPartial(object.pagination)
        : undefined
    return message
  },
}

function createBaseQueryClassAddressResponse(): QueryClassAddressResponse {
  return { exists: false, totalSupply: 0, nfts: [], pagination: undefined }
}

export const QueryClassAddressResponse: MessageFns<QueryClassAddressResponse> = {
  encode(
    message: QueryClassAddressResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.exists !== false) {
      writer.uint32(8).bool(message.exists)
    }
    if (message.totalSupply !== 0) {
      writer.uint32(16).uint64(message.totalSupply)
    }
    for (const v of message.nfts) {
      writer.uint32(26).string(v!)
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(34).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryClassAddressResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryClassAddressResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.exists = reader.bool()
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.totalSupply = longToNumber(reader.uint64())
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.nfts.push(reader.string())
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.pagination = PageResponse.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryClassAddressResponse {
    return {
      exists: isSet(object.exists) ? globalThis.Boolean(object.exists) : false,
      totalSupply: isSet(object.totalSupply)
        ? globalThis.Number(object.totalSupply)
        : isSet(object.total_supply)
          ? globalThis.Number(object.total_supply)
          : 0,
      nfts: globalThis.Array.isArray(object?.nfts)
        ? object.nfts.map((e: any) => globalThis.String(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryClassAddressResponse): unknown {
    const obj: any = {}
    if (message.exists !== false) {
      obj.exists = message.exists
    }
    if (message.totalSupply !== 0) {
      obj.totalSupply = Math.round(message.totalSupply)
    }
    if (message.nfts?.length) {
      obj.nfts = message.nfts
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryClassAddressResponse>, I>>(
    base?: I,
  ): QueryClassAddressResponse {
    return QueryClassAddressResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryClassAddressResponse>, I>>(
    object: I,
  ): QueryClassAddressResponse {
    const message = createBaseQueryClassAddressResponse()
    message.exists = object.exists ?? false
    message.totalSupply = object.totalSupply ?? 0
    message.nfts = object.nfts?.map((e) => e) || []
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageResponse.fromPartial(object.pagination)
        : undefined
    return message
  },
}

function createBaseQueryNftFilterRequest(): QueryNftFilterRequest {
  return { owner: '', classId: '', tokenId: '', pagination: undefined }
}

export const QueryNftFilterRequest: MessageFns<QueryNftFilterRequest> = {
  encode(message: QueryNftFilterRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.owner !== '') {
      writer.uint32(10).string(message.owner)
    }
    if (message.classId !== '') {
      writer.uint32(18).string(message.classId)
    }
    if (message.tokenId !== '') {
      writer.uint32(26).string(message.tokenId)
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(34).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryNftFilterRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryNftFilterRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.owner = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.classId = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.tokenId = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.pagination = PageRequest.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryNftFilterRequest {
    return {
      owner: isSet(object.owner) ? globalThis.String(object.owner) : '',
      classId: isSet(object.classId)
        ? globalThis.String(object.classId)
        : isSet(object.class_id)
          ? globalThis.String(object.class_id)
          : '',
      tokenId: isSet(object.tokenId)
        ? globalThis.String(object.tokenId)
        : isSet(object.token_id)
          ? globalThis.String(object.token_id)
          : '',
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryNftFilterRequest): unknown {
    const obj: any = {}
    if (message.owner !== '') {
      obj.owner = message.owner
    }
    if (message.classId !== '') {
      obj.classId = message.classId
    }
    if (message.tokenId !== '') {
      obj.tokenId = message.tokenId
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryNftFilterRequest>, I>>(base?: I): QueryNftFilterRequest {
    return QueryNftFilterRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryNftFilterRequest>, I>>(
    object: I,
  ): QueryNftFilterRequest {
    const message = createBaseQueryNftFilterRequest()
    message.owner = object.owner ?? ''
    message.classId = object.classId ?? ''
    message.tokenId = object.tokenId ?? ''
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageRequest.fromPartial(object.pagination)
        : undefined
    return message
  },
}

function createBaseQueryNftFilterResponse(): QueryNftFilterResponse {
  return { nfts: [], pagination: undefined }
}

export const QueryNftFilterResponse: MessageFns<QueryNftFilterResponse> = {
  encode(message: QueryNftFilterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.nfts) {
      NftList.encode(v!, writer.uint32(10).fork()).join()
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryNftFilterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryNftFilterResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.nfts.push(NftList.decode(reader, reader.uint32()))
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.pagination = PageResponse.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryNftFilterResponse {
    return {
      nfts: globalThis.Array.isArray(object?.nfts)
        ? object.nfts.map((e: any) => NftList.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryNftFilterResponse): unknown {
    const obj: any = {}
    if (message.nfts?.length) {
      obj.nfts = message.nfts.map((e) => NftList.toJSON(e))
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryNftFilterResponse>, I>>(
    base?: I,
  ): QueryNftFilterResponse {
    return QueryNftFilterResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryNftFilterResponse>, I>>(
    object: I,
  ): QueryNftFilterResponse {
    const message = createBaseQueryNftFilterResponse()
    message.nfts = object.nfts?.map((e) => NftList.fromPartial(e)) || []
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageResponse.fromPartial(object.pagination)
        : undefined
    return message
  },
}

function createBaseNftList(): NftList {
  return { classId: '', tokenId: '', uri: '', owner: '' }
}

export const NftList: MessageFns<NftList> = {
  encode(message: NftList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.classId !== '') {
      writer.uint32(10).string(message.classId)
    }
    if (message.tokenId !== '') {
      writer.uint32(18).string(message.tokenId)
    }
    if (message.uri !== '') {
      writer.uint32(26).string(message.uri)
    }
    if (message.owner !== '') {
      writer.uint32(34).string(message.owner)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NftList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseNftList()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.classId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.tokenId = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.uri = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.owner = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): NftList {
    return {
      classId: isSet(object.classId)
        ? globalThis.String(object.classId)
        : isSet(object.class_id)
          ? globalThis.String(object.class_id)
          : '',
      tokenId: isSet(object.tokenId)
        ? globalThis.String(object.tokenId)
        : isSet(object.token_id)
          ? globalThis.String(object.token_id)
          : '',
      uri: isSet(object.uri) ? globalThis.String(object.uri) : '',
      owner: isSet(object.owner) ? globalThis.String(object.owner) : '',
    }
  },

  toJSON(message: NftList): unknown {
    const obj: any = {}
    if (message.classId !== '') {
      obj.classId = message.classId
    }
    if (message.tokenId !== '') {
      obj.tokenId = message.tokenId
    }
    if (message.uri !== '') {
      obj.uri = message.uri
    }
    if (message.owner !== '') {
      obj.owner = message.owner
    }
    return obj
  },

  create<I extends Exact<DeepPartial<NftList>, I>>(base?: I): NftList {
    return NftList.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<NftList>, I>>(object: I): NftList {
    const message = createBaseNftList()
    message.classId = object.classId ?? ''
    message.tokenId = object.tokenId ?? ''
    message.uri = object.uri ?? ''
    message.owner = object.owner ?? ''
    return message
  },
}

/** Query defines the gRPC querier service. */
export interface Query {
  /** Classes queries Address */
  ClassAddress(request: QueryClassAddressRequest): Promise<QueryClassAddressResponse>
  /** queries nft filter */
  NftFilter(request: QueryNftFilterRequest): Promise<QueryNftFilterResponse>
}

export const QueryServiceName = 'metaearth.wnft.Query'
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc
  private readonly service: string
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName
    this.rpc = rpc
    this.ClassAddress = this.ClassAddress.bind(this)
    this.NftFilter = this.NftFilter.bind(this)
  }
  ClassAddress(request: QueryClassAddressRequest): Promise<QueryClassAddressResponse> {
    const data = QueryClassAddressRequest.encode(request).finish()
    const promise = this.rpc.request(this.service, 'ClassAddress', data)
    return promise.then((data) => QueryClassAddressResponse.decode(new BinaryReader(data)))
  }

  NftFilter(request: QueryNftFilterRequest): Promise<QueryNftFilterResponse> {
    const data = QueryNftFilterRequest.encode(request).finish()
    const promise = this.rpc.request(this.service, 'NftFilter', data)
    return promise.then((data) => QueryNftFilterResponse.decode(new BinaryReader(data)))
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString())
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER')
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER')
  }
  return num
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
