// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/sequencer/description.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'

export const protobufPackage = 'metaearth.sequencer'

/** Description defines a sequencer description. */
export interface Description {
  /** moniker defines a human-readable name for the sequencer. */
  moniker: string
  /** identity defines an optional identity signature (ex. UPort or Keybase). */
  identity: string
  /** website defines an optional website link. */
  website: string
  /** securityContact defines an optional email for security contact. */
  securityContact: string
  /** details define other optional details. */
  details: string
}

function createBaseDescription(): Description {
  return { moniker: '', identity: '', website: '', securityContact: '', details: '' }
}

export const Description: MessageFns<Description> = {
  encode(message: Description, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.moniker !== '') {
      writer.uint32(10).string(message.moniker)
    }
    if (message.identity !== '') {
      writer.uint32(18).string(message.identity)
    }
    if (message.website !== '') {
      writer.uint32(26).string(message.website)
    }
    if (message.securityContact !== '') {
      writer.uint32(34).string(message.securityContact)
    }
    if (message.details !== '') {
      writer.uint32(42).string(message.details)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Description {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseDescription()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.moniker = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.identity = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.website = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.securityContact = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.details = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): Description {
    return {
      moniker: isSet(object.moniker) ? globalThis.String(object.moniker) : '',
      identity: isSet(object.identity) ? globalThis.String(object.identity) : '',
      website: isSet(object.website) ? globalThis.String(object.website) : '',
      securityContact: isSet(object.securityContact)
        ? globalThis.String(object.securityContact)
        : '',
      details: isSet(object.details) ? globalThis.String(object.details) : '',
    }
  },

  toJSON(message: Description): unknown {
    const obj: any = {}
    if (message.moniker !== '') {
      obj.moniker = message.moniker
    }
    if (message.identity !== '') {
      obj.identity = message.identity
    }
    if (message.website !== '') {
      obj.website = message.website
    }
    if (message.securityContact !== '') {
      obj.securityContact = message.securityContact
    }
    if (message.details !== '') {
      obj.details = message.details
    }
    return obj
  },

  create<I extends Exact<DeepPartial<Description>, I>>(base?: I): Description {
    return Description.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<Description>, I>>(object: I): Description {
    const message = createBaseDescription()
    message.moniker = object.moniker ?? ''
    message.identity = object.identity ?? ''
    message.website = object.website ?? ''
    message.securityContact = object.securityContact ?? ''
    message.details = object.details ?? ''
    return message
  },
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
