// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/rollapp/rollapp.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import { StateInfoIndex } from './state_info'

export const protobufPackage = 'metaearth.rollapp'

/**
 * RollappGenesisState is a partial repr of the state the hub can expect the
 * rollapp to be in upon genesis
 */
export interface RollappGenesisState {
  /**
   * If true, then full usage of the canonical ibc transfer channel is enabled.
   * Note: in v3.1.0 and prior this field marked the completion of the 'genesis
   * event' Keeping and renaming the field enables a seamless upgrade
   * https://www.notion.so/dymension/ADR-x-Genesis-Bridge-Phase-2-89769aa551b5440b9ed403a101775ce1?pvs=4#89698384d815435b87393dbe45bc5a74
   * to the new genesis transfer protocol
   * Note: if this field is false, ibc transfers may still be allowed in one or
   * either direction.
   */
  transfersEnabled: boolean
}

/**
 * Rollapp defines a rollapp object. First the RollApp is created and then
 * sequencers can be created and attached. The RollApp is identified by
 * rollappId
 */
export interface Rollapp {
  /**
   * The unique identifier of the rollapp chain.
   * The rollappId follows the same standard as cosmos chain_id.
   */
  rollappId: string
  /** creator is the bech32-encoded address of the rollapp creator. */
  creator: string
  /**
   * version is the software and configuration version.
   * starts from 1 and increases by one on every MsgUpdateState
   */
  version: number
  /** maxSequencers is the maximum number of sequencers. */
  maxSequencers: number
  /**
   * permissionedAddresses is a bech32-encoded address list of the sequencers
   * that are allowed to serve this rollappId. In the case of an empty list, the
   * rollapp is considered permissionless.
   */
  permissionedAddresses: string[]
  /**
   * genesis_state is a partial repr of the state the hub can expect the rollapp
   * to be in upon genesis
   */
  genesisState: RollappGenesisState | undefined
  /** channel_id will be set to the canonical IBC channel of the rollapp. */
  channelId: string
  /** frozen is a boolean that indicates if the rollapp is frozen. */
  frozen: boolean
  /** registeredDenoms is a list of registered denom bases on this rollapp */
  registeredDenoms: string[]
}

/** Rollapp summary is a compact representation of Rollapp */
export interface RollappSummary {
  /**
   * The unique identifier of the rollapp chain.
   * The rollappId follows the same standard as cosmos chain_id.
   */
  rollappId: string
  /** Defines the index of the last rollapp UpdateState. */
  latestStateIndex: StateInfoIndex | undefined
  /** Defines the index of the last rollapp UpdateState that was finalized. */
  latestFinalizedStateIndex: StateInfoIndex | undefined
}

function createBaseRollappGenesisState(): RollappGenesisState {
  return { transfersEnabled: false }
}

export const RollappGenesisState: MessageFns<RollappGenesisState> = {
  encode(message: RollappGenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transfersEnabled !== false) {
      writer.uint32(16).bool(message.transfersEnabled)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RollappGenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRollappGenesisState()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 16) {
            break
          }

          message.transfersEnabled = reader.bool()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): RollappGenesisState {
    return {
      transfersEnabled: isSet(object.transfersEnabled)
        ? globalThis.Boolean(object.transfersEnabled)
        : isSet(object.transfers_enabled)
          ? globalThis.Boolean(object.transfers_enabled)
          : false,
    }
  },

  toJSON(message: RollappGenesisState): unknown {
    const obj: any = {}
    if (message.transfersEnabled !== false) {
      obj.transfersEnabled = message.transfersEnabled
    }
    return obj
  },

  create<I extends Exact<DeepPartial<RollappGenesisState>, I>>(base?: I): RollappGenesisState {
    return RollappGenesisState.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RollappGenesisState>, I>>(
    object: I,
  ): RollappGenesisState {
    const message = createBaseRollappGenesisState()
    message.transfersEnabled = object.transfersEnabled ?? false
    return message
  },
}

function createBaseRollapp(): Rollapp {
  return {
    rollappId: '',
    creator: '',
    version: 0,
    maxSequencers: 0,
    permissionedAddresses: [],
    genesisState: undefined,
    channelId: '',
    frozen: false,
    registeredDenoms: [],
  }
}

export const Rollapp: MessageFns<Rollapp> = {
  encode(message: Rollapp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rollappId !== '') {
      writer.uint32(10).string(message.rollappId)
    }
    if (message.creator !== '') {
      writer.uint32(18).string(message.creator)
    }
    if (message.version !== 0) {
      writer.uint32(24).uint64(message.version)
    }
    if (message.maxSequencers !== 0) {
      writer.uint32(32).uint64(message.maxSequencers)
    }
    for (const v of message.permissionedAddresses) {
      writer.uint32(42).string(v!)
    }
    if (message.genesisState !== undefined) {
      RollappGenesisState.encode(message.genesisState, writer.uint32(58).fork()).join()
    }
    if (message.channelId !== '') {
      writer.uint32(66).string(message.channelId)
    }
    if (message.frozen !== false) {
      writer.uint32(72).bool(message.frozen)
    }
    for (const v of message.registeredDenoms) {
      writer.uint32(82).string(v!)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Rollapp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRollapp()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.rollappId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.creator = reader.string()
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.version = longToNumber(reader.uint64())
          continue
        }
        case 4: {
          if (tag !== 32) {
            break
          }

          message.maxSequencers = longToNumber(reader.uint64())
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.permissionedAddresses.push(reader.string())
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.genesisState = RollappGenesisState.decode(reader, reader.uint32())
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.channelId = reader.string()
          continue
        }
        case 9: {
          if (tag !== 72) {
            break
          }

          message.frozen = reader.bool()
          continue
        }
        case 10: {
          if (tag !== 82) {
            break
          }

          message.registeredDenoms.push(reader.string())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): Rollapp {
    return {
      rollappId: isSet(object.rollappId) ? globalThis.String(object.rollappId) : '',
      creator: isSet(object.creator) ? globalThis.String(object.creator) : '',
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      maxSequencers: isSet(object.maxSequencers) ? globalThis.Number(object.maxSequencers) : 0,
      permissionedAddresses: globalThis.Array.isArray(object?.permissionedAddresses)
        ? object.permissionedAddresses.map((e: any) => globalThis.String(e))
        : [],
      genesisState: isSet(object.genesisState)
        ? RollappGenesisState.fromJSON(object.genesisState)
        : isSet(object.genesis_state)
          ? RollappGenesisState.fromJSON(object.genesis_state)
          : undefined,
      channelId: isSet(object.channelId)
        ? globalThis.String(object.channelId)
        : isSet(object.channel_id)
          ? globalThis.String(object.channel_id)
          : '',
      frozen: isSet(object.frozen) ? globalThis.Boolean(object.frozen) : false,
      registeredDenoms: globalThis.Array.isArray(object?.registeredDenoms)
        ? object.registeredDenoms.map((e: any) => globalThis.String(e))
        : [],
    }
  },

  toJSON(message: Rollapp): unknown {
    const obj: any = {}
    if (message.rollappId !== '') {
      obj.rollappId = message.rollappId
    }
    if (message.creator !== '') {
      obj.creator = message.creator
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version)
    }
    if (message.maxSequencers !== 0) {
      obj.maxSequencers = Math.round(message.maxSequencers)
    }
    if (message.permissionedAddresses?.length) {
      obj.permissionedAddresses = message.permissionedAddresses
    }
    if (message.genesisState !== undefined) {
      obj.genesisState = RollappGenesisState.toJSON(message.genesisState)
    }
    if (message.channelId !== '') {
      obj.channelId = message.channelId
    }
    if (message.frozen !== false) {
      obj.frozen = message.frozen
    }
    if (message.registeredDenoms?.length) {
      obj.registeredDenoms = message.registeredDenoms
    }
    return obj
  },

  create<I extends Exact<DeepPartial<Rollapp>, I>>(base?: I): Rollapp {
    return Rollapp.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<Rollapp>, I>>(object: I): Rollapp {
    const message = createBaseRollapp()
    message.rollappId = object.rollappId ?? ''
    message.creator = object.creator ?? ''
    message.version = object.version ?? 0
    message.maxSequencers = object.maxSequencers ?? 0
    message.permissionedAddresses = object.permissionedAddresses?.map((e) => e) || []
    message.genesisState =
      object.genesisState !== undefined && object.genesisState !== null
        ? RollappGenesisState.fromPartial(object.genesisState)
        : undefined
    message.channelId = object.channelId ?? ''
    message.frozen = object.frozen ?? false
    message.registeredDenoms = object.registeredDenoms?.map((e) => e) || []
    return message
  },
}

function createBaseRollappSummary(): RollappSummary {
  return { rollappId: '', latestStateIndex: undefined, latestFinalizedStateIndex: undefined }
}

export const RollappSummary: MessageFns<RollappSummary> = {
  encode(message: RollappSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rollappId !== '') {
      writer.uint32(10).string(message.rollappId)
    }
    if (message.latestStateIndex !== undefined) {
      StateInfoIndex.encode(message.latestStateIndex, writer.uint32(18).fork()).join()
    }
    if (message.latestFinalizedStateIndex !== undefined) {
      StateInfoIndex.encode(message.latestFinalizedStateIndex, writer.uint32(26).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RollappSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRollappSummary()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.rollappId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.latestStateIndex = StateInfoIndex.decode(reader, reader.uint32())
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.latestFinalizedStateIndex = StateInfoIndex.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): RollappSummary {
    return {
      rollappId: isSet(object.rollappId) ? globalThis.String(object.rollappId) : '',
      latestStateIndex: isSet(object.latestStateIndex)
        ? StateInfoIndex.fromJSON(object.latestStateIndex)
        : undefined,
      latestFinalizedStateIndex: isSet(object.latestFinalizedStateIndex)
        ? StateInfoIndex.fromJSON(object.latestFinalizedStateIndex)
        : undefined,
    }
  },

  toJSON(message: RollappSummary): unknown {
    const obj: any = {}
    if (message.rollappId !== '') {
      obj.rollappId = message.rollappId
    }
    if (message.latestStateIndex !== undefined) {
      obj.latestStateIndex = StateInfoIndex.toJSON(message.latestStateIndex)
    }
    if (message.latestFinalizedStateIndex !== undefined) {
      obj.latestFinalizedStateIndex = StateInfoIndex.toJSON(message.latestFinalizedStateIndex)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<RollappSummary>, I>>(base?: I): RollappSummary {
    return RollappSummary.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RollappSummary>, I>>(object: I): RollappSummary {
    const message = createBaseRollappSummary()
    message.rollappId = object.rollappId ?? ''
    message.latestStateIndex =
      object.latestStateIndex !== undefined && object.latestStateIndex !== null
        ? StateInfoIndex.fromPartial(object.latestStateIndex)
        : undefined
    message.latestFinalizedStateIndex =
      object.latestFinalizedStateIndex !== undefined && object.latestFinalizedStateIndex !== null
        ? StateInfoIndex.fromPartial(object.latestFinalizedStateIndex)
        : undefined
    return message
  },
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString())
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER')
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER')
  }
  return num
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
