// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/kyc/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import { KycLevel, kycLevelFromJSON, kycLevelToJSON } from '../did/did'

export const protobufPackage = 'metaearth.kyc'

export interface MsgApprove {
  issuer: string
  /** me-id */
  did: string
  regionId: string
  address: string
  pubkey: string
  level: KycLevel
  uri: string
  hash: string
  inviter: string
}

export interface MsgApproveResponse {}

export interface MsgUpdate {
  issuer: string
  did: string
  regionId: string
  level: KycLevel
  uri: string
  hash: string
  inviter: string
}

export interface MsgUpdateResponse {}

export interface MsgRemove {
  issuer: string
  did: string
}

export interface MsgRemoveResponse {}

export interface MsgCreateSBT {
  issuer: string
  did: string
  uri: string
  uriHash: string
  data: Uint8Array
}

export interface MsgCreateSBTResponse {}

export interface MsgUpdateSBT {
  issuer: string
  did: string
  uri: string
  uriHash: string
  data: Uint8Array
}

export interface MsgUpdateSBTResponse {}

export interface MsgDeleteSBT {
  issuer: string
  did: string
}

export interface MsgDeleteSBTResponse {}

export interface MsgCreateSubAccount {
  creator: string
  subAccount: string
  subAccountPubkey: string
}

export interface MsgCreateSubAccountResponse {}

function createBaseMsgApprove(): MsgApprove {
  return {
    issuer: '',
    did: '',
    regionId: '',
    address: '',
    pubkey: '',
    level: 0,
    uri: '',
    hash: '',
    inviter: '',
  }
}

export const MsgApprove: MessageFns<MsgApprove> = {
  encode(message: MsgApprove, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.issuer !== '') {
      writer.uint32(10).string(message.issuer)
    }
    if (message.did !== '') {
      writer.uint32(18).string(message.did)
    }
    if (message.regionId !== '') {
      writer.uint32(26).string(message.regionId)
    }
    if (message.address !== '') {
      writer.uint32(34).string(message.address)
    }
    if (message.pubkey !== '') {
      writer.uint32(42).string(message.pubkey)
    }
    if (message.level !== 0) {
      writer.uint32(48).int32(message.level)
    }
    if (message.uri !== '') {
      writer.uint32(58).string(message.uri)
    }
    if (message.hash !== '') {
      writer.uint32(66).string(message.hash)
    }
    if (message.inviter !== '') {
      writer.uint32(74).string(message.inviter)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgApprove {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgApprove()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.issuer = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.did = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.regionId = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.address = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.pubkey = reader.string()
          continue
        }
        case 6: {
          if (tag !== 48) {
            break
          }

          message.level = reader.int32() as any
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.uri = reader.string()
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.hash = reader.string()
          continue
        }
        case 9: {
          if (tag !== 74) {
            break
          }

          message.inviter = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgApprove {
    return {
      issuer: isSet(object.issuer) ? globalThis.String(object.issuer) : '',
      did: isSet(object.did) ? globalThis.String(object.did) : '',
      regionId: isSet(object.regionId) ? globalThis.String(object.regionId) : '',
      address: isSet(object.address) ? globalThis.String(object.address) : '',
      pubkey: isSet(object.pubkey) ? globalThis.String(object.pubkey) : '',
      level: isSet(object.level) ? kycLevelFromJSON(object.level) : 0,
      uri: isSet(object.uri) ? globalThis.String(object.uri) : '',
      hash: isSet(object.hash) ? globalThis.String(object.hash) : '',
      inviter: isSet(object.inviter) ? globalThis.String(object.inviter) : '',
    }
  },

  toJSON(message: MsgApprove): unknown {
    const obj: any = {}
    if (message.issuer !== '') {
      obj.issuer = message.issuer
    }
    if (message.did !== '') {
      obj.did = message.did
    }
    if (message.regionId !== '') {
      obj.regionId = message.regionId
    }
    if (message.address !== '') {
      obj.address = message.address
    }
    if (message.pubkey !== '') {
      obj.pubkey = message.pubkey
    }
    if (message.level !== 0) {
      obj.level = kycLevelToJSON(message.level)
    }
    if (message.uri !== '') {
      obj.uri = message.uri
    }
    if (message.hash !== '') {
      obj.hash = message.hash
    }
    if (message.inviter !== '') {
      obj.inviter = message.inviter
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgApprove>, I>>(base?: I): MsgApprove {
    return MsgApprove.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgApprove>, I>>(object: I): MsgApprove {
    const message = createBaseMsgApprove()
    message.issuer = object.issuer ?? ''
    message.did = object.did ?? ''
    message.regionId = object.regionId ?? ''
    message.address = object.address ?? ''
    message.pubkey = object.pubkey ?? ''
    message.level = object.level ?? 0
    message.uri = object.uri ?? ''
    message.hash = object.hash ?? ''
    message.inviter = object.inviter ?? ''
    return message
  },
}

function createBaseMsgApproveResponse(): MsgApproveResponse {
  return {}
}

export const MsgApproveResponse: MessageFns<MsgApproveResponse> = {
  encode(_: MsgApproveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgApproveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgApproveResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgApproveResponse {
    return {}
  },

  toJSON(_: MsgApproveResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgApproveResponse>, I>>(base?: I): MsgApproveResponse {
    return MsgApproveResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgApproveResponse>, I>>(_: I): MsgApproveResponse {
    const message = createBaseMsgApproveResponse()
    return message
  },
}

function createBaseMsgUpdate(): MsgUpdate {
  return { issuer: '', did: '', regionId: '', level: 0, uri: '', hash: '', inviter: '' }
}

export const MsgUpdate: MessageFns<MsgUpdate> = {
  encode(message: MsgUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.issuer !== '') {
      writer.uint32(10).string(message.issuer)
    }
    if (message.did !== '') {
      writer.uint32(18).string(message.did)
    }
    if (message.regionId !== '') {
      writer.uint32(26).string(message.regionId)
    }
    if (message.level !== 0) {
      writer.uint32(32).int32(message.level)
    }
    if (message.uri !== '') {
      writer.uint32(42).string(message.uri)
    }
    if (message.hash !== '') {
      writer.uint32(50).string(message.hash)
    }
    if (message.inviter !== '') {
      writer.uint32(58).string(message.inviter)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgUpdate()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.issuer = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.did = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.regionId = reader.string()
          continue
        }
        case 4: {
          if (tag !== 32) {
            break
          }

          message.level = reader.int32() as any
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.uri = reader.string()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.hash = reader.string()
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.inviter = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgUpdate {
    return {
      issuer: isSet(object.issuer) ? globalThis.String(object.issuer) : '',
      did: isSet(object.did) ? globalThis.String(object.did) : '',
      regionId: isSet(object.regionId) ? globalThis.String(object.regionId) : '',
      level: isSet(object.level) ? kycLevelFromJSON(object.level) : 0,
      uri: isSet(object.uri) ? globalThis.String(object.uri) : '',
      hash: isSet(object.hash) ? globalThis.String(object.hash) : '',
      inviter: isSet(object.inviter) ? globalThis.String(object.inviter) : '',
    }
  },

  toJSON(message: MsgUpdate): unknown {
    const obj: any = {}
    if (message.issuer !== '') {
      obj.issuer = message.issuer
    }
    if (message.did !== '') {
      obj.did = message.did
    }
    if (message.regionId !== '') {
      obj.regionId = message.regionId
    }
    if (message.level !== 0) {
      obj.level = kycLevelToJSON(message.level)
    }
    if (message.uri !== '') {
      obj.uri = message.uri
    }
    if (message.hash !== '') {
      obj.hash = message.hash
    }
    if (message.inviter !== '') {
      obj.inviter = message.inviter
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgUpdate>, I>>(base?: I): MsgUpdate {
    return MsgUpdate.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdate>, I>>(object: I): MsgUpdate {
    const message = createBaseMsgUpdate()
    message.issuer = object.issuer ?? ''
    message.did = object.did ?? ''
    message.regionId = object.regionId ?? ''
    message.level = object.level ?? 0
    message.uri = object.uri ?? ''
    message.hash = object.hash ?? ''
    message.inviter = object.inviter ?? ''
    return message
  },
}

function createBaseMsgUpdateResponse(): MsgUpdateResponse {
  return {}
}

export const MsgUpdateResponse: MessageFns<MsgUpdateResponse> = {
  encode(_: MsgUpdateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgUpdateResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgUpdateResponse {
    return {}
  },

  toJSON(_: MsgUpdateResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgUpdateResponse>, I>>(base?: I): MsgUpdateResponse {
    return MsgUpdateResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateResponse>, I>>(_: I): MsgUpdateResponse {
    const message = createBaseMsgUpdateResponse()
    return message
  },
}

function createBaseMsgRemove(): MsgRemove {
  return { issuer: '', did: '' }
}

export const MsgRemove: MessageFns<MsgRemove> = {
  encode(message: MsgRemove, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.issuer !== '') {
      writer.uint32(10).string(message.issuer)
    }
    if (message.did !== '') {
      writer.uint32(18).string(message.did)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRemove {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgRemove()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.issuer = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.did = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgRemove {
    return {
      issuer: isSet(object.issuer) ? globalThis.String(object.issuer) : '',
      did: isSet(object.did) ? globalThis.String(object.did) : '',
    }
  },

  toJSON(message: MsgRemove): unknown {
    const obj: any = {}
    if (message.issuer !== '') {
      obj.issuer = message.issuer
    }
    if (message.did !== '') {
      obj.did = message.did
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgRemove>, I>>(base?: I): MsgRemove {
    return MsgRemove.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgRemove>, I>>(object: I): MsgRemove {
    const message = createBaseMsgRemove()
    message.issuer = object.issuer ?? ''
    message.did = object.did ?? ''
    return message
  },
}

function createBaseMsgRemoveResponse(): MsgRemoveResponse {
  return {}
}

export const MsgRemoveResponse: MessageFns<MsgRemoveResponse> = {
  encode(_: MsgRemoveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRemoveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgRemoveResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgRemoveResponse {
    return {}
  },

  toJSON(_: MsgRemoveResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgRemoveResponse>, I>>(base?: I): MsgRemoveResponse {
    return MsgRemoveResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgRemoveResponse>, I>>(_: I): MsgRemoveResponse {
    const message = createBaseMsgRemoveResponse()
    return message
  },
}

function createBaseMsgCreateSBT(): MsgCreateSBT {
  return { issuer: '', did: '', uri: '', uriHash: '', data: new Uint8Array(0) }
}

export const MsgCreateSBT: MessageFns<MsgCreateSBT> = {
  encode(message: MsgCreateSBT, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.issuer !== '') {
      writer.uint32(10).string(message.issuer)
    }
    if (message.did !== '') {
      writer.uint32(18).string(message.did)
    }
    if (message.uri !== '') {
      writer.uint32(26).string(message.uri)
    }
    if (message.uriHash !== '') {
      writer.uint32(34).string(message.uriHash)
    }
    if (message.data.length !== 0) {
      writer.uint32(42).bytes(message.data)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateSBT {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgCreateSBT()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.issuer = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.did = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.uri = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.uriHash = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.data = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgCreateSBT {
    return {
      issuer: isSet(object.issuer) ? globalThis.String(object.issuer) : '',
      did: isSet(object.did) ? globalThis.String(object.did) : '',
      uri: isSet(object.uri) ? globalThis.String(object.uri) : '',
      uriHash: isSet(object.uriHash) ? globalThis.String(object.uriHash) : '',
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    }
  },

  toJSON(message: MsgCreateSBT): unknown {
    const obj: any = {}
    if (message.issuer !== '') {
      obj.issuer = message.issuer
    }
    if (message.did !== '') {
      obj.did = message.did
    }
    if (message.uri !== '') {
      obj.uri = message.uri
    }
    if (message.uriHash !== '') {
      obj.uriHash = message.uriHash
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgCreateSBT>, I>>(base?: I): MsgCreateSBT {
    return MsgCreateSBT.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateSBT>, I>>(object: I): MsgCreateSBT {
    const message = createBaseMsgCreateSBT()
    message.issuer = object.issuer ?? ''
    message.did = object.did ?? ''
    message.uri = object.uri ?? ''
    message.uriHash = object.uriHash ?? ''
    message.data = object.data ?? new Uint8Array(0)
    return message
  },
}

function createBaseMsgCreateSBTResponse(): MsgCreateSBTResponse {
  return {}
}

export const MsgCreateSBTResponse: MessageFns<MsgCreateSBTResponse> = {
  encode(_: MsgCreateSBTResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateSBTResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgCreateSBTResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgCreateSBTResponse {
    return {}
  },

  toJSON(_: MsgCreateSBTResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgCreateSBTResponse>, I>>(base?: I): MsgCreateSBTResponse {
    return MsgCreateSBTResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateSBTResponse>, I>>(_: I): MsgCreateSBTResponse {
    const message = createBaseMsgCreateSBTResponse()
    return message
  },
}

function createBaseMsgUpdateSBT(): MsgUpdateSBT {
  return { issuer: '', did: '', uri: '', uriHash: '', data: new Uint8Array(0) }
}

export const MsgUpdateSBT: MessageFns<MsgUpdateSBT> = {
  encode(message: MsgUpdateSBT, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.issuer !== '') {
      writer.uint32(10).string(message.issuer)
    }
    if (message.did !== '') {
      writer.uint32(18).string(message.did)
    }
    if (message.uri !== '') {
      writer.uint32(26).string(message.uri)
    }
    if (message.uriHash !== '') {
      writer.uint32(34).string(message.uriHash)
    }
    if (message.data.length !== 0) {
      writer.uint32(42).bytes(message.data)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateSBT {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgUpdateSBT()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.issuer = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.did = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.uri = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.uriHash = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.data = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgUpdateSBT {
    return {
      issuer: isSet(object.issuer) ? globalThis.String(object.issuer) : '',
      did: isSet(object.did) ? globalThis.String(object.did) : '',
      uri: isSet(object.uri) ? globalThis.String(object.uri) : '',
      uriHash: isSet(object.uriHash) ? globalThis.String(object.uriHash) : '',
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    }
  },

  toJSON(message: MsgUpdateSBT): unknown {
    const obj: any = {}
    if (message.issuer !== '') {
      obj.issuer = message.issuer
    }
    if (message.did !== '') {
      obj.did = message.did
    }
    if (message.uri !== '') {
      obj.uri = message.uri
    }
    if (message.uriHash !== '') {
      obj.uriHash = message.uriHash
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgUpdateSBT>, I>>(base?: I): MsgUpdateSBT {
    return MsgUpdateSBT.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateSBT>, I>>(object: I): MsgUpdateSBT {
    const message = createBaseMsgUpdateSBT()
    message.issuer = object.issuer ?? ''
    message.did = object.did ?? ''
    message.uri = object.uri ?? ''
    message.uriHash = object.uriHash ?? ''
    message.data = object.data ?? new Uint8Array(0)
    return message
  },
}

function createBaseMsgUpdateSBTResponse(): MsgUpdateSBTResponse {
  return {}
}

export const MsgUpdateSBTResponse: MessageFns<MsgUpdateSBTResponse> = {
  encode(_: MsgUpdateSBTResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateSBTResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgUpdateSBTResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgUpdateSBTResponse {
    return {}
  },

  toJSON(_: MsgUpdateSBTResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgUpdateSBTResponse>, I>>(base?: I): MsgUpdateSBTResponse {
    return MsgUpdateSBTResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateSBTResponse>, I>>(_: I): MsgUpdateSBTResponse {
    const message = createBaseMsgUpdateSBTResponse()
    return message
  },
}

function createBaseMsgDeleteSBT(): MsgDeleteSBT {
  return { issuer: '', did: '' }
}

export const MsgDeleteSBT: MessageFns<MsgDeleteSBT> = {
  encode(message: MsgDeleteSBT, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.issuer !== '') {
      writer.uint32(10).string(message.issuer)
    }
    if (message.did !== '') {
      writer.uint32(18).string(message.did)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteSBT {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgDeleteSBT()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.issuer = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.did = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgDeleteSBT {
    return {
      issuer: isSet(object.issuer) ? globalThis.String(object.issuer) : '',
      did: isSet(object.did) ? globalThis.String(object.did) : '',
    }
  },

  toJSON(message: MsgDeleteSBT): unknown {
    const obj: any = {}
    if (message.issuer !== '') {
      obj.issuer = message.issuer
    }
    if (message.did !== '') {
      obj.did = message.did
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgDeleteSBT>, I>>(base?: I): MsgDeleteSBT {
    return MsgDeleteSBT.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteSBT>, I>>(object: I): MsgDeleteSBT {
    const message = createBaseMsgDeleteSBT()
    message.issuer = object.issuer ?? ''
    message.did = object.did ?? ''
    return message
  },
}

function createBaseMsgDeleteSBTResponse(): MsgDeleteSBTResponse {
  return {}
}

export const MsgDeleteSBTResponse: MessageFns<MsgDeleteSBTResponse> = {
  encode(_: MsgDeleteSBTResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteSBTResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgDeleteSBTResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgDeleteSBTResponse {
    return {}
  },

  toJSON(_: MsgDeleteSBTResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgDeleteSBTResponse>, I>>(base?: I): MsgDeleteSBTResponse {
    return MsgDeleteSBTResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteSBTResponse>, I>>(_: I): MsgDeleteSBTResponse {
    const message = createBaseMsgDeleteSBTResponse()
    return message
  },
}

function createBaseMsgCreateSubAccount(): MsgCreateSubAccount {
  return { creator: '', subAccount: '', subAccountPubkey: '' }
}

export const MsgCreateSubAccount: MessageFns<MsgCreateSubAccount> = {
  encode(message: MsgCreateSubAccount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== '') {
      writer.uint32(10).string(message.creator)
    }
    if (message.subAccount !== '') {
      writer.uint32(18).string(message.subAccount)
    }
    if (message.subAccountPubkey !== '') {
      writer.uint32(26).string(message.subAccountPubkey)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateSubAccount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgCreateSubAccount()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.creator = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.subAccount = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.subAccountPubkey = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): MsgCreateSubAccount {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : '',
      subAccount: isSet(object.subAccount)
        ? globalThis.String(object.subAccount)
        : isSet(object.sub_account)
          ? globalThis.String(object.sub_account)
          : '',
      subAccountPubkey: isSet(object.subAccountPubkey)
        ? globalThis.String(object.subAccountPubkey)
        : isSet(object.sub_account_pubkey)
          ? globalThis.String(object.sub_account_pubkey)
          : '',
    }
  },

  toJSON(message: MsgCreateSubAccount): unknown {
    const obj: any = {}
    if (message.creator !== '') {
      obj.creator = message.creator
    }
    if (message.subAccount !== '') {
      obj.subAccount = message.subAccount
    }
    if (message.subAccountPubkey !== '') {
      obj.subAccountPubkey = message.subAccountPubkey
    }
    return obj
  },

  create<I extends Exact<DeepPartial<MsgCreateSubAccount>, I>>(base?: I): MsgCreateSubAccount {
    return MsgCreateSubAccount.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateSubAccount>, I>>(
    object: I,
  ): MsgCreateSubAccount {
    const message = createBaseMsgCreateSubAccount()
    message.creator = object.creator ?? ''
    message.subAccount = object.subAccount ?? ''
    message.subAccountPubkey = object.subAccountPubkey ?? ''
    return message
  },
}

function createBaseMsgCreateSubAccountResponse(): MsgCreateSubAccountResponse {
  return {}
}

export const MsgCreateSubAccountResponse: MessageFns<MsgCreateSubAccountResponse> = {
  encode(_: MsgCreateSubAccountResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateSubAccountResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseMsgCreateSubAccountResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): MsgCreateSubAccountResponse {
    return {}
  },

  toJSON(_: MsgCreateSubAccountResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<MsgCreateSubAccountResponse>, I>>(
    base?: I,
  ): MsgCreateSubAccountResponse {
    return MsgCreateSubAccountResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateSubAccountResponse>, I>>(
    _: I,
  ): MsgCreateSubAccountResponse {
    const message = createBaseMsgCreateSubAccountResponse()
    return message
  },
}

/** Msg defines the Msg service. */
export interface Msg {
  Approve(request: MsgApprove): Promise<MsgApproveResponse>
  Update(request: MsgUpdate): Promise<MsgUpdateResponse>
  Remove(request: MsgRemove): Promise<MsgRemoveResponse>
  CreateSBT(request: MsgCreateSBT): Promise<MsgCreateSBTResponse>
  UpdateSBT(request: MsgUpdateSBT): Promise<MsgUpdateSBTResponse>
  DeleteSBT(request: MsgDeleteSBT): Promise<MsgDeleteSBTResponse>
  CreateSubAccount(request: MsgCreateSubAccount): Promise<MsgCreateSubAccountResponse>
}

export const MsgServiceName = 'metaearth.kyc.Msg'
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc
  private readonly service: string
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName
    this.rpc = rpc
    this.Approve = this.Approve.bind(this)
    this.Update = this.Update.bind(this)
    this.Remove = this.Remove.bind(this)
    this.CreateSBT = this.CreateSBT.bind(this)
    this.UpdateSBT = this.UpdateSBT.bind(this)
    this.DeleteSBT = this.DeleteSBT.bind(this)
    this.CreateSubAccount = this.CreateSubAccount.bind(this)
  }
  Approve(request: MsgApprove): Promise<MsgApproveResponse> {
    const data = MsgApprove.encode(request).finish()
    const promise = this.rpc.request(this.service, 'Approve', data)
    return promise.then((data) => MsgApproveResponse.decode(new BinaryReader(data)))
  }

  Update(request: MsgUpdate): Promise<MsgUpdateResponse> {
    const data = MsgUpdate.encode(request).finish()
    const promise = this.rpc.request(this.service, 'Update', data)
    return promise.then((data) => MsgUpdateResponse.decode(new BinaryReader(data)))
  }

  Remove(request: MsgRemove): Promise<MsgRemoveResponse> {
    const data = MsgRemove.encode(request).finish()
    const promise = this.rpc.request(this.service, 'Remove', data)
    return promise.then((data) => MsgRemoveResponse.decode(new BinaryReader(data)))
  }

  CreateSBT(request: MsgCreateSBT): Promise<MsgCreateSBTResponse> {
    const data = MsgCreateSBT.encode(request).finish()
    const promise = this.rpc.request(this.service, 'CreateSBT', data)
    return promise.then((data) => MsgCreateSBTResponse.decode(new BinaryReader(data)))
  }

  UpdateSBT(request: MsgUpdateSBT): Promise<MsgUpdateSBTResponse> {
    const data = MsgUpdateSBT.encode(request).finish()
    const promise = this.rpc.request(this.service, 'UpdateSBT', data)
    return promise.then((data) => MsgUpdateSBTResponse.decode(new BinaryReader(data)))
  }

  DeleteSBT(request: MsgDeleteSBT): Promise<MsgDeleteSBTResponse> {
    const data = MsgDeleteSBT.encode(request).finish()
    const promise = this.rpc.request(this.service, 'DeleteSBT', data)
    return promise.then((data) => MsgDeleteSBTResponse.decode(new BinaryReader(data)))
  }

  CreateSubAccount(request: MsgCreateSubAccount): Promise<MsgCreateSubAccountResponse> {
    const data = MsgCreateSubAccount.encode(request).finish()
    const promise = this.rpc.request(this.service, 'CreateSubAccount', data)
    return promise.then((data) => MsgCreateSubAccountResponse.decode(new BinaryReader(data)))
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, 'base64'))
  } else {
    const bin = globalThis.atob(b64)
    const arr = new Uint8Array(bin.length)
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i)
    }
    return arr
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString('base64')
  } else {
    const bin: string[] = []
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte))
    })
    return globalThis.btoa(bin.join(''))
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
