// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/delayedack/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import { PageRequest, PageResponse } from '../../cosmos/base/query/v1beta1/pagination'
import {
  RollappPacket,
  RollappPacket_Type,
  rollappPacket_TypeFromJSON,
  rollappPacket_TypeToJSON,
} from '../common/rollapp_packet'
import { Status, statusFromJSON, statusToJSON } from '../common/status'
import { Params } from './params'

export const protobufPackage = 'metaearth.delayedack'

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined
}

export interface QueryRollappPacketsRequest {
  rollappId: string
  status: Status
  type: RollappPacket_Type
  pagination: PageRequest | undefined
}

export interface QueryRollappPacketListResponse {
  rollappPackets: RollappPacket[]
  pagination: PageResponse | undefined
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {}
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryParamsRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): QueryParamsRequest {
    return {}
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest()
    return message
  },
}

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined }
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryParamsResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.params = Params.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined }
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {}
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(
    object: I,
  ): QueryParamsResponse {
    const message = createBaseQueryParamsResponse()
    message.params =
      object.params !== undefined && object.params !== null
        ? Params.fromPartial(object.params)
        : undefined
    return message
  },
}

function createBaseQueryRollappPacketsRequest(): QueryRollappPacketsRequest {
  return { rollappId: '', status: 0, type: 0, pagination: undefined }
}

export const QueryRollappPacketsRequest: MessageFns<QueryRollappPacketsRequest> = {
  encode(
    message: QueryRollappPacketsRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.rollappId !== '') {
      writer.uint32(10).string(message.rollappId)
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status)
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type)
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(34).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryRollappPacketsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryRollappPacketsRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.rollappId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.status = reader.int32() as any
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.type = reader.int32() as any
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.pagination = PageRequest.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryRollappPacketsRequest {
    return {
      rollappId: isSet(object.rollappId) ? globalThis.String(object.rollappId) : '',
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      type: isSet(object.type) ? rollappPacket_TypeFromJSON(object.type) : 0,
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryRollappPacketsRequest): unknown {
    const obj: any = {}
    if (message.rollappId !== '') {
      obj.rollappId = message.rollappId
    }
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status)
    }
    if (message.type !== 0) {
      obj.type = rollappPacket_TypeToJSON(message.type)
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryRollappPacketsRequest>, I>>(
    base?: I,
  ): QueryRollappPacketsRequest {
    return QueryRollappPacketsRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryRollappPacketsRequest>, I>>(
    object: I,
  ): QueryRollappPacketsRequest {
    const message = createBaseQueryRollappPacketsRequest()
    message.rollappId = object.rollappId ?? ''
    message.status = object.status ?? 0
    message.type = object.type ?? 0
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageRequest.fromPartial(object.pagination)
        : undefined
    return message
  },
}

function createBaseQueryRollappPacketListResponse(): QueryRollappPacketListResponse {
  return { rollappPackets: [], pagination: undefined }
}

export const QueryRollappPacketListResponse: MessageFns<QueryRollappPacketListResponse> = {
  encode(
    message: QueryRollappPacketListResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.rollappPackets) {
      RollappPacket.encode(v!, writer.uint32(10).fork()).join()
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryRollappPacketListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryRollappPacketListResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.rollappPackets.push(RollappPacket.decode(reader, reader.uint32()))
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.pagination = PageResponse.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryRollappPacketListResponse {
    return {
      rollappPackets: globalThis.Array.isArray(object?.rollappPackets)
        ? object.rollappPackets.map((e: any) => RollappPacket.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryRollappPacketListResponse): unknown {
    const obj: any = {}
    if (message.rollappPackets?.length) {
      obj.rollappPackets = message.rollappPackets.map((e) => RollappPacket.toJSON(e))
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryRollappPacketListResponse>, I>>(
    base?: I,
  ): QueryRollappPacketListResponse {
    return QueryRollappPacketListResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryRollappPacketListResponse>, I>>(
    object: I,
  ): QueryRollappPacketListResponse {
    const message = createBaseQueryRollappPacketListResponse()
    message.rollappPackets = object.rollappPackets?.map((e) => RollappPacket.fromPartial(e)) || []
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageResponse.fromPartial(object.pagination)
        : undefined
    return message
  },
}

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>
  /** Queries a list of RollappPacket items by rollappID. */
  GetPackets(request: QueryRollappPacketsRequest): Promise<QueryRollappPacketListResponse>
}

export const QueryServiceName = 'metaearth.delayedack.Query'
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc
  private readonly service: string
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName
    this.rpc = rpc
    this.Params = this.Params.bind(this)
    this.GetPackets = this.GetPackets.bind(this)
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish()
    const promise = this.rpc.request(this.service, 'Params', data)
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)))
  }

  GetPackets(request: QueryRollappPacketsRequest): Promise<QueryRollappPacketListResponse> {
    const data = QueryRollappPacketsRequest.encode(request).finish()
    const promise = this.rpc.request(this.service, 'GetPackets', data)
    return promise.then((data) => QueryRollappPacketListResponse.decode(new BinaryReader(data)))
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
