// Generated by Ignite ignite.com/cli

import { StdFee } from '@cosmjs/launchpad'
import { SigningStargateClient, DeliverTxResponse } from '@cosmjs/stargate'
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from '@cosmjs/proto-signing'
import { msgTypes } from './registry'
import { IgniteClient } from '../client'
import { MissingWalletError } from '../helpers'
import { Api } from './rest'
import { MsgTransfer } from './types/ibc/applications/transfer/v1/tx'
import { getSignData, handleTxRaw } from '../../me-client-utils'
import { TxRaw } from '../cosmos.tx.v1beta1/types/cosmos/tx/v1beta1/tx'
import { getSimulateGas } from '../../me-client-utils'
import { gas_max_set } from '../../config/define'

import { Allocation as typeAllocation } from './types'
import { TransferAuthorization as typeTransferAuthorization } from './types'
import { DenomTrace as typeDenomTrace } from './types'
import { Params as typeParams } from './types'
import { getFinalGas } from '../../me-client-utils/config'

export { MsgTransfer }

type sendMsgTransferParams = {
  value: MsgTransfer
  fee?: StdFee
  memo?: string
}

type msgTransferParams = {
  value: MsgTransfer
}

export const registry = new Registry(msgTypes)

type Field = {
  name: string
  type: unknown
}
function getStructure(template) {
  const structure: { fields: Field[] } = { fields: [] }
  for (let [key, value] of Object.entries(template)) {
    let field = { name: key, type: typeof value }
    structure.fields.push(field)
  }
  return structure
}
const defaultFee = {
  amount: [],
  gas: '200000',
}

interface TxClientOptions {
  addr: string
  prefix: string
  signer?: OfflineSigner
}

export const txClient = (
  { signer, prefix, addr }: TxClientOptions = { addr: 'http://localhost:26657', prefix: 'cosmos' },
) => {
  return {
    async sendMsgTransfer({ value, fee, memo, gas = 0, chainId }: any): Promise<any> {
      if (!signer) {
        throw new Error('TxClient:sendMsgTransfer: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.offline(signer, {
          registry,
        })
        let msg = this.msgTransfer({ value: MsgTransfer.fromPartial(value) })

        const { gasUsed } = await this.simulateSendGas({
          value,
          chainId,
        })

        if (!gasUsed) throw Error(`sendMsgSend: gasUsed error`)
        const gas_fee = getFinalGas(gasUsed, gas)
        const fee = {
          amount: [{ denom: value.token.denom, amount: `${gas_fee}` }],
          // gas: String(gas),
          gas: gas_max_set,
        }

        const signResData = await getSignData({
          signingClient,
          address,
          msg,
          fee,
          memo,
          chainId,
        })
        if (!(signResData as any).result) throw Error('signResData Error')
        let rowRes = signResData.rowRes

        return await handleTxRaw(rowRes)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgTransfer: Could not broadcast Tx: ' + e.message)
      }
    },

    msgTransfer({ value }: msgTransferParams): EncodeObject {
      try {
        return {
          typeUrl: '/ibc.applications.transfer.v1.MsgTransfer',
          value: MsgTransfer.fromPartial(value),
        }
      } catch (e: any) {
        throw new Error('TxClient:MsgTransfer: Could not create message: ' + e.message)
      }
    },

    async simulateSendGas({ value, gas = 20000, chainId }: any) {
      console.log('simulateSendGas value:', value)
      if (!signer) {
        throw new Error('TxClient:sendMsgSend: Unable to sign Tx. Signer is not present.')
      }
      let { address } = (await signer.getAccounts())[0]
      let signingClient = await SigningStargateClient.offline(signer, { registry })
      let msg = this.msgTransfer({ value: MsgTransfer.fromPartial(value) })

      let gas_fee: any = gas
      let fee = {
        amount: [{ denom: value.token.denom, amount: `${gas_fee}` }],
        gas: gas_max_set,
      }
      const isRollApp = value.token.denom !== 'umec'
      let signResData = await getSignData({ signingClient, address, msg, fee, chainId })
      if (!(signResData as any).result) throw Error()
      let rowRes = signResData.rowRes
      const rowResJSON = await handleTxRaw(rowRes)
      return await getSimulateGas(rowResJSON)
    },
  }
}

interface QueryClientOptions {
  addr: string
}

export const queryClient = (
  { addr: addr }: QueryClientOptions = { addr: 'http://localhost:1317' },
) => {
  return new Api({ baseURL: addr })
}

class SDKModule {
  public query: ReturnType<typeof queryClient>
  public tx: ReturnType<typeof txClient>
  public structure: Record<string, unknown>
  public registry: Array<[string, GeneratedType]> = []

  constructor(client: IgniteClient) {
    this.query = queryClient({ addr: client.env.apiURL })
    this.updateTX(client)
    this.structure = {
      Allocation: getStructure(typeAllocation.fromPartial({})),
      TransferAuthorization: getStructure(typeTransferAuthorization.fromPartial({})),
      DenomTrace: getStructure(typeDenomTrace.fromPartial({})),
      Params: getStructure(typeParams.fromPartial({})),
    }
    client.on('signer-changed', (signer) => {
      this.updateTX(client)
    })
  }
  updateTX(client: IgniteClient) {
    const methods = txClient({
      signer: client.signer,
      addr: client.env.rpcURL,
      prefix: client.env.prefix ?? 'cosmos',
    })

    this.tx = methods
    for (let m in methods) {
      this.tx[m] = methods[m].bind(this.tx)
    }
  }
}

const Module = (test: IgniteClient) => {
  return {
    module: {
      IbcApplicationsTransferV1: new SDKModule(test),
    },
    registry: msgTypes,
  }
}
export default Module
