// Generated by Ignite ignite.com/cli

import { StdFee } from '@cosmjs/launchpad'
import { SigningStargateClient, DeliverTxResponse } from '@cosmjs/stargate'
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from '@cosmjs/proto-signing'
import { Any } from './types/google/protobuf/any'
import { msgTypes } from './registry'
import { IgniteClient } from '../client'
import { MissingWalletError } from '../helpers'
import { Api } from './rest'
import { MsgVote } from './types/cosmos/gov/v1beta1/tx'
import { MsgVoteWeighted } from './types/cosmos/gov/v1beta1/tx'
import { MsgSubmitProposal } from './types/cosmos/gov/v1beta1/tx'
import { MsgDeposit } from './types/cosmos/gov/v1beta1/tx'
import { getSignData, handleTxRaw, getSimulateGas } from '../../me-client-utils'
import { gas_max_set } from '../../config/define'
import { getFinalGas, getFinalGasLimit } from '../../me-client-utils/config'
import {
  SoftwareUpgradeProposal,
  Plan,
} from '../cosmos.upgrade.v1beta1/types/cosmos/upgrade/v1beta1/upgrade'

import { WeightedVoteOption as typeWeightedVoteOption } from './types'
import { TextProposal as typeTextProposal } from './types'
import { Deposit as typeDeposit } from './types'
import { Proposal as typeProposal } from './types'
import { TallyResult as typeTallyResult } from './types'
import { Vote as typeVote } from './types'
import { DepositParams as typeDepositParams } from './types'
import { VotingParams as typeVotingParams } from './types'
import { TallyParams as typeTallyParams } from './types'
import { SoftwareUpgradeProposalMsg } from '../../types'

export { MsgVote, MsgVoteWeighted, MsgSubmitProposal, MsgDeposit }

type sendMsgVoteParams = {
  value: MsgVote
  fee?: StdFee
  memo?: string
  gas?: number | string
}

type sendMsgVoteWeightedParams = {
  value: MsgVoteWeighted
  fee?: StdFee
  memo?: string
}

type sendMsgSubmitProposalParams = {
  value: SoftwareUpgradeProposalMsg
  fee?: StdFee
  memo?: string
  gas?: number | string
}

type sendMsgDepositParams = {
  value: MsgDeposit
  fee?: StdFee
  memo?: string
}

type msgVoteParams = {
  value: MsgVote
}

type msgVoteWeightedParams = {
  value: MsgVoteWeighted
}

type msgSubmitProposalParams = {
  value: MsgSubmitProposal
}

type msgDepositParams = {
  value: MsgDeposit
}

type msgSoftwareUpgradeParams = {
  value: SoftwareUpgradeProposal
}

export const registry = new Registry(msgTypes)

type Field = {
  name: string
  type: unknown
}
function getStructure(template) {
  const structure: { fields: Field[] } = { fields: [] }
  for (let [key, value] of Object.entries(template)) {
    let field = { name: key, type: typeof value }
    structure.fields.push(field)
  }
  return structure
}
const defaultFee = {
  amount: [],
  gas: '200000',
}

interface TxClientOptions {
  addr?: string
  prefix: string
  signer?: OfflineSigner
}

export const txClient = (
  { signer, prefix, addr }: TxClientOptions = { addr: 'http://localhost:26657', prefix: 'cosmos' },
) => {
  return {
    async sendMsgVote({ value, gas = 0, memo }: sendMsgVoteParams): Promise<{ tx_bytes: string }> {
      if (!signer) {
        throw new Error('TxClient:sendMsgVote: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.offline(signer, { registry })
        let msg = this.msgVote({ value: MsgVote.fromPartial(value) })
        const { gasUsed } = await this.simulateVoteGas({ value })
        if (!gasUsed) throw Error(`sendMsgVote: gasUsed error`)
        const gas_fee = getFinalGas(gasUsed, gas)
        const gas_limit = getFinalGasLimit(gasUsed)
        let fee = {
          amount: [{ denom: 'umec', amount: `${gas_fee}` }],
          gas: gas_limit,
        }
        let signResData = await getSignData({ signingClient, address, msg, fee, memo })
        if (!(signResData as any).result) throw Error(`sendMsgVote: signResData error`)
        let rowRes = signResData.rowRes
        return await handleTxRaw(rowRes)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgVote: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgVoteWeighted({
      value,
      fee,
      memo,
    }: sendMsgVoteWeightedParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgVoteWeighted: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, {
          registry,
          prefix,
        } as any)
        let msg = this.msgVoteWeighted({ value: MsgVoteWeighted.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgVoteWeighted: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgSubmitProposal({
      value,
      gas = 0,
      memo,
    }: sendMsgSubmitProposalParams): Promise<{ tx_bytes: string }> {
      if (!signer) {
        throw new Error('TxClient:sendMsgSubmitProposal: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.offline(signer, { registry })

        let processedValue: Partial<MsgSubmitProposal>
        // Build content as Any type if it has plan (SoftwareUpgradeProposal)
        if (value.content?.plan) {
          const content = value.content
          processedValue = {
            proposer: value.proposer,
            initialDeposit: value.initialDeposit,
            content: this.msgSoftwareUpgrade({ value: content }),
          }
        }
        let msg = this.msgSubmitProposal({ value: MsgSubmitProposal.fromPartial(processedValue) })
        const { gasUsed } = await this.simulateSubmitProposalGas({ value: processedValue })
        if (!gasUsed) throw Error(`sendMsgSubmitProposal: gasUsed error`)
        const gas_fee = getFinalGas(gasUsed, gas)
        const gas_limit = getFinalGasLimit(gasUsed)
        let fee = {
          amount: [{ denom: 'umec', amount: `${gas_fee}` }],
          gas: gas_limit,
        }
        let signResData = await getSignData({ signingClient, address, msg, fee, memo })
        if (!(signResData as any).result) throw Error(`sendMsgSubmitProposal: signResData error`)
        let rowRes = signResData.rowRes
        return await handleTxRaw(rowRes)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgSubmitProposal: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgDeposit({ value, fee, memo }: sendMsgDepositParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgDeposit: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, {
          registry,
          prefix,
        } as any)
        let msg = this.msgDeposit({ value: MsgDeposit.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgDeposit: Could not broadcast Tx: ' + e.message)
      }
    },

    msgVote({ value }: msgVoteParams): EncodeObject {
      try {
        return { typeUrl: '/cosmos.gov.v1beta1.MsgVote', value: MsgVote.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgVote: Could not create message: ' + e.message)
      }
    },

    msgVoteWeighted({ value }: msgVoteWeightedParams): EncodeObject {
      try {
        return {
          typeUrl: '/cosmos.gov.v1beta1.MsgVoteWeighted',
          value: MsgVoteWeighted.fromPartial(value),
        }
      } catch (e: any) {
        throw new Error('TxClient:MsgVoteWeighted: Could not create message: ' + e.message)
      }
    },

    msgSubmitProposal({ value }: msgSubmitProposalParams): EncodeObject {
      try {
        return {
          typeUrl: '/cosmos.gov.v1beta1.MsgSubmitProposal',
          value: MsgSubmitProposal.fromPartial(value),
        }
      } catch (e: any) {
        throw new Error('TxClient:MsgSubmitProposal: Could not create message: ' + e.message)
      }
    },

    msgDeposit({ value }: msgDepositParams): EncodeObject {
      try {
        return { typeUrl: '/cosmos.gov.v1beta1.MsgDeposit', value: MsgDeposit.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgDeposit: Could not create message: ' + e.message)
      }
    },

    msgSoftwareUpgrade({ value }: msgSoftwareUpgradeParams): Any {
      try {
        return {
          typeUrl: '/cosmos.upgrade.v1beta1.SoftwareUpgradeProposal',
          value: SoftwareUpgradeProposal.encode(
            SoftwareUpgradeProposal.fromPartial(value),
          ).finish(),
        }
      } catch (e: any) {
        throw new Error('TxClient:MsgSoftwareUpgrade: Could not create message: ' + e.message)
      }
    },

    // Gas simulation methods
    async simulateSubmitProposalGas({
      value,
      gas = 50000,
    }: {
      value: MsgSubmitProposal
      gas?: number
    }) {
      if (!signer) {
        throw new Error(
          'TxClient:simulateSubmitProposalGas: Unable to sign Tx. Signer is not present.',
        )
      }
      let { address } = (await signer.getAccounts())[0]
      let signingClient = await SigningStargateClient.offline(signer, { registry })
      let msg = this.msgSubmitProposal({ value: MsgSubmitProposal.fromPartial(value) })

      let gas_fee: any = gas
      let fee = {
        amount: [{ denom: 'umec', amount: `${gas_fee}` }],
        gas: gas_max_set,
      }
      let signResData = await getSignData({ signingClient, address, msg, fee })
      if (!(signResData as any).result) throw Error('simulateSubmitProposalGas: signResData error')
      let rowRes = signResData.rowRes
      const rowResJSON = await handleTxRaw(rowRes)
      return await getSimulateGas(rowResJSON)
    },

    async simulateVoteGas({ value, gas = 50000 }: { value: MsgVote; gas?: number }) {
      if (!signer) {
        throw new Error('TxClient:simulateVoteGas: Unable to sign Tx. Signer is not present.')
      }
      let { address } = (await signer.getAccounts())[0]
      let signingClient = await SigningStargateClient.offline(signer, { registry })
      let msg = this.msgVote({ value: MsgVote.fromPartial(value) })

      let gas_fee: any = gas
      let fee = {
        amount: [{ denom: 'umec', amount: `${gas_fee}` }],
        gas: gas_max_set,
      }
      let signResData = await getSignData({ signingClient, address, msg, fee })
      if (!(signResData as any).result) throw Error('simulateVoteGas: signResData error')
      let rowRes = signResData.rowRes
      const rowResJSON = await handleTxRaw(rowRes)
      return await getSimulateGas(rowResJSON)
    },
  }
}

interface QueryClientOptions {
  addr: string
}

export const queryClient = (
  { addr: addr }: QueryClientOptions = { addr: 'http://localhost:1317' },
) => {
  return new Api({ baseURL: addr })
}

class SDKModule {
  public query: ReturnType<typeof queryClient>
  public tx: ReturnType<typeof txClient>
  public structure: Record<string, unknown>
  public registry: Array<[string, GeneratedType]> = []

  constructor(client: IgniteClient) {
    this.query = queryClient({ addr: client.env.apiURL })
    this.updateTX(client)
    this.structure = {
      WeightedVoteOption: getStructure(typeWeightedVoteOption.fromPartial({})),
      TextProposal: getStructure(typeTextProposal.fromPartial({})),
      Deposit: getStructure(typeDeposit.fromPartial({})),
      Proposal: getStructure(typeProposal.fromPartial({})),
      TallyResult: getStructure(typeTallyResult.fromPartial({})),
      Vote: getStructure(typeVote.fromPartial({})),
      DepositParams: getStructure(typeDepositParams.fromPartial({})),
      VotingParams: getStructure(typeVotingParams.fromPartial({})),
      TallyParams: getStructure(typeTallyParams.fromPartial({})),
    }
    client.on('signer-changed', (signer) => {
      this.updateTX(client)
    })
  }
  updateTX(client: IgniteClient) {
    const methods = txClient({
      signer: client.signer,
      addr: client.env.rpcURL,
      prefix: client.env.prefix ?? 'cosmos',
    })

    this.tx = methods
    for (let m in methods) {
      this.tx[m] = methods[m].bind(this.tx)
    }
  }
}

const Module = (test: IgniteClient) => {
  return {
    module: {
      CosmosGovV1Beta1: new SDKModule(test),
    },
    registry: msgTypes,
  }
}
export default Module
