// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/wstaking/region.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'

export const protobufPackage = 'metaearth.wstaking'

export enum regionAccountType {
  REGION_ACCOUNT_TYPE_BASE = 0,
  REGION_ACCOUNT_TYPE_DEPOSIT_INTEREST = 1,
  UNRECOGNIZED = -1,
}

export function regionAccountTypeFromJSON(object: any): regionAccountType {
  switch (object) {
    case 0:
    case 'REGION_ACCOUNT_TYPE_BASE':
      return regionAccountType.REGION_ACCOUNT_TYPE_BASE
    case 1:
    case 'REGION_ACCOUNT_TYPE_DEPOSIT_INTEREST':
      return regionAccountType.REGION_ACCOUNT_TYPE_DEPOSIT_INTEREST
    case -1:
    case 'UNRECOGNIZED':
    default:
      return regionAccountType.UNRECOGNIZED
  }
}

export function regionAccountTypeToJSON(object: regionAccountType): string {
  switch (object) {
    case regionAccountType.REGION_ACCOUNT_TYPE_BASE:
      return 'REGION_ACCOUNT_TYPE_BASE'
    case regionAccountType.REGION_ACCOUNT_TYPE_DEPOSIT_INTEREST:
      return 'REGION_ACCOUNT_TYPE_DEPOSIT_INTEREST'
    case regionAccountType.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

export interface Region {
  regionId: string
  name: string
  creator: string
  operatorAddress: string
  nftClassId: string
  regionTreasureAddr: string
  depositInterestAddr: string
  /** tokens define the region tokens share */
  regionShare: string
  delegateInterest: string
  delegateAmount: string
  fixedDepositAmount: string
}

function createBaseRegion(): Region {
  return {
    regionId: '',
    name: '',
    creator: '',
    operatorAddress: '',
    nftClassId: '',
    regionTreasureAddr: '',
    depositInterestAddr: '',
    regionShare: '',
    delegateInterest: '',
    delegateAmount: '',
    fixedDepositAmount: '',
  }
}

export const Region: MessageFns<Region> = {
  encode(message: Region, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.regionId !== '') {
      writer.uint32(10).string(message.regionId)
    }
    if (message.name !== '') {
      writer.uint32(18).string(message.name)
    }
    if (message.creator !== '') {
      writer.uint32(26).string(message.creator)
    }
    if (message.operatorAddress !== '') {
      writer.uint32(34).string(message.operatorAddress)
    }
    if (message.nftClassId !== '') {
      writer.uint32(42).string(message.nftClassId)
    }
    if (message.regionTreasureAddr !== '') {
      writer.uint32(50).string(message.regionTreasureAddr)
    }
    if (message.depositInterestAddr !== '') {
      writer.uint32(66).string(message.depositInterestAddr)
    }
    if (message.regionShare !== '') {
      writer.uint32(74).string(message.regionShare)
    }
    if (message.delegateInterest !== '') {
      writer.uint32(82).string(message.delegateInterest)
    }
    if (message.delegateAmount !== '') {
      writer.uint32(90).string(message.delegateAmount)
    }
    if (message.fixedDepositAmount !== '') {
      writer.uint32(98).string(message.fixedDepositAmount)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Region {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRegion()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.regionId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.name = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.creator = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.operatorAddress = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.nftClassId = reader.string()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.regionTreasureAddr = reader.string()
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.depositInterestAddr = reader.string()
          continue
        }
        case 9: {
          if (tag !== 74) {
            break
          }

          message.regionShare = reader.string()
          continue
        }
        case 10: {
          if (tag !== 82) {
            break
          }

          message.delegateInterest = reader.string()
          continue
        }
        case 11: {
          if (tag !== 90) {
            break
          }

          message.delegateAmount = reader.string()
          continue
        }
        case 12: {
          if (tag !== 98) {
            break
          }

          message.fixedDepositAmount = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): Region {
    return {
      regionId: isSet(object.regionId) ? globalThis.String(object.regionId) : '',
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      creator: isSet(object.creator) ? globalThis.String(object.creator) : '',
      operatorAddress: isSet(object.operatorAddress)
        ? globalThis.String(object.operatorAddress)
        : isSet(object.operator_address)
          ? globalThis.String(object.operator_address)
          : '',
      nftClassId: isSet(object.nftClassId)
        ? globalThis.String(object.nftClassId)
        : isSet(object.nft_class_id)
          ? globalThis.String(object.nft_class_id)
          : '',
      regionTreasureAddr: isSet(object.regionTreasureAddr)
        ? globalThis.String(object.regionTreasureAddr)
        : isSet(object.region_treasure_addr)
          ? globalThis.String(object.region_treasure_addr)
          : '',
      depositInterestAddr: isSet(object.depositInterestAddr)
        ? globalThis.String(object.depositInterestAddr)
        : isSet(object.deposit_interest_addr)
          ? globalThis.String(object.deposit_interest_addr)
          : '',
      regionShare: isSet(object.regionShare)
        ? globalThis.String(object.regionShare)
        : isSet(object.region_share)
          ? globalThis.String(object.region_share)
          : '',
      delegateInterest: isSet(object.delegateInterest)
        ? globalThis.String(object.delegateInterest)
        : isSet(object.delegate_interest)
          ? globalThis.String(object.delegate_interest)
          : '',
      delegateAmount: isSet(object.delegateAmount)
        ? globalThis.String(object.delegateAmount)
        : isSet(object.delegate_amount)
          ? globalThis.String(object.delegate_amount)
          : '',
      fixedDepositAmount: isSet(object.fixedDepositAmount)
        ? globalThis.String(object.fixedDepositAmount)
        : isSet(object.fixed_deposit_amount)
          ? globalThis.String(object.fixed_deposit_amount)
          : '',
    }
  },

  toJSON(message: Region): unknown {
    const obj: any = {}
    if (message.regionId !== '') {
      obj.regionId = message.regionId
    }
    if (message.name !== '') {
      obj.name = message.name
    }
    if (message.creator !== '') {
      obj.creator = message.creator
    }
    if (message.operatorAddress !== '') {
      obj.operatorAddress = message.operatorAddress
    }
    if (message.nftClassId !== '') {
      obj.nftClassId = message.nftClassId
    }
    if (message.regionTreasureAddr !== '') {
      obj.regionTreasureAddr = message.regionTreasureAddr
    }
    if (message.depositInterestAddr !== '') {
      obj.depositInterestAddr = message.depositInterestAddr
    }
    if (message.regionShare !== '') {
      obj.regionShare = message.regionShare
    }
    if (message.delegateInterest !== '') {
      obj.delegateInterest = message.delegateInterest
    }
    if (message.delegateAmount !== '') {
      obj.delegateAmount = message.delegateAmount
    }
    if (message.fixedDepositAmount !== '') {
      obj.fixedDepositAmount = message.fixedDepositAmount
    }
    return obj
  },

  create<I extends Exact<DeepPartial<Region>, I>>(base?: I): Region {
    return Region.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<Region>, I>>(object: I): Region {
    const message = createBaseRegion()
    message.regionId = object.regionId ?? ''
    message.name = object.name ?? ''
    message.creator = object.creator ?? ''
    message.operatorAddress = object.operatorAddress ?? ''
    message.nftClassId = object.nftClassId ?? ''
    message.regionTreasureAddr = object.regionTreasureAddr ?? ''
    message.depositInterestAddr = object.depositInterestAddr ?? ''
    message.regionShare = object.regionShare ?? ''
    message.delegateInterest = object.delegateInterest ?? ''
    message.delegateAmount = object.delegateAmount ?? ''
    message.fixedDepositAmount = object.fixedDepositAmount ?? ''
    return message
  },
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
