// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/wstaking/stake.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import { Timestamp } from '../../google/protobuf/timestamp'

export const protobufPackage = 'metaearth.wstaking'

/**
 * Stake represents the bond with tokens held by an account. It is
 * owned by one staker, and is associated with the voting power of one
 * validator.
 */
export interface Stake {
  /** staker_address is the bech32-encoded address of the staker. */
  stakerAddress: string
  /** validator_address is the bech32-encoded address of the validator. */
  validatorAddress: string
  /** shares define the stake shares received. */
  shares: string
  startHeight: number
  rewards: string
  amount: string
  unmovable: string
}

/**
 * UnbondingStake stores all of a single staker's unbonding bonds
 * for a single validator in an time-ordered list.
 */
export interface UnbondingStake {
  /** staker_address is the bech32-encoded address of the staker. */
  stakerAddress: string
  /** validator_address is the bech32-encoded address of the validator. */
  validatorAddress: string
  /** entries are the unbonding delegation entries. */
  entries: UnbondingStakeEntry[]
}

/** UnbondingStakeEntry defines an unbonding object with relevant metadata. */
export interface UnbondingStakeEntry {
  /** creation_height is the height which the unbonding took place. */
  creationHeight: number
  /** completion_time is the unix time for unbonding completion. */
  completionTime: Date | undefined
  /**
   * initial_balance defines the tokens initially scheduled to receive at
   * completion.
   */
  initialBalance: string
  /** balance defines the tokens to receive at completion. */
  balance: string
}

/**
 * SVPair is struct that just has a staker-validator pair with no other data.
 * It is intended to be used as a marshalable pointer. For example, a SVPair can
 * be used to construct the key to getting an UnbondingStake from state.
 */
export interface SVPair {
  stakerAddress: string
  validatorAddress: string
}

/** SVPairs defines an array of SVPair objects. */
export interface SVPairs {
  pairs: SVPair[]
}

function createBaseStake(): Stake {
  return {
    stakerAddress: '',
    validatorAddress: '',
    shares: '',
    startHeight: 0,
    rewards: '',
    amount: '',
    unmovable: '',
  }
}

export const Stake: MessageFns<Stake> = {
  encode(message: Stake, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stakerAddress !== '') {
      writer.uint32(10).string(message.stakerAddress)
    }
    if (message.validatorAddress !== '') {
      writer.uint32(18).string(message.validatorAddress)
    }
    if (message.shares !== '') {
      writer.uint32(26).string(message.shares)
    }
    if (message.startHeight !== 0) {
      writer.uint32(32).int64(message.startHeight)
    }
    if (message.rewards !== '') {
      writer.uint32(42).string(message.rewards)
    }
    if (message.amount !== '') {
      writer.uint32(50).string(message.amount)
    }
    if (message.unmovable !== '') {
      writer.uint32(58).string(message.unmovable)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Stake {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseStake()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.stakerAddress = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.validatorAddress = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.shares = reader.string()
          continue
        }
        case 4: {
          if (tag !== 32) {
            break
          }

          message.startHeight = longToNumber(reader.int64())
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.rewards = reader.string()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.amount = reader.string()
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.unmovable = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): Stake {
    return {
      stakerAddress: isSet(object.stakerAddress)
        ? globalThis.String(object.stakerAddress)
        : isSet(object.staker_address)
          ? globalThis.String(object.staker_address)
          : '',
      validatorAddress: isSet(object.validatorAddress)
        ? globalThis.String(object.validatorAddress)
        : isSet(object.validator_address)
          ? globalThis.String(object.validator_address)
          : '',
      shares: isSet(object.shares) ? globalThis.String(object.shares) : '',
      startHeight: isSet(object.startHeight) ? globalThis.Number(object.startHeight) : 0,
      rewards: isSet(object.rewards) ? globalThis.String(object.rewards) : '',
      amount: isSet(object.amount) ? globalThis.String(object.amount) : '',
      unmovable: isSet(object.unmovable) ? globalThis.String(object.unmovable) : '',
    }
  },

  toJSON(message: Stake): unknown {
    const obj: any = {}
    if (message.stakerAddress !== '') {
      obj.stakerAddress = message.stakerAddress
    }
    if (message.validatorAddress !== '') {
      obj.validatorAddress = message.validatorAddress
    }
    if (message.shares !== '') {
      obj.shares = message.shares
    }
    if (message.startHeight !== 0) {
      obj.startHeight = Math.round(message.startHeight)
    }
    if (message.rewards !== '') {
      obj.rewards = message.rewards
    }
    if (message.amount !== '') {
      obj.amount = message.amount
    }
    if (message.unmovable !== '') {
      obj.unmovable = message.unmovable
    }
    return obj
  },

  create<I extends Exact<DeepPartial<Stake>, I>>(base?: I): Stake {
    return Stake.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<Stake>, I>>(object: I): Stake {
    const message = createBaseStake()
    message.stakerAddress = object.stakerAddress ?? ''
    message.validatorAddress = object.validatorAddress ?? ''
    message.shares = object.shares ?? ''
    message.startHeight = object.startHeight ?? 0
    message.rewards = object.rewards ?? ''
    message.amount = object.amount ?? ''
    message.unmovable = object.unmovable ?? ''
    return message
  },
}

function createBaseUnbondingStake(): UnbondingStake {
  return { stakerAddress: '', validatorAddress: '', entries: [] }
}

export const UnbondingStake: MessageFns<UnbondingStake> = {
  encode(message: UnbondingStake, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stakerAddress !== '') {
      writer.uint32(10).string(message.stakerAddress)
    }
    if (message.validatorAddress !== '') {
      writer.uint32(18).string(message.validatorAddress)
    }
    for (const v of message.entries) {
      UnbondingStakeEntry.encode(v!, writer.uint32(26).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnbondingStake {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseUnbondingStake()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.stakerAddress = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.validatorAddress = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.entries.push(UnbondingStakeEntry.decode(reader, reader.uint32()))
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): UnbondingStake {
    return {
      stakerAddress: isSet(object.stakerAddress)
        ? globalThis.String(object.stakerAddress)
        : isSet(object.staker_address)
          ? globalThis.String(object.staker_address)
          : '',
      validatorAddress: isSet(object.validatorAddress)
        ? globalThis.String(object.validatorAddress)
        : isSet(object.validator_address)
          ? globalThis.String(object.validator_address)
          : '',
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => UnbondingStakeEntry.fromJSON(e))
        : [],
    }
  },

  toJSON(message: UnbondingStake): unknown {
    const obj: any = {}
    if (message.stakerAddress !== '') {
      obj.stakerAddress = message.stakerAddress
    }
    if (message.validatorAddress !== '') {
      obj.validatorAddress = message.validatorAddress
    }
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => UnbondingStakeEntry.toJSON(e))
    }
    return obj
  },

  create<I extends Exact<DeepPartial<UnbondingStake>, I>>(base?: I): UnbondingStake {
    return UnbondingStake.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<UnbondingStake>, I>>(object: I): UnbondingStake {
    const message = createBaseUnbondingStake()
    message.stakerAddress = object.stakerAddress ?? ''
    message.validatorAddress = object.validatorAddress ?? ''
    message.entries = object.entries?.map((e) => UnbondingStakeEntry.fromPartial(e)) || []
    return message
  },
}

function createBaseUnbondingStakeEntry(): UnbondingStakeEntry {
  return { creationHeight: 0, completionTime: undefined, initialBalance: '', balance: '' }
}

export const UnbondingStakeEntry: MessageFns<UnbondingStakeEntry> = {
  encode(message: UnbondingStakeEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creationHeight !== 0) {
      writer.uint32(8).int64(message.creationHeight)
    }
    if (message.completionTime !== undefined) {
      Timestamp.encode(toTimestamp(message.completionTime), writer.uint32(18).fork()).join()
    }
    if (message.initialBalance !== '') {
      writer.uint32(26).string(message.initialBalance)
    }
    if (message.balance !== '') {
      writer.uint32(34).string(message.balance)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnbondingStakeEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseUnbondingStakeEntry()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.creationHeight = longToNumber(reader.int64())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.completionTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()))
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.initialBalance = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.balance = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): UnbondingStakeEntry {
    return {
      creationHeight: isSet(object.creationHeight)
        ? globalThis.Number(object.creationHeight)
        : isSet(object.creation_height)
          ? globalThis.Number(object.creation_height)
          : 0,
      completionTime: isSet(object.completionTime)
        ? fromJsonTimestamp(object.completionTime)
        : isSet(object.completion_time)
          ? fromJsonTimestamp(object.completion_time)
          : undefined,
      initialBalance: isSet(object.initialBalance)
        ? globalThis.String(object.initialBalance)
        : isSet(object.initial_balance)
          ? globalThis.String(object.initial_balance)
          : '',
      balance: isSet(object.balance) ? globalThis.String(object.balance) : '',
    }
  },

  toJSON(message: UnbondingStakeEntry): unknown {
    const obj: any = {}
    if (message.creationHeight !== 0) {
      obj.creationHeight = Math.round(message.creationHeight)
    }
    if (message.completionTime !== undefined) {
      obj.completionTime = message.completionTime.toISOString()
    }
    if (message.initialBalance !== '') {
      obj.initialBalance = message.initialBalance
    }
    if (message.balance !== '') {
      obj.balance = message.balance
    }
    return obj
  },

  create<I extends Exact<DeepPartial<UnbondingStakeEntry>, I>>(base?: I): UnbondingStakeEntry {
    return UnbondingStakeEntry.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<UnbondingStakeEntry>, I>>(
    object: I,
  ): UnbondingStakeEntry {
    const message = createBaseUnbondingStakeEntry()
    message.creationHeight = object.creationHeight ?? 0
    message.completionTime = object.completionTime ?? undefined
    message.initialBalance = object.initialBalance ?? ''
    message.balance = object.balance ?? ''
    return message
  },
}

function createBaseSVPair(): SVPair {
  return { stakerAddress: '', validatorAddress: '' }
}

export const SVPair: MessageFns<SVPair> = {
  encode(message: SVPair, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stakerAddress !== '') {
      writer.uint32(10).string(message.stakerAddress)
    }
    if (message.validatorAddress !== '') {
      writer.uint32(18).string(message.validatorAddress)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SVPair {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseSVPair()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.stakerAddress = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.validatorAddress = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): SVPair {
    return {
      stakerAddress: isSet(object.stakerAddress)
        ? globalThis.String(object.stakerAddress)
        : isSet(object.staker_address)
          ? globalThis.String(object.staker_address)
          : '',
      validatorAddress: isSet(object.validatorAddress)
        ? globalThis.String(object.validatorAddress)
        : isSet(object.validator_address)
          ? globalThis.String(object.validator_address)
          : '',
    }
  },

  toJSON(message: SVPair): unknown {
    const obj: any = {}
    if (message.stakerAddress !== '') {
      obj.stakerAddress = message.stakerAddress
    }
    if (message.validatorAddress !== '') {
      obj.validatorAddress = message.validatorAddress
    }
    return obj
  },

  create<I extends Exact<DeepPartial<SVPair>, I>>(base?: I): SVPair {
    return SVPair.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<SVPair>, I>>(object: I): SVPair {
    const message = createBaseSVPair()
    message.stakerAddress = object.stakerAddress ?? ''
    message.validatorAddress = object.validatorAddress ?? ''
    return message
  },
}

function createBaseSVPairs(): SVPairs {
  return { pairs: [] }
}

export const SVPairs: MessageFns<SVPairs> = {
  encode(message: SVPairs, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.pairs) {
      SVPair.encode(v!, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SVPairs {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseSVPairs()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.pairs.push(SVPair.decode(reader, reader.uint32()))
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): SVPairs {
    return {
      pairs: globalThis.Array.isArray(object?.pairs)
        ? object.pairs.map((e: any) => SVPair.fromJSON(e))
        : [],
    }
  },

  toJSON(message: SVPairs): unknown {
    const obj: any = {}
    if (message.pairs?.length) {
      obj.pairs = message.pairs.map((e) => SVPair.toJSON(e))
    }
    return obj
  },

  create<I extends Exact<DeepPartial<SVPairs>, I>>(base?: I): SVPairs {
    return SVPairs.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<SVPairs>, I>>(object: I): SVPairs {
    const message = createBaseSVPairs()
    message.pairs = object.pairs?.map((e) => SVPair.fromPartial(e)) || []
    return message
  },
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000)
  const nanos = (date.getTime() % 1_000) * 1_000_000
  return { seconds, nanos }
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000
  millis += (t.nanos || 0) / 1_000_000
  return new globalThis.Date(millis)
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o
  } else if (typeof o === 'string') {
    return new globalThis.Date(o)
  } else {
    return fromTimestamp(Timestamp.fromJSON(o))
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString())
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER')
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER')
  }
  return num
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
