// Generated by Ignite ignite.com/cli

import { StdFee } from '@cosmjs/launchpad'
import { SigningStargateClient, DeliverTxResponse } from '@cosmjs/stargate'
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from '@cosmjs/proto-signing'
import { msgTypes } from './registry'
import { IgniteClient } from '../client'
import { MissingWalletError } from '../helpers'
import { Api } from './rest'
import { MsgLeaveGroupRequest } from './types/metaearth/megroup/tx'
import { MsgDeleteGroup } from './types/metaearth/megroup/tx'
import { MsgJoinGroup } from './types/metaearth/megroup/tx'
import { MsgUpdateGroup } from './types/metaearth/megroup/tx'
import { MsgCreateGroup } from './types/metaearth/megroup/tx'

import { Group as typeGroup } from './types'
import { GroupInfo as typeGroupInfo } from './types'
import { GroupMember as typeGroupMember } from './types'
import { GroupMemberCount as typeGroupMemberCount } from './types'
import { Member as typeMember } from './types'
import { MemberJoined as typeMemberJoined } from './types'
import { Params as typeParams } from './types'
import { QueryGroupByMemberResponse as typeQueryGroupByMemberResponse } from './types'
import { QueryGetMemberJoinedRequest as typeQueryGetMemberJoinedRequest } from './types'
import { QueryGetMemberJoinedResponse as typeQueryGetMemberJoinedResponse } from './types'
import { QueryAllMemberJoinedRequest as typeQueryAllMemberJoinedRequest } from './types'
import { QueryAllMemberJoinedResponse as typeQueryAllMemberJoinedResponse } from './types'
import { QueryAllGroupMemberCountRequest as typeQueryAllGroupMemberCountRequest } from './types'
import { QueryAllGroupMemberCountResponse as typeQueryAllGroupMemberCountResponse } from './types'

export { MsgLeaveGroupRequest, MsgDeleteGroup, MsgJoinGroup, MsgUpdateGroup, MsgCreateGroup }

type sendMsgLeaveGroupRequestParams = {
  value: MsgLeaveGroupRequest
  fee?: StdFee
  memo?: string
}

type sendMsgDeleteGroupParams = {
  value: MsgDeleteGroup
  fee?: StdFee
  memo?: string
}

type sendMsgJoinGroupParams = {
  value: MsgJoinGroup
  fee?: StdFee
  memo?: string
}

type sendMsgUpdateGroupParams = {
  value: MsgUpdateGroup
  fee?: StdFee
  memo?: string
}

type sendMsgCreateGroupParams = {
  value: MsgCreateGroup
  fee?: StdFee
  memo?: string
}

type msgLeaveGroupRequestParams = {
  value: MsgLeaveGroupRequest
}

type msgDeleteGroupParams = {
  value: MsgDeleteGroup
}

type msgJoinGroupParams = {
  value: MsgJoinGroup
}

type msgUpdateGroupParams = {
  value: MsgUpdateGroup
}

type msgCreateGroupParams = {
  value: MsgCreateGroup
}

export const registry = new Registry(msgTypes)

type Field = {
  name: string
  type: unknown
}
function getStructure(template) {
  const structure: { fields: Field[] } = { fields: [] }
  for (let [key, value] of Object.entries(template)) {
    let field = { name: key, type: typeof value }
    structure.fields.push(field)
  }
  return structure
}
const defaultFee = {
  amount: [],
  gas: '200000',
}

interface TxClientOptions {
  addr: string
  prefix: string
  signer?: OfflineSigner
}

export const txClient = (
  { signer, prefix, addr }: TxClientOptions = { addr: 'http://localhost:26657', prefix: 'cosmos' },
) => {
  return {
    async sendMsgLeaveGroupRequest({
      value,
      fee,
      memo,
    }: sendMsgLeaveGroupRequestParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error(
          'TxClient:sendMsgLeaveGroupRequest: Unable to sign Tx. Signer is not present.',
        )
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, {
          registry,
          prefix,
        } as any)
        let msg = this.msgLeaveGroupRequest({ value: MsgLeaveGroupRequest.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgLeaveGroupRequest: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgDeleteGroup({
      value,
      fee,
      memo,
    }: sendMsgDeleteGroupParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgDeleteGroup: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, {
          registry,
          prefix,
        } as any)
        let msg = this.msgDeleteGroup({ value: MsgDeleteGroup.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgDeleteGroup: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgJoinGroup({
      value,
      fee,
      memo,
    }: sendMsgJoinGroupParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgJoinGroup: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, {
          registry,
          prefix,
        } as any)
        let msg = this.msgJoinGroup({ value: MsgJoinGroup.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgJoinGroup: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgUpdateGroup({
      value,
      fee,
      memo,
    }: sendMsgUpdateGroupParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgUpdateGroup: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, {
          registry,
          prefix,
        } as any)
        let msg = this.msgUpdateGroup({ value: MsgUpdateGroup.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgUpdateGroup: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgCreateGroup({
      value,
      fee,
      memo,
    }: sendMsgCreateGroupParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgCreateGroup: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, {
          registry,
          prefix,
        } as any)
        let msg = this.msgCreateGroup({ value: MsgCreateGroup.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgCreateGroup: Could not broadcast Tx: ' + e.message)
      }
    },

    msgLeaveGroupRequest({ value }: msgLeaveGroupRequestParams): EncodeObject {
      try {
        return {
          typeUrl: '/metaearth.megroup.MsgLeaveGroupRequest',
          value: MsgLeaveGroupRequest.fromPartial(value),
        }
      } catch (e: any) {
        throw new Error('TxClient:MsgLeaveGroupRequest: Could not create message: ' + e.message)
      }
    },

    msgDeleteGroup({ value }: msgDeleteGroupParams): EncodeObject {
      try {
        return {
          typeUrl: '/metaearth.megroup.MsgDeleteGroup',
          value: MsgDeleteGroup.fromPartial(value),
        }
      } catch (e: any) {
        throw new Error('TxClient:MsgDeleteGroup: Could not create message: ' + e.message)
      }
    },

    msgJoinGroup({ value }: msgJoinGroupParams): EncodeObject {
      try {
        return {
          typeUrl: '/metaearth.megroup.MsgJoinGroup',
          value: MsgJoinGroup.fromPartial(value),
        }
      } catch (e: any) {
        throw new Error('TxClient:MsgJoinGroup: Could not create message: ' + e.message)
      }
    },

    msgUpdateGroup({ value }: msgUpdateGroupParams): EncodeObject {
      try {
        return {
          typeUrl: '/metaearth.megroup.MsgUpdateGroup',
          value: MsgUpdateGroup.fromPartial(value),
        }
      } catch (e: any) {
        throw new Error('TxClient:MsgUpdateGroup: Could not create message: ' + e.message)
      }
    },

    msgCreateGroup({ value }: msgCreateGroupParams): EncodeObject {
      try {
        return {
          typeUrl: '/metaearth.megroup.MsgCreateGroup',
          value: MsgCreateGroup.fromPartial(value),
        }
      } catch (e: any) {
        throw new Error('TxClient:MsgCreateGroup: Could not create message: ' + e.message)
      }
    },
  }
}

interface QueryClientOptions {
  addr: string
}

export const queryClient = (
  { addr: addr }: QueryClientOptions = { addr: 'http://localhost:1317' },
) => {
  return new Api({ baseURL: addr })
}

class SDKModule {
  public query: ReturnType<typeof queryClient>
  public tx: ReturnType<typeof txClient>
  public structure: Record<string, unknown>
  public registry: Array<[string, GeneratedType]> = []

  constructor(client: IgniteClient) {
    this.query = queryClient({ addr: client.env.apiURL })
    this.updateTX(client)
    this.structure = {
      Group: getStructure(typeGroup.fromPartial({})),
      GroupInfo: getStructure(typeGroupInfo.fromPartial({})),
      GroupMember: getStructure(typeGroupMember.fromPartial({})),
      GroupMemberCount: getStructure(typeGroupMemberCount.fromPartial({})),
      Member: getStructure(typeMember.fromPartial({})),
      MemberJoined: getStructure(typeMemberJoined.fromPartial({})),
      Params: getStructure(typeParams.fromPartial({})),
      QueryGroupByMemberResponse: getStructure(typeQueryGroupByMemberResponse.fromPartial({})),
      QueryGetMemberJoinedRequest: getStructure(typeQueryGetMemberJoinedRequest.fromPartial({})),
      QueryGetMemberJoinedResponse: getStructure(typeQueryGetMemberJoinedResponse.fromPartial({})),
      QueryAllMemberJoinedRequest: getStructure(typeQueryAllMemberJoinedRequest.fromPartial({})),
      QueryAllMemberJoinedResponse: getStructure(typeQueryAllMemberJoinedResponse.fromPartial({})),
      QueryAllGroupMemberCountRequest: getStructure(
        typeQueryAllGroupMemberCountRequest.fromPartial({}),
      ),
      QueryAllGroupMemberCountResponse: getStructure(
        typeQueryAllGroupMemberCountResponse.fromPartial({}),
      ),
    }
    client.on('signer-changed', (signer) => {
      this.updateTX(client)
    })
  }
  updateTX(client: IgniteClient) {
    const methods = txClient({
      signer: client.signer,
      addr: client.env.rpcURL,
      prefix: client.env.prefix ?? 'cosmos',
    })

    this.tx = methods
    for (let m in methods) {
      this.tx[m] = methods[m].bind(this.tx)
    }
  }
}

const Module = (test: IgniteClient) => {
  return {
    module: {
      MetaearthMegroup: new SDKModule(test),
    },
    registry: msgTypes,
  }
}
export default Module
