// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/gravity/v1/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import { MsgConfirmBatch, MsgRelayerSetConfirm } from './tx'
import {
  Attestation,
  BridgeToken,
  LastObservedBlockHeight,
  OutgoingTransferTx,
  OutgoingTxBatch,
  Params,
  ProposalRelayer,
  Relayer,
  RelayerSet,
} from './types'

export const protobufPackage = 'metaearth.gravity.v1'

export interface GenesisState {
  params: Params | undefined
  lastObservedEventNonce: number
  lastObservedBlockHeight: LastObservedBlockHeight | undefined
  relayers: Relayer[]
  relayerSets: RelayerSet[]
  bridgeTokens: BridgeToken[]
  unbatchedTransfers: OutgoingTransferTx[]
  batches: OutgoingTxBatch[]
  relayerSetConfirms: MsgRelayerSetConfirm[]
  batchConfirms: MsgConfirmBatch[]
  attestations: Attestation[]
  proposalRelayer: ProposalRelayer | undefined
  lastObservedRelayerSet: RelayerSet | undefined
  lastSlashedBatchBlock: number
  lastSlashedRelayerSetNonce: number
}

function createBaseGenesisState(): GenesisState {
  return {
    params: undefined,
    lastObservedEventNonce: 0,
    lastObservedBlockHeight: undefined,
    relayers: [],
    relayerSets: [],
    bridgeTokens: [],
    unbatchedTransfers: [],
    batches: [],
    relayerSetConfirms: [],
    batchConfirms: [],
    attestations: [],
    proposalRelayer: undefined,
    lastObservedRelayerSet: undefined,
    lastSlashedBatchBlock: 0,
    lastSlashedRelayerSetNonce: 0,
  }
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join()
    }
    if (message.lastObservedEventNonce !== 0) {
      writer.uint32(16).uint64(message.lastObservedEventNonce)
    }
    if (message.lastObservedBlockHeight !== undefined) {
      LastObservedBlockHeight.encode(
        message.lastObservedBlockHeight,
        writer.uint32(26).fork(),
      ).join()
    }
    for (const v of message.relayers) {
      Relayer.encode(v!, writer.uint32(34).fork()).join()
    }
    for (const v of message.relayerSets) {
      RelayerSet.encode(v!, writer.uint32(42).fork()).join()
    }
    for (const v of message.bridgeTokens) {
      BridgeToken.encode(v!, writer.uint32(50).fork()).join()
    }
    for (const v of message.unbatchedTransfers) {
      OutgoingTransferTx.encode(v!, writer.uint32(58).fork()).join()
    }
    for (const v of message.batches) {
      OutgoingTxBatch.encode(v!, writer.uint32(66).fork()).join()
    }
    for (const v of message.relayerSetConfirms) {
      MsgRelayerSetConfirm.encode(v!, writer.uint32(74).fork()).join()
    }
    for (const v of message.batchConfirms) {
      MsgConfirmBatch.encode(v!, writer.uint32(82).fork()).join()
    }
    for (const v of message.attestations) {
      Attestation.encode(v!, writer.uint32(90).fork()).join()
    }
    if (message.proposalRelayer !== undefined) {
      ProposalRelayer.encode(message.proposalRelayer, writer.uint32(98).fork()).join()
    }
    if (message.lastObservedRelayerSet !== undefined) {
      RelayerSet.encode(message.lastObservedRelayerSet, writer.uint32(106).fork()).join()
    }
    if (message.lastSlashedBatchBlock !== 0) {
      writer.uint32(112).uint64(message.lastSlashedBatchBlock)
    }
    if (message.lastSlashedRelayerSetNonce !== 0) {
      writer.uint32(120).uint64(message.lastSlashedRelayerSetNonce)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseGenesisState()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.params = Params.decode(reader, reader.uint32())
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.lastObservedEventNonce = longToNumber(reader.uint64())
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.lastObservedBlockHeight = LastObservedBlockHeight.decode(reader, reader.uint32())
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.relayers.push(Relayer.decode(reader, reader.uint32()))
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.relayerSets.push(RelayerSet.decode(reader, reader.uint32()))
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.bridgeTokens.push(BridgeToken.decode(reader, reader.uint32()))
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.unbatchedTransfers.push(OutgoingTransferTx.decode(reader, reader.uint32()))
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.batches.push(OutgoingTxBatch.decode(reader, reader.uint32()))
          continue
        }
        case 9: {
          if (tag !== 74) {
            break
          }

          message.relayerSetConfirms.push(MsgRelayerSetConfirm.decode(reader, reader.uint32()))
          continue
        }
        case 10: {
          if (tag !== 82) {
            break
          }

          message.batchConfirms.push(MsgConfirmBatch.decode(reader, reader.uint32()))
          continue
        }
        case 11: {
          if (tag !== 90) {
            break
          }

          message.attestations.push(Attestation.decode(reader, reader.uint32()))
          continue
        }
        case 12: {
          if (tag !== 98) {
            break
          }

          message.proposalRelayer = ProposalRelayer.decode(reader, reader.uint32())
          continue
        }
        case 13: {
          if (tag !== 106) {
            break
          }

          message.lastObservedRelayerSet = RelayerSet.decode(reader, reader.uint32())
          continue
        }
        case 14: {
          if (tag !== 112) {
            break
          }

          message.lastSlashedBatchBlock = longToNumber(reader.uint64())
          continue
        }
        case 15: {
          if (tag !== 120) {
            break
          }

          message.lastSlashedRelayerSetNonce = longToNumber(reader.uint64())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      lastObservedEventNonce: isSet(object.lastObservedEventNonce)
        ? globalThis.Number(object.lastObservedEventNonce)
        : isSet(object.last_observed_event_nonce)
          ? globalThis.Number(object.last_observed_event_nonce)
          : 0,
      lastObservedBlockHeight: isSet(object.lastObservedBlockHeight)
        ? LastObservedBlockHeight.fromJSON(object.lastObservedBlockHeight)
        : isSet(object.last_observed_block_height)
          ? LastObservedBlockHeight.fromJSON(object.last_observed_block_height)
          : undefined,
      relayers: globalThis.Array.isArray(object?.relayers)
        ? object.relayers.map((e: any) => Relayer.fromJSON(e))
        : [],
      relayerSets: globalThis.Array.isArray(object?.relayerSets)
        ? object.relayerSets.map((e: any) => RelayerSet.fromJSON(e))
        : globalThis.Array.isArray(object?.relayer_sets)
          ? object.relayer_sets.map((e: any) => RelayerSet.fromJSON(e))
          : [],
      bridgeTokens: globalThis.Array.isArray(object?.bridgeTokens)
        ? object.bridgeTokens.map((e: any) => BridgeToken.fromJSON(e))
        : globalThis.Array.isArray(object?.bridge_tokens)
          ? object.bridge_tokens.map((e: any) => BridgeToken.fromJSON(e))
          : [],
      unbatchedTransfers: globalThis.Array.isArray(object?.unbatchedTransfers)
        ? object.unbatchedTransfers.map((e: any) => OutgoingTransferTx.fromJSON(e))
        : globalThis.Array.isArray(object?.unbatched_transfers)
          ? object.unbatched_transfers.map((e: any) => OutgoingTransferTx.fromJSON(e))
          : [],
      batches: globalThis.Array.isArray(object?.batches)
        ? object.batches.map((e: any) => OutgoingTxBatch.fromJSON(e))
        : [],
      relayerSetConfirms: globalThis.Array.isArray(object?.relayerSetConfirms)
        ? object.relayerSetConfirms.map((e: any) => MsgRelayerSetConfirm.fromJSON(e))
        : globalThis.Array.isArray(object?.relayer_set_confirms)
          ? object.relayer_set_confirms.map((e: any) => MsgRelayerSetConfirm.fromJSON(e))
          : [],
      batchConfirms: globalThis.Array.isArray(object?.batchConfirms)
        ? object.batchConfirms.map((e: any) => MsgConfirmBatch.fromJSON(e))
        : globalThis.Array.isArray(object?.batch_confirms)
          ? object.batch_confirms.map((e: any) => MsgConfirmBatch.fromJSON(e))
          : [],
      attestations: globalThis.Array.isArray(object?.attestations)
        ? object.attestations.map((e: any) => Attestation.fromJSON(e))
        : [],
      proposalRelayer: isSet(object.proposalRelayer)
        ? ProposalRelayer.fromJSON(object.proposalRelayer)
        : isSet(object.proposal_relayer)
          ? ProposalRelayer.fromJSON(object.proposal_relayer)
          : undefined,
      lastObservedRelayerSet: isSet(object.lastObservedRelayerSet)
        ? RelayerSet.fromJSON(object.lastObservedRelayerSet)
        : isSet(object.last_observed_relayer_set)
          ? RelayerSet.fromJSON(object.last_observed_relayer_set)
          : undefined,
      lastSlashedBatchBlock: isSet(object.lastSlashedBatchBlock)
        ? globalThis.Number(object.lastSlashedBatchBlock)
        : isSet(object.last_slashed_batch_block)
          ? globalThis.Number(object.last_slashed_batch_block)
          : 0,
      lastSlashedRelayerSetNonce: isSet(object.lastSlashedRelayerSetNonce)
        ? globalThis.Number(object.lastSlashedRelayerSetNonce)
        : isSet(object.last_slashed_relayer_set_nonce)
          ? globalThis.Number(object.last_slashed_relayer_set_nonce)
          : 0,
    }
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {}
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params)
    }
    if (message.lastObservedEventNonce !== 0) {
      obj.lastObservedEventNonce = Math.round(message.lastObservedEventNonce)
    }
    if (message.lastObservedBlockHeight !== undefined) {
      obj.lastObservedBlockHeight = LastObservedBlockHeight.toJSON(message.lastObservedBlockHeight)
    }
    if (message.relayers?.length) {
      obj.relayers = message.relayers.map((e) => Relayer.toJSON(e))
    }
    if (message.relayerSets?.length) {
      obj.relayerSets = message.relayerSets.map((e) => RelayerSet.toJSON(e))
    }
    if (message.bridgeTokens?.length) {
      obj.bridgeTokens = message.bridgeTokens.map((e) => BridgeToken.toJSON(e))
    }
    if (message.unbatchedTransfers?.length) {
      obj.unbatchedTransfers = message.unbatchedTransfers.map((e) => OutgoingTransferTx.toJSON(e))
    }
    if (message.batches?.length) {
      obj.batches = message.batches.map((e) => OutgoingTxBatch.toJSON(e))
    }
    if (message.relayerSetConfirms?.length) {
      obj.relayerSetConfirms = message.relayerSetConfirms.map((e) => MsgRelayerSetConfirm.toJSON(e))
    }
    if (message.batchConfirms?.length) {
      obj.batchConfirms = message.batchConfirms.map((e) => MsgConfirmBatch.toJSON(e))
    }
    if (message.attestations?.length) {
      obj.attestations = message.attestations.map((e) => Attestation.toJSON(e))
    }
    if (message.proposalRelayer !== undefined) {
      obj.proposalRelayer = ProposalRelayer.toJSON(message.proposalRelayer)
    }
    if (message.lastObservedRelayerSet !== undefined) {
      obj.lastObservedRelayerSet = RelayerSet.toJSON(message.lastObservedRelayerSet)
    }
    if (message.lastSlashedBatchBlock !== 0) {
      obj.lastSlashedBatchBlock = Math.round(message.lastSlashedBatchBlock)
    }
    if (message.lastSlashedRelayerSetNonce !== 0) {
      obj.lastSlashedRelayerSetNonce = Math.round(message.lastSlashedRelayerSetNonce)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState()
    message.params =
      object.params !== undefined && object.params !== null
        ? Params.fromPartial(object.params)
        : undefined
    message.lastObservedEventNonce = object.lastObservedEventNonce ?? 0
    message.lastObservedBlockHeight =
      object.lastObservedBlockHeight !== undefined && object.lastObservedBlockHeight !== null
        ? LastObservedBlockHeight.fromPartial(object.lastObservedBlockHeight)
        : undefined
    message.relayers = object.relayers?.map((e) => Relayer.fromPartial(e)) || []
    message.relayerSets = object.relayerSets?.map((e) => RelayerSet.fromPartial(e)) || []
    message.bridgeTokens = object.bridgeTokens?.map((e) => BridgeToken.fromPartial(e)) || []
    message.unbatchedTransfers =
      object.unbatchedTransfers?.map((e) => OutgoingTransferTx.fromPartial(e)) || []
    message.batches = object.batches?.map((e) => OutgoingTxBatch.fromPartial(e)) || []
    message.relayerSetConfirms =
      object.relayerSetConfirms?.map((e) => MsgRelayerSetConfirm.fromPartial(e)) || []
    message.batchConfirms = object.batchConfirms?.map((e) => MsgConfirmBatch.fromPartial(e)) || []
    message.attestations = object.attestations?.map((e) => Attestation.fromPartial(e)) || []
    message.proposalRelayer =
      object.proposalRelayer !== undefined && object.proposalRelayer !== null
        ? ProposalRelayer.fromPartial(object.proposalRelayer)
        : undefined
    message.lastObservedRelayerSet =
      object.lastObservedRelayerSet !== undefined && object.lastObservedRelayerSet !== null
        ? RelayerSet.fromPartial(object.lastObservedRelayerSet)
        : undefined
    message.lastSlashedBatchBlock = object.lastSlashedBatchBlock ?? 0
    message.lastSlashedRelayerSetNonce = object.lastSlashedRelayerSetNonce ?? 0
    return message
  },
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString())
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER')
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER')
  }
  return num
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
