// Generated by Ignite ignite.com/cli

import { StdFee } from '@cosmjs/launchpad'
import { SigningStargateClient, DeliverTxResponse } from '@cosmjs/stargate'
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from '@cosmjs/proto-signing'
import { msgTypes } from './registry'
import { IgniteClient } from '../client'
import { MissingWalletError } from '../helpers'
import { Api } from './rest'
import { MsgUpdateDao } from './types/metaearth/dao/tx'

import { DaoAddresses as typeDaoAddresses } from './types'

export { MsgUpdateDao }

type sendMsgUpdateDaoParams = {
  value: MsgUpdateDao
  fee?: StdFee
  memo?: string
}

type msgUpdateDaoParams = {
  value: MsgUpdateDao
}

export const registry = new Registry(msgTypes)

type Field = {
  name: string
  type: unknown
}
function getStructure(template) {
  const structure: { fields: Field[] } = { fields: [] }
  for (let [key, value] of Object.entries(template)) {
    let field = { name: key, type: typeof value }
    structure.fields.push(field)
  }
  return structure
}
const defaultFee = {
  amount: [],
  gas: '200000',
}

interface TxClientOptions {
  addr: string
  prefix: string
  signer?: OfflineSigner
}

export const txClient = (
  { signer, prefix, addr }: TxClientOptions = { addr: 'http://localhost:26657', prefix: 'cosmos' },
) => {
  return {
    async sendMsgUpdateDao({
      value,
      fee,
      memo,
    }: sendMsgUpdateDaoParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgUpdateDao: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0]
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, {
          registry,
        } as any)
        let msg = this.msgUpdateDao({ value: MsgUpdateDao.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgUpdateDao: Could not broadcast Tx: ' + e.message)
      }
    },

    msgUpdateDao({ value }: msgUpdateDaoParams): EncodeObject {
      try {
        return { typeUrl: '/metaearth.dao.MsgUpdateDao', value: MsgUpdateDao.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgUpdateDao: Could not create message: ' + e.message)
      }
    },
  }
}

interface QueryClientOptions {
  addr: string
}

export const queryClient = (
  { addr: addr }: QueryClientOptions = { addr: 'http://localhost:1317' },
) => {
  return new Api({ baseURL: addr })
}

class SDKModule {
  public query: ReturnType<typeof queryClient>
  public tx: ReturnType<typeof txClient>
  public structure: Record<string, unknown>
  public registry: Array<[string, GeneratedType]> = []

  constructor(client: IgniteClient) {
    this.query = queryClient({ addr: client.env.apiURL })
    this.updateTX(client)
    this.structure = {
      DaoAddresses: getStructure(typeDaoAddresses.fromPartial({})),
    }
    client.on('signer-changed', (signer) => {
      this.updateTX(client)
    })
  }
  updateTX(client: IgniteClient) {
    const methods = txClient({
      signer: client.signer,
      addr: client.env.rpcURL,
      prefix: client.env.prefix ?? 'cosmos',
    })

    this.tx = methods
    for (let m in methods) {
      this.tx[m] = methods[m].bind(this.tx)
    }
  }
}

const Module = (test: IgniteClient) => {
  return {
    module: {
      MetaearthDao: new SDKModule(test),
    },
    registry: msgTypes,
  }
}
export default Module
