// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: metaearth/kyc/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import { PageRequest, PageResponse } from '../../cosmos/base/query/v1beta1/pagination'
import { NFT } from '../../cosmos/nft/v1beta1/nft'
import { Credential } from '../did/credential'
import { DidInfo } from '../did/did'
import { Protocol } from './protocol'

export const protobufPackage = 'metaearth.kyc'

export interface QueryProtocol {}

export interface QueryProtocolResponse {
  protocol: Protocol | undefined
}

export interface QueryDID {
  address: string
}

export interface QueryDIDResponse {
  info: DidInfo | undefined
}

export interface QueryDIDs {
  regionId: string
  pagination: PageRequest | undefined
}

export interface QueryDIDsResponse {
  infos: DidInfo[]
  pagination: PageResponse | undefined
}

export interface QueryKYC {
  did: string
}

export interface QueryKYCResponse {
  kyc: Credential | undefined
}

export interface QueryKYCs {
  regionId: string
  pagination: PageRequest | undefined
}

export interface QueryKYCsResponse {
  KYCs: Credential[]
  pagination: PageResponse | undefined
}

export interface QuerySBT {
  did: string
}

export interface QuerySBTResponse {
  sbt: NFT | undefined
}

export interface QuerySubAccountDid {
  subAccount: string
}

export interface QuerySubAccountDidResponse {
  info: DidInfo | undefined
}

function createBaseQueryProtocol(): QueryProtocol {
  return {}
}

export const QueryProtocol: MessageFns<QueryProtocol> = {
  encode(_: QueryProtocol, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryProtocol {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryProtocol()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): QueryProtocol {
    return {}
  },

  toJSON(_: QueryProtocol): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<QueryProtocol>, I>>(base?: I): QueryProtocol {
    return QueryProtocol.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryProtocol>, I>>(_: I): QueryProtocol {
    const message = createBaseQueryProtocol()
    return message
  },
}

function createBaseQueryProtocolResponse(): QueryProtocolResponse {
  return { protocol: undefined }
}

export const QueryProtocolResponse: MessageFns<QueryProtocolResponse> = {
  encode(message: QueryProtocolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.protocol !== undefined) {
      Protocol.encode(message.protocol, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryProtocolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryProtocolResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.protocol = Protocol.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryProtocolResponse {
    return { protocol: isSet(object.protocol) ? Protocol.fromJSON(object.protocol) : undefined }
  },

  toJSON(message: QueryProtocolResponse): unknown {
    const obj: any = {}
    if (message.protocol !== undefined) {
      obj.protocol = Protocol.toJSON(message.protocol)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryProtocolResponse>, I>>(base?: I): QueryProtocolResponse {
    return QueryProtocolResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryProtocolResponse>, I>>(
    object: I,
  ): QueryProtocolResponse {
    const message = createBaseQueryProtocolResponse()
    message.protocol =
      object.protocol !== undefined && object.protocol !== null
        ? Protocol.fromPartial(object.protocol)
        : undefined
    return message
  },
}

function createBaseQueryDID(): QueryDID {
  return { address: '' }
}

export const QueryDID: MessageFns<QueryDID> = {
  encode(message: QueryDID, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== '') {
      writer.uint32(10).string(message.address)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDID {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryDID()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.address = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryDID {
    return { address: isSet(object.address) ? globalThis.String(object.address) : '' }
  },

  toJSON(message: QueryDID): unknown {
    const obj: any = {}
    if (message.address !== '') {
      obj.address = message.address
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryDID>, I>>(base?: I): QueryDID {
    return QueryDID.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryDID>, I>>(object: I): QueryDID {
    const message = createBaseQueryDID()
    message.address = object.address ?? ''
    return message
  },
}

function createBaseQueryDIDResponse(): QueryDIDResponse {
  return { info: undefined }
}

export const QueryDIDResponse: MessageFns<QueryDIDResponse> = {
  encode(message: QueryDIDResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.info !== undefined) {
      DidInfo.encode(message.info, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDIDResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryDIDResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.info = DidInfo.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryDIDResponse {
    return { info: isSet(object.info) ? DidInfo.fromJSON(object.info) : undefined }
  },

  toJSON(message: QueryDIDResponse): unknown {
    const obj: any = {}
    if (message.info !== undefined) {
      obj.info = DidInfo.toJSON(message.info)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryDIDResponse>, I>>(base?: I): QueryDIDResponse {
    return QueryDIDResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryDIDResponse>, I>>(object: I): QueryDIDResponse {
    const message = createBaseQueryDIDResponse()
    message.info =
      object.info !== undefined && object.info !== null
        ? DidInfo.fromPartial(object.info)
        : undefined
    return message
  },
}

function createBaseQueryDIDs(): QueryDIDs {
  return { regionId: '', pagination: undefined }
}

export const QueryDIDs: MessageFns<QueryDIDs> = {
  encode(message: QueryDIDs, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.regionId !== '') {
      writer.uint32(10).string(message.regionId)
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDIDs {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryDIDs()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.regionId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.pagination = PageRequest.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryDIDs {
    return {
      regionId: isSet(object.regionId) ? globalThis.String(object.regionId) : '',
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryDIDs): unknown {
    const obj: any = {}
    if (message.regionId !== '') {
      obj.regionId = message.regionId
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryDIDs>, I>>(base?: I): QueryDIDs {
    return QueryDIDs.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryDIDs>, I>>(object: I): QueryDIDs {
    const message = createBaseQueryDIDs()
    message.regionId = object.regionId ?? ''
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageRequest.fromPartial(object.pagination)
        : undefined
    return message
  },
}

function createBaseQueryDIDsResponse(): QueryDIDsResponse {
  return { infos: [], pagination: undefined }
}

export const QueryDIDsResponse: MessageFns<QueryDIDsResponse> = {
  encode(message: QueryDIDsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.infos) {
      DidInfo.encode(v!, writer.uint32(10).fork()).join()
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryDIDsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryDIDsResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.infos.push(DidInfo.decode(reader, reader.uint32()))
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.pagination = PageResponse.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryDIDsResponse {
    return {
      infos: globalThis.Array.isArray(object?.infos)
        ? object.infos.map((e: any) => DidInfo.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryDIDsResponse): unknown {
    const obj: any = {}
    if (message.infos?.length) {
      obj.infos = message.infos.map((e) => DidInfo.toJSON(e))
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryDIDsResponse>, I>>(base?: I): QueryDIDsResponse {
    return QueryDIDsResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryDIDsResponse>, I>>(object: I): QueryDIDsResponse {
    const message = createBaseQueryDIDsResponse()
    message.infos = object.infos?.map((e) => DidInfo.fromPartial(e)) || []
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageResponse.fromPartial(object.pagination)
        : undefined
    return message
  },
}

function createBaseQueryKYC(): QueryKYC {
  return { did: '' }
}

export const QueryKYC: MessageFns<QueryKYC> = {
  encode(message: QueryKYC, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.did !== '') {
      writer.uint32(10).string(message.did)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryKYC {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryKYC()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.did = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryKYC {
    return { did: isSet(object.did) ? globalThis.String(object.did) : '' }
  },

  toJSON(message: QueryKYC): unknown {
    const obj: any = {}
    if (message.did !== '') {
      obj.did = message.did
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryKYC>, I>>(base?: I): QueryKYC {
    return QueryKYC.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryKYC>, I>>(object: I): QueryKYC {
    const message = createBaseQueryKYC()
    message.did = object.did ?? ''
    return message
  },
}

function createBaseQueryKYCResponse(): QueryKYCResponse {
  return { kyc: undefined }
}

export const QueryKYCResponse: MessageFns<QueryKYCResponse> = {
  encode(message: QueryKYCResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.kyc !== undefined) {
      Credential.encode(message.kyc, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryKYCResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryKYCResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.kyc = Credential.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryKYCResponse {
    return { kyc: isSet(object.kyc) ? Credential.fromJSON(object.kyc) : undefined }
  },

  toJSON(message: QueryKYCResponse): unknown {
    const obj: any = {}
    if (message.kyc !== undefined) {
      obj.kyc = Credential.toJSON(message.kyc)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryKYCResponse>, I>>(base?: I): QueryKYCResponse {
    return QueryKYCResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryKYCResponse>, I>>(object: I): QueryKYCResponse {
    const message = createBaseQueryKYCResponse()
    message.kyc =
      object.kyc !== undefined && object.kyc !== null
        ? Credential.fromPartial(object.kyc)
        : undefined
    return message
  },
}

function createBaseQueryKYCs(): QueryKYCs {
  return { regionId: '', pagination: undefined }
}

export const QueryKYCs: MessageFns<QueryKYCs> = {
  encode(message: QueryKYCs, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.regionId !== '') {
      writer.uint32(10).string(message.regionId)
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryKYCs {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryKYCs()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.regionId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.pagination = PageRequest.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryKYCs {
    return {
      regionId: isSet(object.regionId) ? globalThis.String(object.regionId) : '',
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryKYCs): unknown {
    const obj: any = {}
    if (message.regionId !== '') {
      obj.regionId = message.regionId
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryKYCs>, I>>(base?: I): QueryKYCs {
    return QueryKYCs.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryKYCs>, I>>(object: I): QueryKYCs {
    const message = createBaseQueryKYCs()
    message.regionId = object.regionId ?? ''
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageRequest.fromPartial(object.pagination)
        : undefined
    return message
  },
}

function createBaseQueryKYCsResponse(): QueryKYCsResponse {
  return { KYCs: [], pagination: undefined }
}

export const QueryKYCsResponse: MessageFns<QueryKYCsResponse> = {
  encode(message: QueryKYCsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.KYCs) {
      Credential.encode(v!, writer.uint32(10).fork()).join()
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryKYCsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQueryKYCsResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.KYCs.push(Credential.decode(reader, reader.uint32()))
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.pagination = PageResponse.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QueryKYCsResponse {
    return {
      KYCs: globalThis.Array.isArray(object?.KYCs)
        ? object.KYCs.map((e: any) => Credential.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    }
  },

  toJSON(message: QueryKYCsResponse): unknown {
    const obj: any = {}
    if (message.KYCs?.length) {
      obj.KYCs = message.KYCs.map((e) => Credential.toJSON(e))
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QueryKYCsResponse>, I>>(base?: I): QueryKYCsResponse {
    return QueryKYCsResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QueryKYCsResponse>, I>>(object: I): QueryKYCsResponse {
    const message = createBaseQueryKYCsResponse()
    message.KYCs = object.KYCs?.map((e) => Credential.fromPartial(e)) || []
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? PageResponse.fromPartial(object.pagination)
        : undefined
    return message
  },
}

function createBaseQuerySBT(): QuerySBT {
  return { did: '' }
}

export const QuerySBT: MessageFns<QuerySBT> = {
  encode(message: QuerySBT, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.did !== '') {
      writer.uint32(10).string(message.did)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySBT {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQuerySBT()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.did = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QuerySBT {
    return { did: isSet(object.did) ? globalThis.String(object.did) : '' }
  },

  toJSON(message: QuerySBT): unknown {
    const obj: any = {}
    if (message.did !== '') {
      obj.did = message.did
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QuerySBT>, I>>(base?: I): QuerySBT {
    return QuerySBT.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QuerySBT>, I>>(object: I): QuerySBT {
    const message = createBaseQuerySBT()
    message.did = object.did ?? ''
    return message
  },
}

function createBaseQuerySBTResponse(): QuerySBTResponse {
  return { sbt: undefined }
}

export const QuerySBTResponse: MessageFns<QuerySBTResponse> = {
  encode(message: QuerySBTResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sbt !== undefined) {
      NFT.encode(message.sbt, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySBTResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQuerySBTResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.sbt = NFT.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QuerySBTResponse {
    return { sbt: isSet(object.sbt) ? NFT.fromJSON(object.sbt) : undefined }
  },

  toJSON(message: QuerySBTResponse): unknown {
    const obj: any = {}
    if (message.sbt !== undefined) {
      obj.sbt = NFT.toJSON(message.sbt)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QuerySBTResponse>, I>>(base?: I): QuerySBTResponse {
    return QuerySBTResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QuerySBTResponse>, I>>(object: I): QuerySBTResponse {
    const message = createBaseQuerySBTResponse()
    message.sbt =
      object.sbt !== undefined && object.sbt !== null ? NFT.fromPartial(object.sbt) : undefined
    return message
  },
}

function createBaseQuerySubAccountDid(): QuerySubAccountDid {
  return { subAccount: '' }
}

export const QuerySubAccountDid: MessageFns<QuerySubAccountDid> = {
  encode(message: QuerySubAccountDid, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subAccount !== '') {
      writer.uint32(10).string(message.subAccount)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySubAccountDid {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQuerySubAccountDid()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.subAccount = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QuerySubAccountDid {
    return {
      subAccount: isSet(object.subAccount)
        ? globalThis.String(object.subAccount)
        : isSet(object.sub_account)
          ? globalThis.String(object.sub_account)
          : '',
    }
  },

  toJSON(message: QuerySubAccountDid): unknown {
    const obj: any = {}
    if (message.subAccount !== '') {
      obj.subAccount = message.subAccount
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QuerySubAccountDid>, I>>(base?: I): QuerySubAccountDid {
    return QuerySubAccountDid.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QuerySubAccountDid>, I>>(object: I): QuerySubAccountDid {
    const message = createBaseQuerySubAccountDid()
    message.subAccount = object.subAccount ?? ''
    return message
  },
}

function createBaseQuerySubAccountDidResponse(): QuerySubAccountDidResponse {
  return { info: undefined }
}

export const QuerySubAccountDidResponse: MessageFns<QuerySubAccountDidResponse> = {
  encode(
    message: QuerySubAccountDidResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.info !== undefined) {
      DidInfo.encode(message.info, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySubAccountDidResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseQuerySubAccountDidResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.info = DidInfo.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): QuerySubAccountDidResponse {
    return { info: isSet(object.info) ? DidInfo.fromJSON(object.info) : undefined }
  },

  toJSON(message: QuerySubAccountDidResponse): unknown {
    const obj: any = {}
    if (message.info !== undefined) {
      obj.info = DidInfo.toJSON(message.info)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<QuerySubAccountDidResponse>, I>>(
    base?: I,
  ): QuerySubAccountDidResponse {
    return QuerySubAccountDidResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<QuerySubAccountDidResponse>, I>>(
    object: I,
  ): QuerySubAccountDidResponse {
    const message = createBaseQuerySubAccountDidResponse()
    message.info =
      object.info !== undefined && object.info !== null
        ? DidInfo.fromPartial(object.info)
        : undefined
    return message
  },
}

export interface Query {
  /** query protocol */
  Protocol(request: QueryProtocol): Promise<QueryProtocolResponse>
  DID(request: QueryDID): Promise<QueryDIDResponse>
  DIDs(request: QueryDIDs): Promise<QueryDIDsResponse>
  KYC(request: QueryKYC): Promise<QueryKYCResponse>
  KYCs(request: QueryKYCs): Promise<QueryKYCsResponse>
  SBT(request: QuerySBT): Promise<QuerySBTResponse>
  SubAccountDid(request: QuerySubAccountDid): Promise<QuerySubAccountDidResponse>
}

export const QueryServiceName = 'metaearth.kyc.Query'
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc
  private readonly service: string
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName
    this.rpc = rpc
    this.Protocol = this.Protocol.bind(this)
    this.DID = this.DID.bind(this)
    this.DIDs = this.DIDs.bind(this)
    this.KYC = this.KYC.bind(this)
    this.KYCs = this.KYCs.bind(this)
    this.SBT = this.SBT.bind(this)
    this.SubAccountDid = this.SubAccountDid.bind(this)
  }
  Protocol(request: QueryProtocol): Promise<QueryProtocolResponse> {
    const data = QueryProtocol.encode(request).finish()
    const promise = this.rpc.request(this.service, 'Protocol', data)
    return promise.then((data) => QueryProtocolResponse.decode(new BinaryReader(data)))
  }

  DID(request: QueryDID): Promise<QueryDIDResponse> {
    const data = QueryDID.encode(request).finish()
    const promise = this.rpc.request(this.service, 'DID', data)
    return promise.then((data) => QueryDIDResponse.decode(new BinaryReader(data)))
  }

  DIDs(request: QueryDIDs): Promise<QueryDIDsResponse> {
    const data = QueryDIDs.encode(request).finish()
    const promise = this.rpc.request(this.service, 'DIDs', data)
    return promise.then((data) => QueryDIDsResponse.decode(new BinaryReader(data)))
  }

  KYC(request: QueryKYC): Promise<QueryKYCResponse> {
    const data = QueryKYC.encode(request).finish()
    const promise = this.rpc.request(this.service, 'KYC', data)
    return promise.then((data) => QueryKYCResponse.decode(new BinaryReader(data)))
  }

  KYCs(request: QueryKYCs): Promise<QueryKYCsResponse> {
    const data = QueryKYCs.encode(request).finish()
    const promise = this.rpc.request(this.service, 'KYCs', data)
    return promise.then((data) => QueryKYCsResponse.decode(new BinaryReader(data)))
  }

  SBT(request: QuerySBT): Promise<QuerySBTResponse> {
    const data = QuerySBT.encode(request).finish()
    const promise = this.rpc.request(this.service, 'SBT', data)
    return promise.then((data) => QuerySBTResponse.decode(new BinaryReader(data)))
  }

  SubAccountDid(request: QuerySubAccountDid): Promise<QuerySubAccountDidResponse> {
    const data = QuerySubAccountDid.encode(request).finish()
    const promise = this.rpc.request(this.service, 'SubAccountDid', data)
    return promise.then((data) => QuerySubAccountDidResponse.decode(new BinaryReader(data)))
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
